### ISSUE TITLE
Evaluate the need for the media session extension

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1023]
We're using an internal media session extension that used to provide some "fixes" on top of the media session object. This was added almost 2 years ago when wolvic was using GeckoView v95. I am not aware of the rationale but I'd say that there are high chances that we don't need the extension anymore.

In any case we should evaluate it.

**Comment by HollowMan6** [comment]
Currently, we use the canSeek() method of the mediaSession to check if the video is seekable, it will become `LIVE` if it's unseekable. 

https://github.com/Igalia/wolvic/blob/5dd7e2c99ebce3b102144c58d68ba9b3a94c2580/app/src/common/shared/com/igalia/wolvic/ui/widgets/MediaControlsWidget.java#L314
https://github.com/Igalia/wolvic/blob/5dd7e2c99ebce3b102144c58d68ba9b3a94c2580/app/src/common/shared/com/igalia/wolvic/ui/views/MediaSeekBar.java#L130-L150

Unfortunately, when I tried to remove the [fxr_mediasession](https://github.com/Igalia/wolvic/tree/5dd7e2c99ebce3b102144c58d68ba9b3a94c2580/app/src/main/assets/extensions/fxr_mediasession) and play video in Youtube, it becomes live (no media position and unseekable), so we will still need the plugin.

Further investigate the plugin, and you will find that we actually rely on the navigator.mediaSession.setPositionState to get the media position information.

https://github.com/Igalia/wolvic/blob/5dd7e2c99ebce3b102144c58d68ba9b3a94c2580/app/src/main/assets/extensions/fxr_mediasession/main.js#L7-L15

Refer to the API documentation: https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setPositionState It's introduced in Gecko 82

> The [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) method setPositionState() is used to update the current document's media playback position and speed for presentation by the user's device in any kind of interface that provides details about ongoing media.

So I guess maybe the plugin is not for providing some "fixes" on top of the media session object, but rather for adapting the breaking change introduced in Gecko 82 (`setPositionState()`), which requires us to implement our own method of controlling the playback position and speed.

Moreover, I think it's perfectly safe to keep the plugin even if the webpage implements all the functionalities of that plugin / later the Gecko/Chromium supports seeking natively again, as I don't think it will cause any collision (should always have the same state of the video).

![com igalia wolvic-20230928-105842](https://github.com/Igalia/wolvic/assets/43995067/4eb994ec-3278-49aa-bd90-7cce880bfef1)
