### ISSUE TITLE
Hands disappear randomly while hand-tracking is active

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#1038]
## Configuration

Wolvic version: 1.5
Wolvic build ID: 205

Hardware: Quest2, system version 57.0.0

## Steps to Reproduce

1. Enable hand-tracking feature
2. Open Wolvic and leave the controllers aside to activate hand-tracking
3. Hands are visible and user can interact with Wolvic

## Current Behavior

After a few seconds, the hands disappear, together with the pointer beam and target, as if hand-tracking was completely disabled. 

## Expected Behavior

Hands should continue to be shown, with pointer beam and target.

**Comment by svillar** [comment]
I haven't seen this, is still an issue for you?
