### ISSUE TITLE
wolvic 1.5 @huawei vr glass， controller cannot work

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#1053]
## Configuration

Wolvic version: 1.5
Wolvic build ID: 

Hardware: huawei vr glass 

## Steps to Reproduce

1.
2.
3.

## Current Behavior

controller cannot work.

## Context

  xrStringToPath error.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Which error do you get?

**Comment by dingsing2021** [comment]
xrStringToPath error. 
it seems that v1.5 do not get the huawei controller profile. but v1.4 is ok.
maybe you can check the difference between v1.4 and v.15.

**Comment by svillar** [comment]
> xrStringToPath error. it seems that v1.5 do not get the huawei controller profile. but v1.4 is ok. maybe you can check the difference between v1.4 and v1.5.

3DoF, 6DoF or both?

**Comment by dingsing2021** [comment]
> > xrStringToPath error. it seems that v1.5 do not get the huawei controller profile. but v1.4 is ok. maybe you can check the difference between v1.4 and v1.5.
> 
> 3DoF, 6DoF or both?

3dof only.

**Comment by svillar** [comment]
Also which package are you using? The one from wolvic.com/dl ? The one in the overseas store?

**Comment by dingsing2021** [comment]
> Also which package are you using? The one from wolvic.com/dl ? The one in the overseas store?

[Wolvic-hvr-arm64-world-gecko-generic-release.apk](https://github.com/Igalia/wolvic/releases/download/v1.5/Wolvic-hvr-arm64-world-gecko-generic-release.apk)
97.4 MB
2 weeks ago

**Comment by svillar** [comment]
Hmm I've just tried that package and everything looks normal.

https://github.com/Igalia/wolvic/assets/1826122/b5c779e8-f9a5-4512-8ed4-38f5508d53fd

Are you trying in different hardware other than the Huawei glasses? Because controllers won't be shown if the device is different. For example what does `adb shell getprop ro.product.vendor.model` this command outputs?

**Comment by svillar** [comment]
> Are you trying in different hardware other than the Huawei glasses? Because controllers won't be shown if the device is different. For example what does this command `adb shell getprop ro.product.vendor.model` output in the console?

Hmm I think I've just found the reason. We're using a Huawei Mate 40 for testing which reports `kirin9000` as vendor model. However the Huawei glasses are ment to be used with different phones so the filtering we're doing is not correct. I'll upload  a patch for that.

**Comment by dingsing2021** [comment]
> Hmm I've just tried that package and everything looks normal.
> 
>  output.mp4 
> Are you trying in different hardware other than the Huawei glasses? Because controllers won't be shown if the device is different. For example what does this command `adb shell getprop ro.product.vendor.model` output in the console?

hi svillar, this bug happend in 3dof mode. i think  you should try the 3dof controller.

**Comment by dingsing2021** [comment]
wolvic1.4 3dof mode， /interaction_profiles/huawei/controller , it is correct.
wolvic1.5 3dof mode，it runs in  /interaction_profiles/khr/simple_controller，_it is not correct profile for huawei vr glass._

so why it happpend in wolvic1.5 , here is some log for reference.

- here is the log of v1.4

10-07 16:16:30.720 17447       17626 I HxrFunctions: [@SDK][HxrFunctions.cpp:hxr_xrEnumerateViewConfigurationViews](434): In hxr_xrEnumerateViewConfigurationViews
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](179): In getSystem by ID
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](184): In getSystem by ID 1
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](186): In getSystem by ID 1_1
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](188): In getSystem by ID 1_2
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](193): In getSystem by ID 2
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](199): In getSystem by ID 3
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](202): In getSystem by ID 4
10-07 16:16:30.720 17447       17626 I VRB     : OpenXR Available color formats: 1
10-07 16:16:30.720 17447       17626 E VRB     : OpenXR systemName: Haliday: G3HMD by Huawei
10-07 16:16:30.720 17447       17626 E HxrInstance: [@SDK][HxrInstance.cpp:hxrSuggestInteractionProfileBindings](299): non-supported profile /interaction_profiles/khr/simple_controller
10-07 16:16:30.720 17447       17626 E VRB     : openxr xrSuggestInteractionProfileBindings error with '/interaction_profiles/khr/simple_controller': XR_ERROR_PATH_UNSUPPORTED
10-07 16:16:30.720 17447       17626 I HxrInstance: [@SDK][HxrInstance.cpp:hxrSuggestInteractionProfileBindings](303): Current attached profile: /interaction_profiles/huawei/controller
10-07 16:16:30.720  1663        2714 I HwPCUtils#HwPCManagerService: onDisplayAdded, displayId:27

- here is the log of v1.5

10-07 15:28:36.659  4702        5043 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](193): In getSystem by ID 2
10-07 15:28:36.659  4702        5043 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](199): In getSystem by ID 3
10-07 15:28:36.659  4702        5043 I HxrInstance: [@SDK][HxrInstance.cpp:getSystemByID](202): In getSystem by ID 4
10-07 15:28:36.659  5359        5417 I Ids_AbsOldArchController: environment is master
10-07 15:28:36.659  4702        5043 I VRB     : OpenXR Available color formats: 1
10-07 15:28:36.660  1663        1857 I HwDisplayPolicyEx: initialNavigationSize navBarHeight:122 navBarHeightMin:0 configuration:{1.0 ?mcc?mnc [zh_CN_#Hans] ldltr sw5dp w5dp h5dp 480dpi smll hdr widecg port -touch -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1152, 2376) mAppBounds=Rect(0, 120 - 1152, 2376) mMaxBounds=Rect(0, 0 - 1152, 2376) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0 mPopOverMode=0} suim:1 extflag:8 s.17 fontWeightAdjustment=0}
10-07 15:28:36.660  4702        5043 E VRB     : OpenXR systemName: Haliday: G3HMD by Huawei
10-07 15:28:36.660  1663        1857 I HwDisplayPolicyEx: screen width:16; mIsLandscape:false
10-07 15:28:36.660  4702        5043 E HxrInstance: [@SDK]_[HxrInstance.cpp:hxrSuggestInteractionProfileBindings](299): non-supported profile /interaction_profiles/khr/simple_controller_
_10-07 15:28:36.660  4702        5043 E VRB     : openxr xrSuggestInteractionProfileBindings error with '/interaction_profiles/khr/simple_controller': XR_ERROR_PATH_UNSUPPORTED_
10-07 15:28:36.660  4702        5043 W HxrSession: [@SDK][HxrSession.cpp:hxrAttachSessionActionSets](777): left profile XR_ERROR_PATH_UNSUPPORTED
10-07 15:28:36.660  4702        5043 E VRB     : XrResult failure [XR_ERROR_PATH_UNSUPPORTED] /home/felipe/Igalia/wolvic/wolvic/app/src/openxr/cpp/OpenXRInput.cpp: 61
10-07 15:28:36.660  1663        1857 D WindowManager: initDisplayRoundCorner screenWidth 16 screenHeight 16 mRoundCornerSafeInsets[0]= Rect(1, 1 - 1, 1) mRoundCornerSafeInsets[1]= Rect(1, 1 - 1, 1) mRoundCornerSafeInsets[2]= Rect(1, 1 - 1, 1) mRoundCornerSafeInsets[3]= Rect(1, 1 - 1, 1)
10-07 15:28:36.660  4702        5043 I VRB     : OpenXR XrEventDataSessionStateChanged: state XR_SESSION_STATE_UNKNOWN->XR_SESSION_STATE_IDLE session=0x0 time=0
10-07 15:28:36.660  4702        5043 I VRB     : OpenXR XrEventDataSessionStateChanged: state XR_SESSION_STATE_IDLE->XR_SESSION_STATE_READY session=0x0 time=0
10-07 15:28:36.660  4702        5043 I VRB     : XR_SESSION_STATE_READY
10-07 15:28:36.660  4702        5043 I HxrFunctions: [@SDK][HxrFunctions.cpp:hxr_xrBeginSession](600): In xrBeginSession
10-07 15:28:36.660  4702        5043 I HxrSession: [@SDK][HxrSession.cpp:beginSession](154): In beginSession

**Comment by dingsing2021** [comment]
> Yes likely testing with other model. The supported models are listed here: https://www.vmall.com/product/comdetail/index.html?prdId=10086373799016&sbomCode=3102170004302 ![image](https://user-images.githubusercontent.com/6307430/273633402-2d80bc2f-1bb7-49fa-91ac-bf1040491562.png)
> 
> Let's see if we can get a list.
> 
> @svillar

@ mats, svillar , this is the list of huawei vision glass , not huawei vr glass.
and wolvic do not need consider the phone model, because huwei vr sdk and runtime have do the work, if the phone could not support vr glass, when you connect it to the phone, the vr glass cloud not start.

**Comment by matlu** [comment]
> > Yes likely testing with other model. The supported models are listed here: https://www.vmall.com/product/comdetail/index.html?prdId=10086373799016&sbomCode=3102170004302 ![image](https://user-images.githubusercontent.com/6307430/273633402-2d80bc2f-1bb7-49fa-91ac-bf1040491562.png)
> > Let's see if we can get a list.
> > @svillar
> 
> @ mats, svillar , this is the list of huawei vision glass , not huawei vr glass. and wolvic do not need consider the phone model, because huwei vr sdk and runtime have do the work, if the phone could not support vr glass, when you connect it to the phone, the vr glass cloud not start.

@dingsing2021  You are correct. I searched for Huawei VR Glass but Vmall gave me the Vision Glass :-(
As discussed I suggest we have list of supported decvices added to the FAQ. It was available on the Vmall page but that page is now gone.
But for the Wolvic App I suggest to allow all devices as proposed in: https://github.com/Igalia/wolvic/pull/1056
@svillar

**Comment by matlu** [comment]
Here is the complete list of supported devices (For the FAQ):
https://consumer.huawei.com/cn/support/content/zh-cn00757272/

@svillar
