### ISSUE TITLE
Sync gradle failed

### ISSUE THREAD

**Issue by yanzhefengELEJO** [Igalia/wolvic#1054]
## Configuration

Wolvic version:  1.5
Wolvic build ID: 

Hardware:   windows PC

## Steps to Reproduce

1.download and build the android-components
2.download wolvic and sync

## Current Behavior

FAILURE: Build failed with an exception.

* Where:
Script 'D:\workcode\android-components\substitute-local-ac.gradle' line: 18

* What went wrong:
A problem occurred evaluating script.
> Could not find method repositories() for arguments [substitute_local_ac_4imbzon19trbub9bgwgdlu198$_run_closure1@6e7bf59d] on settings 'wolvic' of type org.gradle.initialization.DefaultSettings.
## Expected Behavior

sync successflully

## Error Logs and Stack Traces

<details open>
Local configuration: loaded user.properties
	userProperties.simultaneousDevProduction=true
	userProperties.useDebugSigningOnRelease=true
Local configuration: loaded local.properties
	localProperties.sdk.dir=C:\Users\Administrator\AppData\Local\Android\Sdk
	localProperties.autoPublish.android-components.dir=../android-components
[local-ac] adjusting project to use locally published android-components modules (0.0.1-+)

FAILURE: Build failed with an exception.

* Where:
Script 'D:\workcode\android-components\substitute-local-ac.gradle' line: 18

* What went wrong:
A problem occurred evaluating script.
> Could not find method repositories() for arguments [substitute_local_ac_4imbzon19trbub9bgwgdlu198$_run_closure1@35a9be43] on settings 'wolvic' of type org.gradle.initialization.DefaultSettings.

```
```

</details>

**Comment by svillar** [comment]
That's a problem in android components. You should report that to Mozilla not Wolvic. In Wolvic we use a prebuilt version of Android Components directly from Maven.
