### ISSUE TITLE
There is no curved window in full-screen video mode

### ISSUE THREAD

**Issue by avamel** [Igalia/wolvic#1055]
## Configuration

Wolvic version: 1.5
Wolvic build ID: 

Hardware: Oculus Quest 2

## Steps to Reproduce

1. Install wolvic
2. Activate curved screen mod in settings
3. Switch to full-screen mode in youtube or other app

## Current Behavior

When switching to full-screen mode, the window stops being curved

## Expected Behavior

In version 1.4.2, there is no such problem, when switching to full-screen mode, the window remains curved

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by avamel** [comment]
That's right, I use wolvic to view 2D video content, it's very convenient for me. And in the curved screen mode, the picture is perceived much better, if there is such an opportunity to return the curved screen for 2D mode, it would be super!

**Comment by GuerreroNinja** [comment]
I am using the app lab version (1.4.2) due to this issue. Is it possible to add an option to keep the screen curved in fullscreen? Thank you.

**Comment by GuerreroNinja** [comment]
Oh I just saw the pull request, than you @HollowMan6 !!

**Comment by HollowMan6** [comment]
Sorry to you guys! Didn't realize that people would actually want to watch full-screen video in curved windows when I worked on the original PR: https://github.com/Igalia/wolvic/pull/969

**Comment by HollowMan6** [comment]
The next version should fix this issue.
