### ISSUE TITLE
华为vrglass

### ISSUE THREAD

**Issue by bizhou78** [Igalia/wolvic#1059]
华为vrglass无法使用，无法显示手柄和输入法，请问是什么原因？

**Comment by bizhou78** [comment]
+8618356566615我的联系方式

**Comment by HollowMan6** [comment]
I have already opened PR #1030 to address the Chinese input issue. I can see there's also an ongoing PR here for the controller at #1056
下一个版本预计会修复这里的所有问题，请耐心等待。
