### ISSUE TITLE
Not installable on Quest 3

### ISSUE THREAD

**Issue by rooneyp** [Igalia/wolvic#1062]
## Configuration

Wolvic version: n/a whatever version appears in the meta quest app store
Wolvic build ID: 

Hardware:  quest 3

## Steps to Reproduce

1. find Wolvic in app store (not app lab ver) 
2. purchase it
3. no option appears for install on quest 3 (quest 2 install is available)

## Context

Other people have raised this, see the reviews of the app in the meta quest store

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by HollowMan6** [comment]
I don't think we have Meta Quest 3 support already, there's a PR trying to add support for Meta Quest 3 controllers: #1045
