### ISSUE TITLE
Enable haptic feedback when controller pointer swipes across widgets/web page

### ISSUE THREAD

**Issue by HollowMan6** [Igalia/wolvic#1067]
**Is your feature request related to a problem? Please describe.**
It can be a great addition to have haptic vibration feedback when we browse the web page, just like what we have in the Meta Quest 2 systems UI and YouTube VR app.

**Describe the solution you'd like**
Create a responsible class in Java so that we can manually call different kinds of vibration customized for each widget.

**Describe alternatives you've considered**
Simply vibrate when the focus changes. (OnGlobalFocusChangeListener and web page focus listener)

**Additional context**
https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrHapticVibration.html

**Comment by svillar** [comment]
Sounds like a good idea indeed
