### ISSUE TITLE
Allow 'Device Name' change in Firefox/Mozzila Sync settings.

### ISSUE THREAD

**Issue by c010rb1indusa** [Igalia/wolvic#1069]
Currently, there is no way to change the 'Device Name' in Firefox/Mozzila Sync settings in the Wolvic Browser like you can do with normal Firefox clients. The device is named 'Wolvic on Oculus Quest' by default with no way to change it. This is especially frustrating with multiple headsets as I can't easily send a link to a specific headset as I don't know which one it is as they are all named 'Wolvic on Oculus Quest'.

**Comment by svillar** [comment]
Ah that's indeed something we need to fix. Not only to differentitate among Meta devices but also to properly refer to the other devices we support. Thanks for reporting!
