### ISSUE TITLE
How to improve sharpness at 0.5 window size

### ISSUE THREAD

**Issue by Risu** [Igalia/wolvic#1078]
## Hardware
Quest3 v57
Wolvic 1.5.1 from MetaStore.

## Steps to Reproduce
Just any page

## Current Behavior
Display DPI option seems not working?

## Expected Behavior
Match my android Kiwi Browser which I am running on Quest3 and it is sharp as fck in comparison to wolvic.

## Possible Solution
Increase pixel density?

## Context
Interface is not sharp too aside  three dots menu popup

## Error Logs and Stack Traces

```
```

Shouldn't "Display DPI" option change anything? I don't see a difference between 1 and 9999.
I tried changing devPixelsPerPx in about:config but no luck.
Perhaps wolvic itself is running in low resolution?

**Comment by YunaDecim** [comment]
I noticed this problem as well. In addition to the steps mentioned by Risu I also tried increasing the default render resolution of the Quest 3, which is usually referenced by apps as their render resolution, sometimes with a multiplier attached. If implemented properly, this makes the app render at different resolutions depending on the device default (usually tailored to its capabilities) but it doesn’t seem to have any affect whatsoever on Wolvic. 

I would like to add that on Quest 3 the resolution of Youtube in fullscreen 4k in fact looks much worse than it does running the same video on my Quest 1. It’s much more pixelated and aliased on Quest 3 somehow, even though it should have almost twice the resolution.

**Comment by HollowMan6** [comment]
Investigated this a little bit, this (sharpness) is something controlled by textureScale that was introduced back in Firefox reality: https://github.com/MozillaReality/FirefoxReality/pull/790

https://github.com/Igalia/wolvic/blob/6298da5c92969c2246603a42bdbc21718e50419b/app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetPlacement.java#L63

Currently, users have no control over that value, so I would suggest we do one of the following ways:
- Make an exception for Meta Quest 3, just like what we do to HVR builds: https://github.com/Igalia/wolvic/blob/6298da5c92969c2246603a42bdbc21718e50419b/app/src/common/shared/com/igalia/wolvic/ui/widgets/WidgetPlacement.java#L35-L37
- It looks like "Display DPI" really changes nothing although it's a runtime setting for Gecko, so I think it can be actually a good way to make that option control the `textureScale`.

I will try to work on the second way, meanwhile, let me know your ideas @svillar @felipeerias
