### ISSUE TITLE
Default values for display density and DPI

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#1088]
Display density and DPI are two values that we pass to the Web engine and which determine how the website is laid out and rendered.

By default, we set the density to 1.0 and the DPI to 96. In a [test page](https://people.igalia.com/femorandeira/viewport/) it looks like this:

![pico scale dpi 1 100 viewport](https://github.com/Igalia/wolvic/assets/1412060/954f5edf-01a3-4aec-a146-54a73c053a2e)

If we increase both values in sync (e.g. density 2, DPI 192) the result looks much clearer because now the engine is rendering a larger and more detailed texture:

![pico scale dpi 2 200 viewport](https://github.com/Igalia/wolvic/assets/1412060/ec67ec65-5a69-4b54-b919-629528fc6923)

If we modify one of these values while keeping the other constant, we change the space available for the page's layout (e.g. density 1.5, DPI 192):

![pico scale dpi 15 200 viewport](https://github.com/Igalia/wolvic/assets/1412060/efb99409-ab1a-4768-b574-3e0e62b7b6f9)

This issue will track our research on these two values. The goal is to find good defaults for each device that balance clarity and performance.

**Comment by felipeerias** [comment]
Will be fixed by https://github.com/Igalia/wolvic/pull/1105

**Comment by HollowMan6** [comment]
Let's close this as #1108 has already been merged
