### ISSUE TITLE
Allow users to use the Zoom to change the size of the rendered web content

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1093]
**Is your feature request related to a problem? Please describe.**
Sometimes a website shows a lot of text using a font size difficult to read. 

**Describe the solution you'd like**
It'd be useful to have a zoom functionality to change the size of the rendered web content.

**Describe alternatives you've considered**
A workaround could be to change the window distance.

**Additional context**
This issue has been filled through the feedback form

> A zoom function would be helpful

**Comment by HollowMan6** [comment]
> It'd be useful to have a zoom functionality to change the size of the rendered web content.

We can of course change that using `Display density` in the Display option of the settings, but that would require a restart of Wolvic to make the change take effect.

In any case, once we have completed the migration to Chromium, we will be able to include zoom buttons in the UI. It's already in the future UI evolution plan. https://github.com/Igalia/wolvic/wiki/Future-UI-evolution#52--proposal-zoom-buttons

> A workaround could be to change the window distance.

PR #734

**Comment by svillar** [comment]
I think this is just a dup of #938 ?

**Comment by javifernandez** [comment]
> I think this is just a dup of #938 ?

Not sure, I thought #938 was more about the window distance, more than zooming the web content,
