### ISSUE TITLE
need a way to add bookmark/URLs in the phone/pc browsers to wolvic

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#1098]
**Is your feature request related to a problem? Please describe.**
it is hard to type the URL in vr mode, so it need a simple way to add URLs in wolvic.

**Describe the solution you'd like**
option1: user account shared with other browsers, like chrome,  edge broswers, uc browers and so on.
option2:  wolvic can run in the phone, add simple 2d view page @ system settings  , and the users can login,  add the bookmarks/URLs in the phone. type in URLs and copy/paste easy.

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
You can setup a Firefox Sync account and then use "Send tab to device" in your desktop Firefox browser. Have you tried that?

**Comment by dingsing2021** [comment]
> You can setup a Firefox Sync account and then use "Send tab to device" in your desktop Firefox browser. Have you tried that?
ok ， i will try it.
and i find that here is no mobile firefox browser in huawei app gallery.

**Comment by svillar** [comment]
> > You can setup a Firefox Sync account and then use "Send tab to device" in your desktop Firefox browser. Have you tried that?
> > ok ， i will try it.
> > and i find that here is no mobile firefox browser in huawei app gallery.

maybe, but in any case you don't need to have it in the phone, just use a laptop/pc

**Comment by svillar** [comment]
@dingsing2021 have you tried Firefox Sync ?

**Comment by dingsing2021** [comment]
> @dingsing2021 have you tried Firefox Sync ?

yes，i have try it, the bookmark can be sync.
but i have found some bugs or requirements：
1，firefox in macOS，cannot sync.
2，the visit history of cann't be sync.

and  "Send tab to device"  is a good feature, but i have found the wolvic should be restart. maybe it is a bug?
and if i select more than one tab to send, it seems failed.

**Comment by svillar** [comment]
Firefox sync not working on macOS is not a Wolvic's issue but Mozilla's. Regarding the need to restart I'll file a bug for that specifically.
