### ISSUE TITLE
Voice Search is not working on Wolvic 0.9.5 #31

### ISSUE THREAD

**Issue by lzhangcs** [Igalia/wolvic#114]
![image](https://user-images.githubusercontent.com/63130594/167040959-ea0e4c2b-8c15-496b-b13e-5639f96a5e89.png)

All the permissions have been granted to Wolvic app:

![image](https://user-images.githubusercontent.com/63130594/167041015-c89ca6c2-76bc-41e3-b94f-6b1296fce5fa.png)

**Comment by svillar** [comment]
This was fixed some time ago in https://github.com/Igalia/wolvic/pull/93 and https://github.com/Igalia/wolvic/pull/94
