### ISSUE TITLE
wolvic-chromium make failed

### ISSUE THREAD

**Issue by weller0** [Igalia/wolvic#1149]
I found in the wolvic source code that the chromium can be used, but how can we compile chromium_aar? Also, I am https://github.com/igalia/wolvic-chromium Compilation method not found in the project. Apply https://github.com/igalia/wolvic-chromium/blob/wolvic_experimental/docs/android_build_instructions.md This compilation method also cannot compile successfully. Apply https://github.com/chromium/chromium/blob/main/docs/android_build_instructions.md document compilation https://github.com/chromium/chromium the project was successful.

Can you provide a compilation method for chromium_aar?

![image](https://github.com/Igalia/wolvic/assets/25904865/33ea0f1f-edc6-4597-8988-b5a9f5832889)

**Comment by weller0** [comment]
Can you release a compiled document first？

**Comment by svillar** [comment]
The chromium_aar property is just the location to the .aar files containing the chromium code. We'll add some documentation as soon as we have time for that

**Comment by weller0** [comment]
Okay, could you please complete the document as soon as possible so that we can quickly complete the technical pre research

**Comment by weller0** [comment]
Can you provide a document about Chromium_aar?

**Comment by yuripourre** [comment]
@weller0 You can find the documentation here: https://github.com/Igalia/wolvic/blob/main/CHROMIUM.md#build-wolvic

You must add to your local.properties:
```sh
chromium_aar=/your/folder/chromium/src
```

**Comment by weller0** [comment]
> @weller0 You can find the documentation here: https://github.com/Igalia/wolvic/blob/main/CHROMIUM.md#build-wolvic
> 
> You must add to your local.properties:
> 
> ```shell
> chromium_aar=/your/folder/chromium/src
> ```

Finally, the documentation has been released. The wolvic aar documentation was not compiled before. Thanks.
