### ISSUE TITLE
When you enter a complete URL such as https:webxr.events in the Address column, you will go directly to Google Search instead of directly to the website,

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#116]
## Configuration

Wolvic version: 
https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/demos/Wolvic-hvr-arm64-release_6Dof_4_28_2022.apk

Wolvic build ID: 
https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/demos/Wolvic-hvr-arm64-release_6Dof_4_28_2022.apk

Hardware:  华为VR Glass 6dof @ SDK 77 verison

## Steps to Reproduce

1.enter a complete URL such as https:webxr.events in the Address column, click go

## Current Behavior

you will go directly to Google Search instead of directly to the website, which will be very inconvenient in regions where Google Search is unavailable (such as China).

## Expected Behavior

When the user enters the correct website,  the browser should go directly to the website.
Or, depending on the region, choose the available search engine to search, such as China, most of which uses Baidu.
Or let the user configure the search engine to be used by default.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
This was already fixed in 0.9.5. 

Wolvic selects the browser engine depending on your location. For China Baidu should be automatically selected. Apart from that you could customize the search engine you want to use in the settings dialog.
