### ISSUE TITLE
Wovic plays intranet videos from PC

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#1161]
## Configuration

Wolvic version: 
Wolvic build ID: 1.5.2

Hardware: huawei vr glass

## Steps to Reproduce

1.
2.
3.

## Expected Behavior

is there a way to play LAN videos from PC？  Samba？

## Possible Solution

find a way ，the pc install EMBY server，and wolvic can play the videos on the PC intranet.
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by dingsing2021** [comment]
maybe wolvic can make a guide for the users.

**Comment by svillar** [comment]
Wolvic can play videos as long as they have a valid URL as any other browser. Wolvic is not a file browser though so it does not implement any handling of samba protocol. The system could however mount the remote share locally and then allow wolvic to read files via `file://` urls.
