### ISSUE TITLE
wolvic support to play 360 view & Horizontal Panoramic View pictures which is photoed by the customers

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#1162]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
the customers take 360 view & Horizontal Panoramic View pictures by the phones or other devices , and they can to watch it on the vr glass. 

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
Wolvic can display panoramic photos, not sure what cases are you talking about? Any website in particular that is not working?

**Comment by dingsing2021** [comment]
> Wolvic can display panoramic photos, not sure what cases are you talking about? Any website in particular that is not working?

The photos are taken by the user and stored in the phone, not uploaded to the Internet.

**Comment by HollowMan6** [comment]
> The photos are taken by the user and stored in the phone, not uploaded to the Internet.

Wolvic is a web browser, not a file browser. How do you open the photos stored in the phone if you didn't download them but stored them manually/from other apps (should have no access privilege)?

**Comment by svillar** [comment]
> > The photos are taken by the user and stored in the phone, not uploaded to the Internet.
> 
> Wolvic is a web browser, not a file browser. How do you open the photos stored in the phone if you didn't download them but stored them manually/from other apps (should have no access privilege to those files)?

Right, the browser should not have access to the files you have on your device (it's a security problem). Opening those files should be done from a file browser.

**Comment by dingsing2021** [comment]
> > > The photos are taken by the user and stored in the phone, not uploaded to the Internet.
> > 
> > 
> > Wolvic is a web browser, not a file browser. How do you open the photos stored in the phone if you didn't download them but stored them manually/from other apps (should have no access privilege to those files)?
> 
> Right, the browser should not have access to the files you have on your device (it's a security problem). Opening those files should be done from a file browser.

ok,got it.
