### ISSUE TITLE
Disabling 360 background

### ISSUE THREAD

**Issue by laurenweinstein1** [Igalia/wolvic#1166]
New to the browser. Very nice work. I've searched around a bit but so far can't find a way to change the 360 background image. To avoid distractions, just having it be black would be best in some cases. Is there a mechanism for controlling this that I missed? Thanks!

**Comment by HollowMan6** [comment]
Hi! Thank you for using Wolvic! You can configure the 360 background in the `Environment` tab of the settings. You may find the video below useful:

https://github.com/Igalia/wolvic/assets/43995067/18124d90-0096-4f28-9f61-47f8c33f6613

**Comment by laurenweinstein1** [comment]
Perfect. Thanks!
