### ISSUE TITLE
Issues entering VR Mode

### ISSUE THREAD

**Issue by johnmanagexr** [Igalia/wolvic#1172]
## Configuration

Wolvic version: 244
Wolvic build ID: fb118459 (AC 116.30)

Hardware: Quest 2

## Steps to Reproduce
1. Launch https://courses.certify-ed.com/content/electric/vr/sim/index.html?id=386f2e32-8d48-44a9-abf5-db27d9087d1a#CityLevel 
2. Click "Start" on the displayed link
3. Note that there is no option to launch this experience in VR Mode
4. Attempt to move around in the experience 

https://github.com/Igalia/wolvic/assets/99302632/c89de9a3-eb9b-4393-a511-676100e1c47d

## Current Behavior
Unable to move around, and directed to use the "WASD" keys, which I do not have on my headset

## Expected Behavior

Able to enter VR mode and move around in the experience

## Context
We had a customer of ours who uses this WebXR link report that it is compatible with other browsers and can launch in VR mode but not with Wolvic

## Error Logs and Stack Traces

```
```

</details>

**Comment by svillar** [comment]
Many thanks for the report. We'll look into that

**Comment by svillar** [comment]
OK I've just verified that it's another user agent issue, i.e., the WebXR experience is filtering out non-meta browsers. We can add an exception for your site but since you control it, I'd suggest removing that filtering or improving it to include Wolvic. Note that Wolvic's user agent already includes the word `Wolvic`so it should be pretty easy to detect

**Comment by svillar** [comment]
Should be fixed in the next release. Note that if Wolvic is important for your clients please do consider supporting the project via the [OpenCollective](https://opencollective.com/wolvic) or any other collaboration setup with Igalia. Thanks!

**Comment by johnmanagexr** [comment]
Hey @svillar thank you for the quick response!

I would love to set up a way for us to collaborate. We help distribute Wolvic to our customers on an opt in basis, since we find it to be so excellent. I can definitely think of a few things it would be useful for us to collaborate on. 

For one, it would be great if we could understand how to submit PRs like #1174 - it seems like we just need a way to generate the key. Is there any documentation on this?

For other issues, I'll do some digging and see if we can start contributing. If it would be useful for someone from our team to chat with someone from Igalia, I'd love to get something on the books.

**Comment by svillar** [comment]
> Hey @svillar thank you for the quick response!
> 
> I would love to set up a way for us to collaborate. We help distribute Wolvic to our customers on an opt in basis, since we find it to be so excellent. I can definitely think of a few things it would be useful for us to collaborate on.
> 
> For one, it would be great if we could understand how to submit PRs like #1174 - it seems like we just need a way to generate the key. Is there any documentation on this?

Not sure what do you mean with "generate the key". The PR was perfect BTW

> For other issues, I'll do some digging and see if we can start contributing. If it would be useful for someone from our team to chat with someone from Igalia, I'd love to get something on the books.

Just send an email to info@wolvic.com or info@igalia.com and we'd be happy to talk.

**Comment by johnmanagexr** [comment]
@svillar great, thank you!

Regarding "generate the key": 

I see the new JSON key value pair is 

"44908fbb56b0dd5ed7769e601ed3067b38c3ef01638acc8d1e2c4b6d3a5ca3004643a0dc2115a30b193023a034d555ea081082c5dc30ad44181b4af61fe7a38c": "Mozilla/5.0 (Linux; Android 10.1.1; Quest 2) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/17.2.0.9.61 SamsungBrowser/4.0 Chrome/93.0.3163.109 Mobile VR Safari/537.36",

I understand the value is a User Agent, so the User Agent to that particular website is treated the same as the OculusBrowser. However, I don't understand how to go form a URL to the key (ie, how you went from "courses.certify-ed.com/content/electric/vr/sim/index.html?id=386f2e32-8d48-44a9-abf5-db27d9087d1a#CityLevel" to "44908fbb56b0dd5ed7769e601ed3067b38c3ef01638acc8d1e2c4b6d3a5ca3004643a0dc2115a30b193023a034d555ea081082c5dc30ad44181b4af61fe7a38c")

Do you have instructions on how to do this, so we could submit our own PRs for this? 

Thanks!

**Comment by svillar** [comment]
> @svillar great, thank you!
> 
> Regarding "generate the key":
> 
> I see the new JSON key value pair is
> 
> "44908fbb56b0dd5ed7769e601ed3067b38c3ef01638acc8d1e2c4b6d3a5ca3004643a0dc2115a30b193023a034d555ea081082c5dc30ad44181b4af61fe7a38c": "Mozilla/5.0 (Linux; Android 10.1.1; Quest 2) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/17.2.0.9.61 SamsungBrowser/4.0 Chrome/93.0.3163.109 Mobile VR Safari/537.36",
> 
> I understand the value is a User Agent, so the User Agent to that particular website is treated the same as the OculusBrowser. However, I don't understand how to go form a URL to the key (ie, how you went from "courses.certify-ed.com/content/electric/vr/sim/index.html?id=386f2e32-8d48-44a9-abf5-db27d9087d1a#CityLevel" to "44908fbb56b0dd5ed7769e601ed3067b38c3ef01638acc8d1e2c4b6d3a5ca3004643a0dc2115a30b193023a034d555ea081082c5dc30ad44181b4af61fe7a38c")
> 
> Do you have instructions on how to do this, so we could submit our own PRs for this?
> 
> Thanks!

OK I got it now. It's easy, those hashes are generated in the UriOverride.java file. What's more we print those hashes to logcat [here](https://github.com/Igalia/wolvic/blob/main/app/src/common/shared/com/igalia/wolvic/browser/UriOverride.java#L93) so we just basically take the most specific one that makes the site work. With "most specific one" I mean that we do several tests for each domain, for example for "site.example.com" we first check the whole URL then "example.com" and then ".com"
