### ISSUE TITLE
[Chromium] Enable password save/autofill

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1179]
There is no implementation in the Chromium backed for the login save/autofill

**Comment by BattleAxeVR** [comment]
So Wolvic supports Chromium officially now? Is there a README on how to achieve it? Geckoview still has some major flaws I'd rather avoid it.

**Comment by svillar** [comment]
> So Wolvic supports Chromium officially now? Is there a README on how to achieve it? Geckoview still has some major flaws I'd rather avoid it.

We haven't released it yet, it's under development. Nothing secret, everything is in the repo, it's just it isn't ready yet for releasing.

**Comment by BattleAxeVR** [comment]
By "everything" do you mean including some prebuilt chromium .zip files to use? Last time I tried using wolvic / chromium maybe a year ago, I wasted several days trying to do that myself and that's something I'm hoping this repo can fix. 

You can't build chromium (AFAICT) on a Windows workstation, or even WSL, it has to be native Linux.

Every single standalone VR headset uses Chromium for its system browser now, it's 100% ready for VR use I'm sure of it. I will help fix some bugs here if you have a working chromium build I can use.
