### ISSUE TITLE
Controllers disappear during video playback

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#1181]
## Configuration

Wolvic version: 1.5.2

## Steps to Reproduce

1. Visit https://www.ixigua.com/
2. Click on a video.
3. Enter and leave fullscreen mode.
4. Press the play button on the video.

## Current Behavior

The controllers disappear. Any user actions (click, etc.) are ignored.

## Context

This is the most reliable way to trigger the bug, but it might be happening on other websites as well.

**Comment by felipeerias** [comment]
Video:

https://github.com/Igalia/wolvic/assets/1412060/0b733d79-ed1a-4ce5-b816-71d33217e027

**Comment by HollowMan6** [comment]
I guess we can close this since #1198 has been merged.
