### ISSUE TITLE
Autocomplete: blank space requires tapping on the spacebar twice

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1186]
When the latin keyboard autocomplete is active adding a blank space requires typing ywice in the space bar, the first cancels autocompletion and the second actually inserts the character.

I mentioned this in the #1185 review

**Comment by HollowMan6** [comment]
This is actually how most Chinese/Japanese input methods work. I'm not sure if this is the same case for Latin autocomplete as well, but if we want to make exceptions, I guess we need to do some refactoring of the code.

**Comment by HollowMan6** [comment]
Fixed in https://github.com/Igalia/wolvic/pull/1189/commits/654e4949c8444dd5d1617e573000801408c4be5c It's indeed a bug...
