### ISSUE TITLE
Weblate updated: added Ukrainian Language Translation for Wolvic VR Browser

### ISSUE THREAD

**Issue by shynekomaid** [Igalia/wolvic#1191]
### Title:
Add Ukrainian Language Translation for Wolvic VR Browser

### Description:
Dear Wolvic VR Browser Team,

I hope this message finds you well. I have prepared and verified the Ukrainian language translation for Wolvic VR Browser. The translation adheres to the rules of the Ukrainian language and is ready for integration.

Translation Link: [Ukrainian Translation](https://hosted.weblate.org/projects/wolvic/wolvic/uk/)

### Request:
I kindly request your attention to add the Ukrainian translation to the Wolvic VR Browser. The availability of Ukrainian translation is critical, especially given the significant number of Ukrainians who have consciously decided to distance themselves from the Russian language after the Russian terror directed at Ukrainians and the whole world by the criminal state authorities of Russia.

### Importance:
This addition is essential for ensuring a more inclusive and accessible experience for Ukrainian-speaking users. It aligns with the current preferences of a substantial Ukrainian user base, contributing to the global reach of Wolvic VR Browser.

**Thank you for your time and consideration.**

Best regards,
shynekomaid

**Comment by svillar** [comment]
Awesome we'll include it in the next release. Many thanks!!!

**Comment by shynekomaid** [comment]
> Awesome we'll include it in the next release. Many thanks!!!

Thank you for a great browser!

**Comment by juanjosanchez** [comment]
There are a few new strings in weblate that will be used in the upcoming 1.6 version. We would appreciate if you could translate those soon, so that we can include the full translation. Thanks!

**Comment by svillar** [comment]
The language has been merged, so closing this

**Comment by shynekomaid** [comment]
> There are a few new strings in weblate that will be used in the upcoming 1.6 version. We would appreciate if you could translate those soon, so that we can include the full translation. Thanks!

Sorry for the delay, I have updated the translation now.

**Comment by shynekomaid** [comment]
The translation has been updated.
![image](https://github.com/Igalia/wolvic/assets/34548743/fb2c453f-e317-4ad9-966e-4f14824580bc)

**Comment by shynekomaid** [comment]
The translation has been updated.

**Comment by vadykoo** [comment]
@shynekomaid thank you for the translation, you did a great job!

@svillar As I see Ukrainian language is still not available on Meta Quest 3 from the Oculus store in the 1.8.1 version of the Wolvic browser.  Also, is it possible to add a keyboard? How can I help?

![Image](https://github.com/user-attachments/assets/3658ae4b-0609-4ff9-accc-349b042d0441)

**Comment by svillar** [comment]
> [@shynekomaid](https://github.com/shynekomaid) thank you for the translation, you did a great job!
> 
> [@svillar](https://github.com/svillar) As I see Ukrainian language is still not available on Meta Quest 3 from the Oculus store in the 1.8.1 version of the Wolvic browser. Also, is it possible to add a keyboard? How can I help?
> 
> ![Image](https://github.com/user-attachments/assets/3658ae4b-0609-4ff9-accc-349b042d0441)

Hmm maybe we didn't include it in the list of available languages... Right if you check the `l10n.toml` file Ukranian is not included there. It should be a matter of adding the language code to the locales array and that's it. Would you feel like creating a PR? If not we'd do it for the next release

**Comment by shynekomaid** [comment]
@svillar https://github.com/Igalia/wolvic/pull/1813
