### ISSUE TITLE
Issue found on HVR .77 testing version

### ISSUE THREAD

**Issue by lzhangcs** [Igalia/wolvic#120]
For  the test version of HVR .77 : https://drive.google.com/file/d/14UpijyQVqiDZ3qbHVBIC5QBkdxtzMLrE/view?usp=sharing

The following issue has be identified by Igalia team:

There is a huge issue happening on my device. The controllers suddenly disconnect themselves without any explanation. Then the VR world starts to move back until you exit the security zone and then, after that, everything gets stalled and nothing more is rendered. There is no way to recover that situation, you have to unplug the glasses. Most of the times I even have to reboot the device because the glasses do not work any longer.

This started to happen with .76 but became more frequent right now to the point that is seriously affecting my capacity to develop on the device.

Also Igalia team wants to see if they can have the following files:
I ask this because among other things Wolvic requires the following files

* `libxr_loader.so` for both arm64-v8 and armeabi-v7 (we can get these from the apk)
* The openxr includes: `openxr.h`, `openxr_hw.h`, `openxr_platform.h` ...
* The `hvrbridge.jar` file

Thanks

**Comment by svillar** [comment]
I guess this should be reported in the [HVR SDK](https://github.com/hms-ecosystem/OpenXR-SDK/) right? This isn't a wolvic bug at all
