### ISSUE TITLE
Entering Immersive mode crashes the Wolvic Browser 

### ISSUE THREAD

**Issue by sujay-digilens** [Igalia/wolvic#1206]
## Configuration

Wolvic version: 1.5.1
Wolvic build ID: 116.0

Hardware: Digilens ARGO

## Steps to Reproduce

1. Go to the following URL: [https://app.etherealengine.com/location/ar-fashion] or any website which offers XR experience.
2. Enter immersive/VR/XR mode.
3. This will crash the Wolvic browser. 

## Context
I’m trying to build a version of the Wolvic XR Browser integrated with Snapdragon Spaces for our ARGO smart glasses platform. Active Build Variant: SpacesArm64GeckoGenericDebug, Active ABI: arm64-v8a

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Can you please attach a logcat ? Note that Gecko does not support AR features

**Comment by sujay-digilens** [comment]
I have attached the logs in this comment. 

If Gecko does not support AR features, how do I support WebXR (specifically, Immersive-AR mode of WebXR) on our platform?
[logcat.txt](https://github.com/Igalia/wolvic/files/14089789/logcat.txt)

**Comment by sujay-digilens** [comment]
Thanks for the response @svillar . 

1. Is there any documentation on how to implement the WebXR AR modules in Gecko?
2. Do you know how to fix the issue with media codec in the Gecko?

**Comment by svillar** [comment]
> Thanks for the response @svillar .
> 
> 1. Is there any documentation on how to implement the WebXR AR modules in Gecko?

You have the specificacion https://github.com/immersive-web/webxr-ar-module. Then you have to implement it in Gecko. If you haven't touched a Web engine code previously then probably is not a task you could complete easily.

> 2. Do you know how to fix the issue with media codec in the Gecko?

Sorry I don't have enough data to check what's going on. Even with it I don't think we'd have time for that in the following weeks/months as we have higher priority tasks

**Comment by svillar** [comment]
Provided the reporter is trying to use an unsupported feature on an unsupported device I think we should close this. Please reopen if you think this is still relevant for the project.
