### ISSUE TITLE
Adding Wolvic to caniuse.com

### ISSUE THREAD

**Issue by expenses** [Igalia/wolvic#121]
**Is your feature request related to a problem? Please describe.**

It's currently unclear what browser APIs Wolvic currently supports. An entry on https://caniuse.com would help immensely in this regard.

**Describe the solution you'd like*

I recommend making an issue at https://github.com/Fyrd/caniuse/issues to get added to the database.

**Describe alternatives you've considered**

Documentation on a wiki or elsewhere would also help with this issue, but would be less discoverable. As a baseline, it would be good to know what version of Firefox Wolvic was forked from, and what features have been added since then.

**Comment by svillar** [comment]
Seems like a good idea.

**Comment by svillar** [comment]
[Done](https://github.com/Fyrd/caniuse/issues/6275)

**Comment by svillar** [comment]
Handled externally, so let's close this
