### ISSUE TITLE
Automatic VR 360 WebXR Open

### ISSUE THREAD

**Issue by JairoGutierrezBarcina** [Igalia/wolvic#1211]
**Is your feature request related to a problem? Please describe.**
I can't get content to open automatically in VR or web xr version when I open a window in which the content is already prepared to autoplay in 360

**Describe the solution you'd like**
I would need that when you open a web page in which you have content generated by viewers like 3dVista and you have marked it to autoplay in the view with web-rx, it would play without having to press the VR button

**Describe alternatives you've considered**
I have considered that there may be some configuration that allows this, but I have not found a way to configure it.

**Additional context**
We are developing a web platform that plays multimedia content in VR launched remotely and transparently to the user. To do this we need that when they are played they are initially opened with the VR view activated

I have attached a video, I would like the user to not have to tap on the screen to open VR mode:
https://github.com/Igalia/wolvic/assets/108017292/99d32191-02e9-4c0d-a9f6-e8078c98554d

**Comment by HollowMan6** [comment]
We already have opened PRs #1171 for auto-entering VR mode, previously we have #1085. Please let us know your comments on these PRs / if you would like to propose an alternative way, thank you!
