### ISSUE TITLE
remove the leave webxr button from controller.

### ISSUE THREAD

**Issue by ankou29666** [Igalia/wolvic#1213]
Hi

I regularly play in oculus browser a few in-browser games or visit a few sites that makes good use of controller buttons.

However, the B button in wolvic triggers the leave webxr, which is problematic because it overrides the games or sites use of that button, making those games unplayable or sites unbrowsable in wolvic.

And moreover, I just see no point to have a quick access button to leave webXR, I by far prefer go to a menu or click the oculus button then leave webxr explicitly, which is fool proof and doesn't permit accidental leaving webXR.  so could it be possible to disable that feature from wolvic ? at least as an option, or better totally remove that feature that in the end causes more trouble than in helps.

thanks in advance.

**Comment by svillar** [comment]
The B button is used as go back action in Meta platform, so it is something that is not that uncommon.

However I agree with you that it prevents some games from using it. We'd have to replace it by some other action/event, likely the menu button on the left controller

**Comment by ankou29666** [comment]
Hi and thanks for this answer and your understanding.

I never really realized that the B button was used as a go back action, but now you tell this I realize that this is far from being a false statement. Most sites I visit and some games also actually more or less use it as a go back action. But, to be honest, leaving the webxr environment is not really my understanding of the go back action.

once again, thank you for your answer and your understanding

**Comment by svillar** [comment]
> Hi and thanks for this answer and your understanding.
> 
> I never really realized that the B button was used as a go back action, but now you tell this I realize that this is far from being a false statement. Most sites I visit and some games also actually more or less use it as a go back action. But, to be honest, leaving the webxr environment is not really my understanding of the go back action.
> 
> once again, thank you for your answer and your understanding

Well we did that for consistency. The back action is used both to go back and to exit immersive experiences/videos.
