### ISSUE TITLE
WebXR links not working - "Enter VR" button doesn't appear

### ISSUE THREAD

**Issue by that3Dguy** [Igalia/wolvic#1216]
## Configuration

 LATEST RELEASE FOR META QUEST

Wolvic version: LATEST RELEASE FOR META QUEST
Wolvic build ID: ?

Hardware: META QUEST 2

## Steps to Reproduce

1. ALL WEBXR LINKS:
2. https://docs.google.com/spreadsheets/d/16qaZpBf3WmAnC_JSD5YjQkNlrskLFAfkjxiwh1a0LVM/edit#gid=0
3. (also attached as xlsx & pdf)

## Current Behavior
 MOST OF THESE LINKS TO VR SIMULATIONS DO NOT SHOW THE "ENTER VR" OPTION LIKE THEY SHOULD... ONLY 3 WORK PROPERLY

## Expected Behavior
 THE "ENTER VR" BUTTON SHOULD APPEAR IN THE LOWER-CENTER

## Possible Solution

 THE SOLUTION COULD POSSIBLY BE FOUND BY YOU ALONE, OR WITH THE HELP OF CERTIFY-ED, THE OWNERS OF THIS CONTENT
 THANK YOU!!!

## Context

 I NEED THESE LINKS TO WORK TO DELIVER LEARNING MATERIAL TO STUDENTS

## Error Logs and Stack Traces

<details open>

```
```

</details>
[Certify-Ed WebXR links - Sheet1.pdf](https://github.com/Igalia/wolvic/files/14114220/Certify-Ed.WebXR.links.-.Sheet1.pdf)
[Certify-Ed WebXR links.xlsx](https://github.com/Igalia/wolvic/files/14114221/Certify-Ed.WebXR.links.xlsx)

**Comment by svillar** [comment]
It is not a Wolvic issue, the problem is that the creator of the courses only enabled them for the Meta browser, so please contact them and ask them not to filter out other browsers as Wolvic.

That said we added a workaround 3 weeks ago in #1174 so they will work in the upcoming 1.6 release.

Thanks for reporting

**Comment by FanEric** [comment]
hi @svillar , I built a spaces version using version 1.7.0, and found the same issue. 
When visiting https://xrdinosaurs.com, "Visit our Dinosaurs in Virtual Reality" is disable. 
As a contrast, the one I built several months ago with version 1.5.1 works fine. 
I believe it's not the version causing this issue, but the build env, but I could not figure out what's in the backend.

**Comment by FanEric** [comment]
After rebuild Gekco, issue is gone

**Comment by svillar** [comment]
> After rebuild Gekco, issue is gone

Yes, you need Gecko v128 with out gecko patches on top to get WebXR working
