### ISSUE TITLE
I couldn't find the six scenes in version 1.5.2 in the source code

### ISSUE THREAD

**Issue by fengpeitian** [Igalia/wolvic#1222]
I couldn't find the six scenes from version 1.5.2 in the source code. I would like to learn how to quickly generate more skyboxes

**Comment by svillar** [comment]
That's because they're in an external repo, see https://github.com/Igalia/wolvic-3D-environments/

**Comment by fengpeitian** [comment]
Thank you, I would like to learn how to create a browser compatible Skybox, which will be of great help to me发自我的 iPhone在 2024年2月2日，18:01，Sergio ***@***.***> 写道：﻿
That's because they're in an external repo, see https://github.com/Igalia/wolvic-3D-environments/

**Comment by svillar** [comment]
You have all the information in the repository, Go to https://github.com/Igalia/wolvic-3D-environments/tree/main, there it explains how to create them and the format they should have
