### ISSUE TITLE
Back button removal on Wolvic 1.6

### ISSUE THREAD

**Issue by schhat** [Igalia/wolvic#1266]
**Is your feature request related to a problem? Please describe.**

Update notes for latest v1.6 update mentions removal of back button input (B & Y) on controller due to rare usage and conflict with WebXR apps. Using the latest Wolvic on my Quest 3, I can confirm that back input on controller no longer works. I initially thought this was a bug with the update until I read thru the update notes. For me, I rarely use WebXR apps and prefer back button on controller for website navigation. I use the back button input frequently and is a convenient shortcut to have on controller. 

**Describe the solution you'd like**
Any possibility of providing an option to enable back button on controller as a settings option? It can be disabled or enabled per user preference.

**Comment by svillar** [comment]
Unfortunately we cannot bring it back as it breaks WebXR experiences which is one of the main purpouses of the browser. You can use the menu button on the left controller instead as you probably do with other apps in the system.

**Comment by goosechaser** [comment]
Another vote to bring it back as an optional setting. It is a pain to browse and exit out of VR videos now, especially when using a single controller as I always do.

**Comment by svillar** [comment]
> Another vote to bring it back as an optional setting. It is a pain to browse and exit out of VR videos now, especially when using a single controller as I always do.

Perhaps one option could be to bring it back but just for the non-immersive browsing mode. It will remain disabled for WebXR experiences

**Comment by schhat** [comment]
> > Another vote to bring it back as an optional setting. It is a pain to browse and exit out of VR videos now, especially when using a single controller as I always do.
> 
> Perhaps one option could be to bring it back but just for the non-immersive browsing mode. It will remain disabled for WebXR experiences

That seems like a good solution.
