### ISSUE TITLE
Autofill in address bar not working correctly

### ISSUE THREAD

**Issue by schhat** [Igalia/wolvic#1267]
## Configuration

Wolvic version:  v1.6
Wolvic build ID:  -

Hardware: Meta Quest 3

## Steps to Reproduce

1. Click on address bar
2. Type R, then E on virtual keyboard. Wolvic autofills with suggested url for reddit.com
3. Press enter on virtual keyboard

## Current Behavior

After pressing enter on virtual keyboard, a google search result shows up for "re"

## Expected Behavior

After pressing enter on virtual keyboard, browser will open up reddit website. This was typical behavior previously.

## Possible Solution

Unclear if this is new intention with latest update. Previous behavior is how, I would think, it should behave, Similar to other browsers.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. This is likely a regression caused by all the word autocomplete work we've done for 1.6. We'll take a look

**Comment by svillar** [comment]
I believe this regressed with AC 121.1. Let's see if future versions fix the issue (I've just verified that the text entry returns the typed text instead of the autocompleted one)
