### ISSUE TITLE
copy/paste in form fields not working

### ISSUE THREAD

**Issue by bkardell** [Igalia/wolvic#129]
## Configuration

Wolvic version:  0.9.6

Hardware: 
Oculus Quest 2

## Steps to Reproduce
Go to a site which requires login (eg hulu.com, netflix.com, docs.google, etc), open your password manager, find the site and copy the password.  Ensure you can paste it into the url bar (so you know it's copied).  You cannot get a paste context menu on the form fields to paste in your password (or other things, as far as I can tell)

## Expected Behavior
The 'right click' behavior should give you the same menu on form fields as it does in the URL bar and allow pasting.

```
```

</details>

**Comment by svillar** [comment]
I've just found the issue. It's actually a regression from the multibackend architecture. I'll upload a PR soon.

**Comment by svillar** [comment]
See PR #137
