### ISSUE TITLE
The Archery Evolution game doesn't load correctly

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1296]
## Configuration

Wolvic version: 1.6.0
Wolvic build ID: 

Hardware: Quest2

## Steps to Reproduce

1. Load the Archery Evolution from the heyvr.io site 
2.
3.

## Current Behavior

The game loads, but as soon as the load is complete, the virtual environment start spinning around the user perspective.

## Expected Behavior

The virtual environment is stable and moves it on user's demand.

**Comment by javifernandez** [comment]
The same game works correctly with Wolvic 1.6 and the Gecko backend.

**Comment by svillar** [comment]
On the other hand there are other weird things, for example it looks to me that if the head rotates the world starts to rotate in the same direction

**Comment by svillar** [comment]
> On the other hand there are other weird things, for example it looks to me that if the head rotates the world starts to rotate in the same direction

This was https://github.com/Igalia/wolvic-chromium/pull/107 BTW
