### ISSUE TITLE
Support for external bluetooh mouse

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1299]
**Is your feature request related to a problem? Please describe.**
Have a desktop like working environment, with external peripherals 

**Describe the solution you'd like**
Support bot external mouse devices for controlling the pointer, via bluetooh.

**Describe alternatives you've considered**

**Additional context**
This is supported by different devices already, as part of their SO, so we would need to add support of the app

**Comment by svillar** [comment]
I don't understand how you could control the pointer using a 2D mouse. A 2D mouse does not provide orientation just x,y coordinates

**Comment by svillar** [comment]
> > I don't understand how you could control the pointer using a 2D mouse. A 2D mouse does not provide orientation just x,y coordinates
> 
> This feature would target just 2D navigation.

what we call 2D navigation is a 3D navigation anyway. As I mentioned we need an orientation for the pointer because the wolvic window and the browser controllers are in a 3D environment

**Comment by svillar** [comment]
In any case dup of #19 ?

**Comment by javifernandez** [comment]
Closed as dup of #19
