### ISSUE TITLE
VisionPro support

### ISSUE THREAD

**Issue by Utopiah** [Igalia/wolvic#1314]
**Is your feature request related to a problem? Please describe.**
Wolvic does not work on the Vision Pro.

**Describe the solution you'd like**
Wolvic should work on the Vision Pro.

**Describe alternatives you've considered**
An iPad browser that support WebXR but I don't think, beside Safari obviously, any exist as they have (or had in Europe maybe?) to rely on WebKit. Note that there was a WPE/WebKit backend test a while ago, could be helpful.

**Additional context**
iOS is now opening up in the EU to other browsers with their own engine. The Vision Pro is a locked down headset as other Apple products. It would be interesting to have a proper alternative that users can customize, a proper open-source solution within that otherwise limited ecosystem.

**Comment by svillar** [comment]
No goal ATM but future will tell

**Comment by svillar** [comment]
I'm closing this because Wolvic runs on AOSP devices, porting it to VisionOS will force us to completely change the architecture so it'd effectively be a different product.
