### ISSUE TITLE
Won't open on quest 3

### ISSUE THREAD

**Issue by JohnDoh337** [Igalia/wolvic#1328]
## Hardware
quest 3

## Steps to Reproduce
launch Wolvic

## Current Behavior
fails to open

## Possible Solution
I have no idea

## Context
I installed Wolvic on new headset, didn't like it and uninstalled.  I decided to try it out again so I reinstalled but now when I try to open it fails to open.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by JohnDoh337** [comment]
I forgot to mention, after several attempts to open Wolvic but failing, I factory reset the headset and reinstalled Wolvic and it still isn't working.

**Comment by svillar** [comment]
> I forgot to mention, after several attempts to open Wolvic but failing, I factory reset the headset and reinstalled Wolvic and it still isn't working.

That's really weird. How are you installing Wolvic? From the store? Sideloading packages?

**Comment by JohnDoh337** [comment]
Hi, I tried both methods.  I ended up sending the headset back for RMA
yesterday for other issues so I'm unable to do any more troubleshooting
until I receive a replacement.  I must have tried to install Wolvic 5 or
six times over the timespan of several days and between several factory
resets being requested by Meta to help diagnose other issues but the only
time I was able to install and open Wolvic was the first time.  All
subsequent install attempts seemed to be fine but the application would
fail to open.

I'm not sure how long it will be for the replacement to arrive but when it
does I'll try again and will let you know.

**Comment by svillar** [comment]
it's likely that this is caused by those other issues you mentioned. There wasn't any other single report about this. Please reopen if you can still reproduce this after getting your unit back

**Comment by JohnDoh337** [comment]
Hello,

I Finally received my replacement (refurbished) headset from Meta. First
thing after setting up the new headset, I installed DeoVR, YouTube VR.
Immersed, and Wolvic and then launched Wolvic.  It opened and the logo
appeared then the virtual environment (city) loaded but then instantly
kicked me out.  I tried relaunching and the Wolvic logo would appear and
then it would crash.  I have no idea whats going on.  This is a "brand new'
headset and the only thing I've done is launch the browser and the app
store.

**Comment by svillar** [comment]
> Hello, I Finally received my replacement (refurbished) headset from Meta. First thing after setting up the new headset, I installed DeoVR, YouTube VR. Immersed, and Wolvic and then launched Wolvic. It opened and the logo appeared then the virtual environment (city) loaded but then instantly kicked me out. I tried relaunching and the Wolvic logo would appear and then it would crash. I have no idea whats going on. This is a "brand new' headset and the only thing I've done is launch the browser and the app store.

OK this is all really weird. I assume you're installing Wolvic from the App Store and not from the App Lab, is that correct?

Then I'd like to know whether you know how to extract a logcat from the device, because that could help identifying your issue.

**Comment by JohnDoh337** [comment]
Hi,

I'm not too familliar with an "App Lab".  I believe I installed from the
Meta App Store.  I also remember on the old headset trying to sideload it
via Sidequest but maybe I hadn't and it was just an idea.

If you can direct me on how to extract the logcat I would give it a try.
As soon as I finish work I'll try to figure it out if I dont hear back from
you.

I might reset the headset again and try only installing Wolvic just to see
what happens but I'm sure I had tried that with the old headset

Thanks for your help.

**Comment by JohnDoh337** [comment]
Hello again,

So I've seem to have made some progress.  I factory reset and only
installed Wolvic directly from the Meta App store like I've done in the
past and the problem continues.  Launching Wolvic instantly crashes after
the logo appears, so nothing new there BUT,  I made a second Meta account
and logged into the headset and installed Wolvic and it WORKED.  No instant
crash, so there's got to be something wrong with my meta account???.  I
have no idea but as for now I'm just going to use the second account.

As you might be aware, the apps that have been installed per user are saved
in the library, so even if the headset is factory reset, it will still show
all past apps and whatnot.  If there was a way to delete all history of the
app being installed, then maybe that would fix it.... again, I have no idea.

If you still would like that logcat or whatever just let me know and I'll
try and get that for you

**Comment by Chris-360x180** [comment]
Hello,
re-installed latest Wolvic from the Meta store. Cannot open it. Merssage: "App konnte nicht geöffnet werden". 
Hmm, it once worked on a fresh Quest 3 a month ago.

**Comment by svillar** [comment]
> Hello, re-installed latest Wolvic from the Meta store. Cannot open it. Merssage: "App konnte nicht geöffnet werden". Hmm, it once worked on a fresh Quest 3 a month ago.

Wow that's pretty bad. Do you know how to get a logcat from the device? That would help a lot debugging the issue

**Comment by Chris-360x180** [comment]
The automatic update of Wolvic that took place in the background fixed that problem. Thank you!
