### ISSUE TITLE
Android Studio: Cannot build selected target ABI: arm64-v8a,armeabi-v7a,armeabi, supported ABIs are: x86_64

### ISSUE THREAD

**Issue by luketurnerdev** [Igalia/wolvic#1343]
Hi all, I am wanting to make my own APK of this project for local use only, with the exit button disabled (I am building an art project app in WebXR, and I need users not to be able to accidentally tap exit). I found the method that calls the exit button menu, and have commented it out. I now want to build the APK for my Quest 3, but I run into the above error (Cannot build selected target ABI: arm64-v8a,armeabi-v7a,armeabi, supported ABIs are: x86_64).

I tried: 

Adding  `PROP_APP_ABI=armeabi-v7a:x86` to gradle.properties. No change.

Editing the Build Variants window: x86_64 is not available when clicking the active ABI:

![image](https://github.com/Igalia/wolvic/assets/47762545/92c3b44a-44b2-48f1-a64b-cfef59958361)

Sorry I'm very new to Android dev, and some help making this APK would be much appreciated!

## Configuration

Wolvic version: 1.6.0
Wolvic build ID: b64e81e8

Hardware: Quest 3

## Steps to Reproduce

1. Clone project and open in Android Studio
2. Connect Quest 3 Headset
3. Select Run (Profile is using Native debug only, otherwise standard Android app config).
4. Encounter above error.

```
```

</details>

**Comment by svillar** [comment]
You are using the wrong build variant. You have to select an oculusArm64 build variant not the AOSP one.

**Comment by luketurnerdev** [comment]
Hi @svillar, thanks for the quick reply - when running with the oculus gecko generic debug (as well as a few others I have tried), I get this error:

1. `ninja: error: '../../../../../third_party/ovr_mobile/VrApi/Libs/Android/arm64-v8a/Release/libvrapi.so', needed by '../../../../build/intermediates/cxx/Debug/3s5d3314/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it`
2. 
![image](https://github.com/Igalia/wolvic/assets/47762545/372b2376-0bac-4617-b0d4-09a95b45f94c).

I am using gradle version 8.2, which appears to be the same as in the project. Any assistance would be appreciated!

**Comment by svillar** [comment]
That's because you don't have the deprecated ovr-mobile sdk under third_parties. You should download it and place it in third_parties/ovr_mobile. In any case we are no longer using it for Oculus. We're using OpenXR for all the supported platforms now. Check the docs to configure the openxr build for oculus/meta
