### ISSUE TITLE
Video Player 3D Options

### ISSUE THREAD

**Issue by ByeyB** [Igalia/wolvic#136]
**Is your feature request related to a problem? Please describe.**

Not a problem, per se, but when playing 2D formatted videos, there is still an option for displaying them in a 3D format (among other formats like 180º, etc.), and when clicked on, it shows each eye 2 different areas of the video, instead of overlaying the entire screen, extrapolating to convert to a 3D format, and generating approximate stereoscopic images from the 2D video.

**Describe the solution you'd like**

Add the ability to automatically convert any/most 2D formatted videos into 3D formatted videos, just like the old 3D TVs were able to do. Possibly also include some additional 3D conversion sub-options that were available on those TVs, like choosing to make the background have more depth, or the foreground pop out more (essentially adjusting relative perspective and the degree of 3Dimensionality).
Somewhat similar to how it is already able to automatically generate analogs of 180 and 360º formats from a standardly formatted video.

**Describe alternatives you've considered**

Not having the option when playing a 2D formatted video, or at least showing 2 side by side identical videos instead of showing different parts of the screen to each eye, which just leads to eye strain.

**Additional context**
VR devices are uniquely well suited for displaying this kind of format, and don't require the elaborate technical engineering that was needed for display on 3D TVs, so it mostly depends on the extent to which different reformatting methods can be employed on this platform.

**Comment by svillar** [comment]
Closing this because converting from 2D videos to 3D is a no-goal for the project. Thanks for reporting anyway!
