### ISSUE TITLE
Wrong orientation of the tray bar in multi-window 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1372]
## Configuration

Wolvic version: 1.7
Wolvic build ID: 

Hardware: Vision Glass

## Steps to Reproduce

1. Click on + to launch a new window
2. Select the new created window on the left side
3.

## Current Behavior

The tray bar is displayed with the wrong orientation

## Expected Behavior

The tray bar is displayed just below the new window and both the Window and Tray must be correctly aligned in the 3D space.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by javifernandez** [comment]
> That's a consecuence of moving the windows further away. What happens if you set the window distance to the minimum?

The effect is different, but still wrong, or not properly aligned with the window.

**Comment by svillar** [comment]
I've tested it and indeed it's poorly orientated
