### ISSUE TITLE
Wrong orientation of the keyboard in multi-window 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1373]
## Configuration

Wolvic version: 1.7
Wolvic build ID: 

Hardware: Vision Glass

## Steps to Reproduce

1. Click on + to launch a new window
2. Select the new created window on the left side
3. Click on the url bar to launch the virtual keyboard

## Current Behavior

The virtual keyboard is displayed with the wrong orientation

## Expected Behavior

The tray bar is displayed just below the new window and both the Window and Tray must be correctly aligned in the 3D space.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Does it happen if you set the window distance to the minimum?
