### ISSUE TITLE
Virtual keyboard dimensions change when trying to move it 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1375]
## Configuration

Wolvic version: 1.7
Wolvic build ID: 

Hardware: 

## Steps to Reproduce

1. Click on the url bar to launch the virtual keyboard 
2. Click on the icon to move the keyboard 
3.

## Current Behavior

The virtual keyboard is displayed with a bigger size. 
Additionally, it's not possible to change its position.

## Expected Behavior

The keyboard's dimensions should not be altered. 
The keyboard can be moved and placed at any location in the 3D space.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Does it happen if you set the window distance to the minimum?

**Comment by javifernandez** [comment]
> Does it happen if you set the window distance to the minimum?

it happens independently of the window distance

**Comment by javifernandez** [comment]
> Does it happen if you set the window distance to the minimum?

Yes, it happens independently of the window distance.
