### ISSUE TITLE
No information about wifi connection

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1376]
## Configuration

Wolvic version: 1.7
Wolvic build ID: 

Hardware: Vision Glass

## Steps to Reproduce

1. Move the pointer to the wifi icon in the Tray bar.
2. 
3.

## Current Behavior

On hovering, it shows '<unknown ssid>" 

## Expected Behavior

On hovering, it shows the actual SSID  

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
That is not a bug, you need to grant location permissions to the app, otherwise it won't have access to the wifi data.
