### ISSUE TITLE
[Chromium Beta] Video Playback Issue

### ISSUE THREAD

**Issue by domexie** [Igalia/wolvic#1386]
## Configuration

Wolvic version: 0.9 (Chromium)
Wolvic build ID: 315

Hardware: Meta Quest 3

## Steps to Reproduce

1. Start watching a video on bilibili.com.(for example https://www.bilibili.com/video/BV1xE421u7fh)
2. Video may fail to load, switch to AVC and refresh the page, then video will play.
![image](https://github.com/Igalia/wolvic/assets/34992856/5b831c4b-1a47-476a-82e3-98061869b8a0)
![image](https://github.com/Igalia/wolvic/assets/34992856/bfbd8377-2b7f-429d-aeb3-58997f1523fb)
3. Bug Reproduced

## Current Behavior

As video plays, Quest 3's screen starts to turn off and on by itself (**it's not just a software black screen, as the backlight also turns off)**.
I've noticed that after a segment of a video buffers, replaying that segment does not cause the screen to turn off and on by itself.
However, when I play a new video or crank the progress bar to a position that hasn't been played before, the aforementioned issue of the screen turning off and on occurs again.

Pressing the Oculus button and opening the system main menu does not prevent the display from continuously restarting. Only exiting Wolvic or stop playing videos works. I suspect that the entire Android display driver is temporarily crashing due to Wolvic.

I conducted an internal screen recording on the Quest 3 while it was experiencing continual screen restarting. Interestingly, in the internal recording, video playback appeared perfectly normal. However, when I used Scrcpy to record the screen image via ADB to my computer, I noticed that the entire field of view would occasionally freeze, with the frequency matching that of the screen restarts.

By the way, the Gecko version works perfectly.

## Expected Behavior

AV1 and HVEC playback should work, and the screen shouldn't blink.

## Error Logs and Stack Traces

<details open>

```
[logcat.txt](https://github.com/Igalia/wolvic/files/15144962/logcat.txt)

```

</details>

**Comment by svillar** [comment]
Thanks for the report. Yeah we are aware of that issue. It does only happen in the Quest3. That's why we suspect is a platform issue. The exactly same APK does not show that behaviour in the Quest2 for example. So it must be something related to the codecs shipped in the Quest3. Some other people reported similar issues in other apps.

**Comment by weller0** [comment]
Hi domexie,

Wolvic Chromium0.9版本要如何打包，能麻烦给一个说明吗？chromium_aar怎么打包导入啊，谢谢

**Comment by svillar** [comment]
Today I found something interesting, everytime a glitch happens we get something like this in the logs
```
NativeWindowResized: 0xb400007af6f5a140 -- 0xb400007a9a622010
```
Checking now...

**Comment by svillar** [comment]
An update on the topic:
- v66 seems to have greatly improved the experience. The flickers are not that visible, they just affect the browser window now and do not switch the displays completely off
- I've also tested v66 with a Quest Pro. Again no issue at all in that device as well. That confirms that there is something wrong in the OS stack of the Quest3

**Comment by svillar** [comment]
We have verified that there was an OS issue. Closing this as the recent Meta updates greatly improved video playback
