### ISSUE TITLE
Memory corruption in xrCreateSession when EXTX_overlay is supported by runtime

### ISSUE THREAD

**Issue by rcelyte** [Igalia/wolvic#1400]
## Configuration

Wolvic version: any since 4a2fac1bed6a6315fa37999e35908a883b6a2233

Hardware: any

## Steps to Reproduce
1. Use a runtime that supports XR_EXTX_overlay (i.e. Monado)
2. Attempt to launch Wolvic
3. Observe errors and immediate crash

## Current Behavior
The extension struct for enabling XR_EXTX_overlay is out of scope when passed to `xrCreateSession()`, resulting in the memory getting clobbered:
https://github.com/Igalia/wolvic/blob/a33d5dede7a2ab1cb6affbb5df21871cd7a9d72d/app/src/openxr/cpp/DeviceDelegateOpenXR.cpp#L1549-L1560

## Expected Behavior
Not crashing on startup

## Possible Solution
Hoist the declaration of `overlayInfo` outside of the `if` statement so it remains in scope

## Error Logs and Stack Traces
<details open>

```
I VRB     : BrowserWorld::InitializeGL
D OXR     : XR_ERROR_GRAPHICS_DEVICE_INVALID: xrCreateSession(createInfo->next) Argument chain does not contain any known graphics bindings
E libc++abi: terminating with uncaught exception of type std::logic_error: XrResult failure [XR_ERROR_GRAPHICS_DEVICE_INVALID]
E libc++abi:     Origin: xrCreateSession(m.instance, &createInfo, &m.session)
```

</details>

**Comment by svillar** [comment]
What a timing :) I precisely spotted that yesterday, it was fixed by #1399
