### ISSUE TITLE
Access to the wolvic-third-parties repo

### ISSUE THREAD

**Issue by yuripourre** [Igalia/wolvic#1413]
**Is your feature request related to a problem? Please describe.**
To build the project you require this repo but it says it is only accessible to Igalia members. So it's not possible to build this project?

**Describe the solution you'd like**
A way to access that repo

**Describe alternatives you've considered**
-

**Additional context**
I am ok in signing an NDA or anything, just wanted to access the repo.

**Comment by svillar** [comment]
You don't need access to the repo, it contains resources that can be downloaded from other sources. The README lists the expected files needed for each platform. You can download them on your own. Basically we need to keep them in a private repo because those SDKs have EULAs
