### ISSUE TITLE
希望支持页面缩放。

### ISSUE THREAD

**Issue by kickbing5421** [Igalia/wolvic#1434]
希望增加页面缩放功能，以方便查看更多的内容。
非常喜欢你们这个浏览器。感谢!

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
Thanks for the kind words. Zoom in page is not possible with Gecko because there is no GeckoView API for that. However it's already implemented in the Chromium backend. You can download it from [here](https://wolvic.com/dl/).
