### ISSUE TITLE
Instructions for building the Chromium AARs and Chromium version of Wolvic?

### ISSUE THREAD

**Issue by jdagdelen** [Igalia/wolvic#1437]
**Is your feature request related to a problem? Please describe.**
I'm interested in building the Chromium backed version of Wolvic from source. Could you please provide some instructions/guidance?

**Describe the solution you'd like**
Short README explaining how to build the required AARs and Wolvic with the chromium backend.

**Comment by svillar** [comment]
I've just uploaded a PR with some docs. Please do take a look and if possible give it a try. I'd include any useful suggestion to the final version of the text.

**Comment by jdagdelen** [comment]
Thanks so much!
