### ISSUE TITLE
Flickering / Screen goes black in v0.9.1

### ISSUE THREAD

**Issue by ststimac** [Igalia/wolvic#1457]
## Configuration

Wolvic version:  Chromium v0.9.1
Wolvic build ID: Could not find anything labeled build ID but code under the version number is 181441406

Hardware:  Meta Quest 3

## Steps to Reproduce

1. Search in URL bar for something. 
2. Accept/Reject Google cookie settings (doesn't make a difference).
3. Try to navigate down the page or click on a link/video. Flickering should start and doesn't stop. More info below.

## Current Behavior

Installed Chromium v0.9.1 and navigated to search in the URL input.

Typed "Titanic VR" which navigated to Google Search. Google's Cookie policy popover appeared and I had to accept all/reject all or customize. 

Selected "Accept All" - popover disappeared as expected. Started to scroll down page. Screen started flickering - lost all vision in immersive mode and could no longer navigate with Wolvic open. The device made a bit of a whirring noise each time the visuals went black. Exited back out of Wolvic. FLickering went away. 

Repeated the same search / experience with Google search in the standard Meta browser. Flickering did not repeat. 

Went back to Wolvic. Repeated same sequence of events. Flickering started again. 

I was also recording this experience in Wolvic and the recording did not capture the flickering and Wolvic was displaying just fine which leads me to think something is interfering with the visuals of the physical device. 

## Expected Behavior

Should be able to navigate through Wolvic without visuals flickering. 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Isn't it a dup of #1386 ?

**Comment by svillar** [comment]
Was there any video in the google search page?

**Comment by ststimac** [comment]
@svillar Confirming there was a video showing a preview loop & that's when the flickering started.
