### ISSUE TITLE
[hvr] Window Drag Malfunction

### ISSUE THREAD

**Issue by anjia1991** [Igalia/wolvic#1463]
Configuration
Wolvic version: v0.9.1 Chromium beta & v1.6.1
Hardware: Huawei VR Glasses Glass CV10; Huawei Mate 20 Pro UD with EMUI 11

Curved screen off: No drag button. 
![ScreenShotVR_20240624074530](https://github.com/Igalia/wolvic/assets/43293176/63b150d9-e897-44f8-a9cc-e36b04363a04)

Curved screen on: Drag button appears, but the window can not move vertically (up and down).

![ScreenShotVR_20240624074543](https://github.com/Igalia/wolvic/assets/43293176/31cbe4ba-ec2b-4d46-b483-f9164176aea6)

**Comment by svillar** [comment]
That is not a bug, we do only allow horizontal movements so far. Vertical adjustments will come later once we revamp the whole UI to allow multiple windows with multiple sizes in free locations
