### ISSUE TITLE
[Quest2] No video loads on motogp.com

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1475]
## Configuration

Wolvic version:  1.6.1
Wolvic build ID: 

Hardware: Quest2

## Steps to Reproduce

1. load the www.motogp.com
2. Play any video
3.

## Current Behavior

The video doesn't load

## Expected Behavior

The video can be played properly

## Context

It works fine in Quest3.
It works fine in Quest2 but with the Chromium backend.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Works in Quest3 but not in Quest2? That's weird

**Comment by svillar** [comment]
Actually works fine in Quest2 for me using 1.6.1. See video

https://github.com/user-attachments/assets/447ee09f-c379-4767-af74-31a962b671f9

**Comment by svillar** [comment]
> Works in Quest3 but not in Quest2? That's weird

Actually works fine for me in Quest2 using 1.6.1. See video

https://github.com/user-attachments/assets/6928e260-fc5f-460e-a2ab-fd374ac0de46
