### ISSUE TITLE
Wolvic is too bright

### ISSUE THREAD

**Issue by yuripourre** [Igalia/wolvic#1479]
## Configuration

Wolvic version: trunk
Wolvic build ID: 

Hardware: Oculus Quest 2

## Steps to Reproduce

1. Open Wolvic
2. Access any page
3. Confirm the page is too bright

## Current Behavior

The web page is too bright, specially comparing to the Oculus Browser

## Expected Behavior

Page has regular brightness

## Possible Solution

Set default brightness to a lower value

## Context

The image below shows Wolvic on top and Oculus browser in the bottom. Wolvic is clearly very bright.

![image showing the same page in oculus browser and Wolvic](https://github.com/user-attachments/assets/a8a8f75e-3a7e-494e-9b70-5063a53a9888)

## Error Logs and Stack Traces

<details open>

```

```

</details>

**Comment by svillar** [comment]
Hmm I doubt there are differences caused by Chromium there. Have you tried the Gecko version?

**Comment by yuripourre** [comment]
> Hmm I doubt there are differences caused by Chromium there. Have you tried the Gecko version?

No, I couldn't build gecko-dev. I can try to download the gecko version and compare.

Is there any way to change the brightness via code? I've found some methods but calling them didn't have any noticable effect.

**Comment by svillar** [comment]
> > Hmm I doubt there are differences caused by Chromium there. Have you tried the Gecko version?
> 
> No, I couldn't build gecko-dev. I can try to download the gecko version and compare.
> 
> Is there any way to change the brightness via code? I've found some methods but calling them didn't have any noticable effect.

We haven't used gecko-dev for a while. You don't actually need to build it as long as you don't use WebXR. For a non-WebXR enabled Wolvic you can just use the version from Maven. It should work out of the box

**Comment by svillar** [comment]
It is not a problem with chromium. Check the following two screenshots, top is with Chromium bottom with Gecko. Both taken in a Pico4. I'll check later with a Meta device, because I know we have specific code for gamma there and that might be the issue
![Screenshot_com igalia wolvic dev_2024 07 30-10 12 53 598_801](https://github.com/user-attachments/assets/7cbe5fdf-ce3c-4b13-949c-b19e7e6b5c9b)
![Screenshot_com igalia wolvic_2024 07 30-09 51 37 890_343](https://github.com/user-attachments/assets/955a0312-30e2-4bf9-ba41-231d2a235fe7)

**Comment by svillar** [comment]
@yuripourre are you sure you didn't change anything in the code? I cannot see any difference in brightness. I'm attaching 3 new pictures, the first two using Wolvic with chromium and gecko and the last one the Meta browser.
![54](https://github.com/user-attachments/assets/1d22a212-2ca2-48dd-b9b8-66897a55f6f6)
![55](https://github.com/user-attachments/assets/92f91961-69fe-4d9a-8c99-552ce7a46b4b)
![57](https://github.com/user-attachments/assets/5a1711bf-be99-4a2f-b936-c1e4b26b80dc)

**Comment by svillar** [comment]
> @svillar thanks for investigating!
> 
> I didn't change anything, I compiled as-is. I will try pull master again e make a new test.
> 
> I can also try in another device, just in case. I will let you know.

Have you verified the issue?

**Comment by yuripourre** [comment]
@svillar Hi, I didn't verify yet. I am sorry, busy weeks.

I will update here when I test it.

**Comment by yuripourre** [comment]
@svillar I am sorry, I've been focusing in other projects, I will close this issue, if I make time to test it and the problem persists I can reopen.

Thank you so much for taking time to investigate it.
