### ISSUE TITLE
cant add custom environments to wolvic?

### ISSUE THREAD

**Issue by lima8** [Igalia/wolvic#148]
## Configuration

Wolvic version: 0.9.6
Wolvic build ID: 627326e8

Hardware: Oculus Quest 2

## Steps to Reproduce
 

1. enable environment override
2. put custom skybox of your choice (for me, its the firefox reality one)
3. see if it is there

## Current Behavior
 i currently cannot see the environment i want in the environments menu in the browser 
 

## Expected Behavior
 i should see the custom environment 

## Context

its irritating that the original tutorial is meant for the Go and that you guys haven't made a newer one for these devices, since i cannot use ADB. i have made a skybox folder and placed the such skybox in there. (this skybox is in .ktx format)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
We're currently very busy preparing the 1.0 release. We'll seriously consider your suggestion after that.

**Comment by svillar** [comment]
So Wolvic does indeed support custom environments as Firefox Reality used to. I've added [some documentation](https://github.com/Igalia/wolvic/wiki/Environments) in our wiki.
