### ISSUE TITLE
Wolwic doesn't download files correctly

### ISSUE THREAD

**Issue by Samu01Tech** [Igalia/wolvic#1485]
## Configuration

Wolvic version: 1.6.1
Wolvic build ID: 181441556

Hardware: Oculus Quest 1

## Steps to Reproduce
1. Visit https://testwolwic.netlify.app/
2. The download popup opens
3. Nothing is downloaded (should be a json file)

## Current Behavior
on the page of that website I build a json file as a Blob and then download it by calling the .click() method on an a tag i create. The popup shows the dwonload but when cliccking the blue button it disappears and in the library of files it doesn't appear

## Expected Behavior
It should download the file like for example downloading a pdf from Google Drive which indeed works

## Possible Solution
Maybe some handling in downloading files or restrictions of any kind

## Context
-

## Error Logs and Stack Traces
I do not have access to developer tools unfortunatly
<details open>

```
```

</details>

**Comment by javifernandez** [comment]
We don't officially support Quest1, so perhaps latest versions of Wolvic have some incompatibility with the path we use to access the device's filesytem to store the downloaded files. 

I tried to reproduce the issue with Wolvic 1.6.1 in the Quest3, but it works fine there; see the attached picture.

![com oculus vrshell-20240724-163242](https://github.com/user-attachments/assets/5dd023ff-dc68-492b-b152-e18b8226ad92)

**Comment by Samu01Tech** [comment]
Yes, that should be the expected behaviour. I wasn't aware of the difference on the filesystem between the Quests. I found a work around for my application, and I understand that you may not look into it too much. Thanks
