### ISSUE TITLE
3x window resets to 2x when going fullscreen

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1486]
## Configuration

Wolvic version: 1.6.1
Wolvic build ID: 

Hardware: Quest3

## Steps to Reproduce

1. Play any video (eg, any YouTube 2D video)
2. Use the menu to resize the window to 3x 
3. Press the fullscreen button in the video

## Current Behavior

The window size is 2x

## Expected Behavior

The window size should remain in 3x

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Honestly I don't know which is the bug here. The fullscreen size is fixed and does not depend on the browsing window size. If you check the Meta browser the behaviour is the same, the window can be resized but the fullscreen size is fixed.

**Comment by svillar** [comment]
> Honestly I don't know which is the bug here. The fullscreen size is fixed and does not depend on the browsing window size. If you check the Meta browser the behaviour is the same, the window can be resized but the fullscreen size is fixed.

Ah I missunderstood the issue, we can indeed change the fullscreen size, maybe we need to add some setting to remember the fullscreen size as well.

**Comment by javifernandez** [comment]
Current Wovic's behavior is based on the fact that the fullscreen size is determined by the media's fullscreen aspec-ratio. If it's different to the one provided by 3x, Wolvic will [rescale]([url](https://github.com/Igalia/wolvic/blob/04131b06656a49f871d85d5855d01c0e123e9562/app/src/common/shared/com/igalia/wolvic/ui/widgets/Windows.java#L1271)) the screen to enforce the one provided by the media content.

**Comment by javifernandez** [comment]
cc @felipeerias @svillar

**Comment by felipeerias** [comment]
If the window is already at the maximum width then IMHO we should just change the height to set the new aspect ratio. 

The resizing logic was cleaned-up by https://github.com/Igalia/wolvic/pull/1337 and maybe this issue comes from `Windows.setFullScreenSize()` not using that logic properly.
