### ISSUE TITLE
Virtual controller position doesn't match actual controller position

### ISSUE THREAD

**Issue by MartinSStewart** [Igalia/wolvic#1498]
## Configuration
Wolvic version: 1.6.1
Wolvic build ID: 181441556

Hardware: Meta Quest 3 with Meta Quest 3 controllers

## Steps to Reproduce
Run Wolvic and look at the controllers with passthrough enabled so you can see where the actual controllers are at the same time.

## Current Behavior
The virtual controllers will be offset from the actual controller positions by about 10 centimeters.
![image](https://github.com/user-attachments/assets/05bafe45-f8ef-45a9-bbaa-e2f9f8359233)

## Expected Behavior
The virtual controller position should match the actual controller position. Note that if you use hand tracking, then the virtual hands do match the position of your actual hands.

```
```

</details>

**Comment by svillar** [comment]
This is a dup of #1451
