### ISSUE TITLE
Remove cookies from the address bar

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1499]
**Is your feature request related to a problem? Please describe.**
The only way of removing cookies is from the Privacy settings dialog

**Describe the solution you'd like**
i miss the option to remove the site`s cookies, from the firefox adressbar

**Describe alternatives you've considered**
It's indeed possible to remove the stored cookies from the Privacy settings dialog.

**Additional context**

**Comment by svillar** [comment]
There are no plans for this, we should not clutter the UI for specific things. Note that no desktop browser does that.

**Comment by javifernandez** [comment]
> There are no plans for this, we should not clutter the UI for specific things. Note that no desktop browser does that.

Not discussing about the plans, but Desktop Firerox indeed provides such feature from its address bar.

**Comment by svillar** [comment]
> > There are no plans for this, we should not clutter the UI for specific things. Note that no desktop browser does that.
> 
> Not discussing about the plans, but Desktop Firerox indeed provides such feature from its address bar, as described in the report.

Ups you're right, excuse my ignorance then
