### ISSUE TITLE
Can't use saved passwords in private mode

### ISSUE THREAD

**Issue by Dr-Battenburg** [Igalia/wolvic#1510]
Apologies if this has already been mentioned, I used the search function but didn't find anything. 

When in private mode it doesn't auto-fill saved passwords into websites. Is there a way I can enable this? Most browsers do this automatically. 

To be clear, I'm talking about passwords that have been saved in the browser while not in private mode.

Thanks.

**Comment by svillar** [comment]
I think this is how desktop browsers behave?

**Comment by Dr-Battenburg** [comment]
> I think this is how desktop browsers behave?

It's not. Not for Chrome or Firefox anyway. The key is that it has to be a login that's been saved while not in private mode.

**Comment by svillar** [comment]
> > I think this is how desktop browsers behave?
> 
> It's not. Not for Chrome or Firefox anyway. The key is that it has to be a login that's been saved while not in private mode.

So the key here is that Firefox does not autofill them in private browsing mode but it allows you to use the saved password if the user clicks on the user/pass entry fields. We'll do the same in Wolvic.

**Comment by Dr-Battenburg** [comment]
Awesome, thank you! 👏

**Comment by Dr-Battenburg** [comment]
Awesome, thank you! 👏

**Comment by svillar** [comment]
Let's keep it open, github will automatically close this once the patch lands

**Comment by Dr-Battenburg** [comment]
No problem, apologies I'm not that familiar with Github etiquette.
