### ISSUE TITLE
Fullscreen video has the wrong size when the window is set to 3x

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1517]
## Configuration

Wolvic version: 1.7
Wolvic build ID: 

Hardware: Oculus Quest 3

## Steps to Reproduce

1.  Load the youtube.com site
2.  Set the window size to 3x
3. Play a video in fullscreen mode
4.

## Current Behavior

The video doesn't fill the whole screen; a white area is being rendered (see the attached picture)

## Expected Behavior

The video should be rendered in fullscreen

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by javifernandez** [comment]
![com oculus vrshell-20240818-170100](https://github.com/user-attachments/assets/2b9ba0eb-f978-4dc6-bb80-7effcad34f6e)

**Comment by felipeerias** [comment]
PR https://github.com/Igalia/wolvic/pull/1519 corrects the calculation for the size of the fullscreen window, although unfortunately it seems that it might not fix this bug.

**Comment by javifernandez** [comment]
> PR #1519 corrects the calculation for the size of the fullscreen window, although unfortunately it seems that it might not fix this bug.

  yes; I don't understand the reason but the bug happens now randomly, but once you hit it, it's happening consistently in subsequent YouTube videos.
