### ISSUE TITLE
WebXR experiences appear rotated 90 degress to the left

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1522]
## Configuration

Wolvic version: 1.7.0
Wolvic build ID: 

Hardware: VisionGlass

## Steps to Reproduce

1. Load a WebXR game or experience (eg, moonrider or dinosaursXR)
2. 
3.

## Current Behavior

The users's view is not centered with the experience's world 

## Expected Behavior

The game or experience world appears rotated 90 degrees to the left, based on the user's view

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Vision Glass only right?

**Comment by javifernandez** [comment]
> Vision Glass only right?

right

**Comment by javifernandez** [comment]
This issue is reproducible in 1.8.0, although now the deviation respect the user's initial position is 180 degrees.  I could reproduce it in XRDinosaurs and Iron Rails (HeyVR game). 

Should re-opeing it or would you rather file a new one ?
