### ISSUE TITLE
V1.7 broken on Pico

### ISSUE THREAD

**Issue by Paddy5150** [Igalia/wolvic#1528]
## Configuration

 

Wolvic version: 1.7.0
Wolvic build ID: pico

Hardware: pico 4

## Steps to Reproduce

1. Update Wolvic to latest version from Pico store
2. Launch wolvic
3. Try to use the controllers - you can't, they're frozen in mud air and don't respond.

## Current Behavior
 controllers not recognised/functioning

 
## Expected Behavior
 controllers should function normally

## Possible Solution
 roll back Pico version in the store or fix the problem and republish v1.7

## Context

 cannot use Wolvic at all on Pico 4

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Paddy5150** [comment]
Hi,

It's the Pico 4 (consumer/games version).

Thanks,

Patrick


________________________________

**Comment by javifernandez** [comment]
I can confirm the issue in Pico4 with SO version 5.11.1.S 

It works as expected in previous version, though.

**Comment by Paddy5150** [comment]
Those who have updated to that OS version cannot roll back (and that includes me).

Are you working on a fix? It would be a shame to tarnish Wolvic's good reputation among Pico users. (They recommended it to me in the first place).

Thank you,

Patrick


________________________________

**Comment by javifernandez** [comment]
Yes, we are working on a fix and will do a release soon. I'm so sorry about the inconveniences this has caused.
