### ISSUE TITLE
Addons (including custom) not working [Chromium]

### ISSUE THREAD

**Issue by SmRzT** [Igalia/wolvic#1543]
## Configuration

Wolvic version: V1.0 Chromium 
Wolvic build ID: 

Hardware: Quest 3

## Steps to Reproduce

1. Going to addons page and enable any add-on will download a Firefox add-on ofc doesn't work.
2. Downloading a chromium add-on like ublock origin from their GitHub and trying to enable it is impossible as "not a supported file type".
3. _continuation of 1:_ After downloading the add-on and clicking details will crash wolvic

 

## Current Behavior
 Not correct addons, no way to get correct addons and crash

## Context

 I don't want ads brev

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Yes, we know about that. It was mentioned in the [first beta release](https://wolvic.com/blog/Chromium_Beta_APKs/) blog post.

That said we should probably disable the addons UI until it is not supported.

**Comment by Julmik647** [comment]
There is Android desktop variant of Chromium that supports extensions, so we could use it:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=AndroidDesktop
