### ISSUE TITLE
Add a Wolvic URL for the private mode start page

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1557]
When private mode is enabled Wolvic displays a custom web page informing the user about what private mode is about. Among other things it contains a link to a page explaining it with some more detail. That [page](https://support.mozilla.org/en-US/kb/private-mode-firefox-reality) is a Mozilla one made for Firefox Reality. We should replace it with something similar in our Wiki and change the `private_browsing_support_url` string accordingly.

**Comment by AbdAlRahmanGad** [comment]
Hi @svillar,
I would like to do this task. Could you tell please how Could I edit the wiki page?

**Comment by svillar** [comment]
> Hi @svillar, I would like to do this task. Could you tell please how Could I edit the wiki page?

Unfortunately there is no way to create a PR for the Wiki contents, we'd have to come up with some CI magic to do that. But if you want to contribute some text, just attach it here and I'd be happy to review and publish it.

**Comment by AbdAlRahmanGad** [comment]
Sorry for the delay!
I've just opened a pull request.
