### ISSUE TITLE
Crash when preeviewing youtube vr video

### ISSUE THREAD

**Issue by vincent456** [Igalia/wolvic#1573]
## Configuration

Wolvic version: dev 1.7
Wolvic build ID: 6f684f35

Hardware:  Meta Quest 3

## Steps to Reproduce

1. Open latest dev build of wolvic
2. Go to youtube.com
3. search something like "vr video meditation" 
4. hover the cursor on the first video

## Current Behavior
performing the steps crash wolvic

## Expected Behavior
I expect the video to play or the preview not even play but when clicking the video it would play the vr video, instead of crashing

## Context
I was investigating the lastes wolvic release bug not having an environment, then I tried building the project myself, the environment was here but playing vr videos don't work and make the app crash

## Error Logs and Stack Traces
I see a segfault in libart so, but android studio only gives me assembly code.

```
```

</details>

**Comment by svillar** [comment]
Hi @vincent456, when you mention "latest dev build" of Wolvic what do you really mean? We don't release dev builds

**Comment by vincent456** [comment]
Hi, by latest dev build I mean that I built from the latest source at the time using android studio (hence what I was talking about when I said that android studio gave me assembly code when debugging the crash

**Comment by svillar** [comment]
> Hi, by latest dev build I mean that I built from the latest source at the time using android studio (hence what I was talking about when I said that android studio gave me assembly code when debugging the crash

OK then it's probably an issue in your build because I'm using Wolvic from upstream and I don't have that crash. Attaching the logcat of the system would help a lot. BTW the environments issue is something that it was already being workaround'ed by using another format. Meta abruptly remove the support for the compressed textures we were using.

**Comment by vincent456** [comment]
So the issues I'm reffering to are already working on fix for later build ? Okay, then I guess I just have to wait and test again in latest release

**Comment by svillar** [comment]
> So the issues I'm reffering to are already working on fix for later build ? Okay, then I guess I just have to wait and test again in latest release

The environments fix was already released. Regarding the crash we haven't seen any issue. We suspect is something that is wrong in your build. Are you building Gecko on your own? Have you applied our patches?

**Comment by vincent456** [comment]
If I may recycle this issue : I'm experiencing issues with openXR videos having sound but not video, and problem with the environment not working, using the latest release version of wolvic gecko flavor (at https://www.wolvic.com/dl/ for meta quest 3)

**Comment by svillar** [comment]
> If I may recycle this issue : I'm experiencing issues with openXR videos having sound but not video, and problem with the environment not working, using the latest release version of wolvic gecko flavor (at https://www.wolvic.com/dl/ for meta quest 3)

Please use the one from the store

**Comment by svillar** [comment]
> > If I may recycle this issue : I'm experiencing issues with openXR videos having sound but not video, and problem with the environment not working, using the latest release version of wolvic gecko flavor (at https://www.wolvic.com/dl/ for meta quest 3)
> 
> Please use the one from the store

Regarding videos with only audio please do create a new PR specifying examples of those videos for us to test

**Comment by vincent456** [comment]
> > If I may recycle this issue : I'm experiencing issues with openXR videos having sound but not video, and problem with the environment not working, using the latest release version of wolvic gecko flavor (at https://www.wolvic.com/dl/ for meta quest 3)
> 
> Please use the one from the store

that's what's ended up working for me. Tyvm.
