### ISSUE TITLE
Doesn't detect controller on quest 3s

### ISSUE THREAD

**Issue by tails101** [Igalia/wolvic#1611]
## Configuration

Wolvic version: current latest version in meta store
Wolvic build ID: 

Hardware: quest 3s

## Steps to Reproduce

1.opening wolvic
2.use controller
3.switfhing to hand tracking with the double tap on controller

## Current Behavior
 detect only hand tracking but fail to detect the controllers.

## Expected Behavior
 it should detect the controllers instead

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by javifernandez** [comment]
Thanks for reporting the issue. 
Unfortunately, Wolvic is not yet supported in the new Quest3S hardware. We tried to prevent the Meta Store to offer it for that device, but it seems it didn't work.

We are working to add Quest3S to the list of supported devices, so hopefully you will be able to use Wolvic there soon.

**Comment by svillar** [comment]
@tails101 one thing that could help a lot to support the Quest3S is the output of the following command (if you have the `adb`command and the device is in developer mode and attached to a computer.

`adb shell getprop ro.product.vendor.model`

I guess the output would be "Quest 3S" or similar.

**Comment by tails101** [comment]
> @tails101 one thing that could help a lot to support the Quest3S is the output of the following command (if you have the `adb`command and the device is in developer mode and attached to a computer.
> 
> `adb shell getprop ro.product.vendor.model`
> 
> I guess the output would be "Quest 3S" or similar.

no it is not in developer mode, Im trying to keep it as close to factory as possible sorry.

**Comment by svillar** [comment]
We wouldn't be able to show the 3D controllers until we don't have that info. In the meantime #1618 would allow users to at least use the controllers (although just the trigger and the menu buttons) while showing generic 3D models.

**Comment by javifernandez** [comment]
> @tails101 one thing that could help a lot to support the Quest3S is the output of the following command (if you have the `adb`command and the device is in developer mode and attached to a computer.
> 
> `adb shell getprop ro.product.vendor.model`
> 
> I guess the output would be "Quest 3S" or similar.

The value returned by the command above is: `Quest 3S`

**Comment by javifernandez** [comment]
> > @tails101 one thing that could help a lot to support the Quest3S is the output of the following command (if you have the `adb`command and the device is in developer mode and attached to a computer.
> > `adb shell getprop ro.product.vendor.model`
> > I guess the output would be "Quest 3S" or similar.
> 
> no it is not in developer mode, Im trying to keep it as close to factory as possible sorry.

Would you be willing to join one of the Wolvic testing channels in the Meta store ?  We've got a fix for this and we could distribute an apk there so you could confirm it works in your device.

**Comment by FlorisMXR** [comment]
Our company also has the first customers that are interested using Wolvic on their Meta Quest 3S devices. Do you have a timeline on when you're expecting to implement full support for these devices? Unfortunately, we can't ask our customers to join the PTC. 

I am looking forward to your response!

**Comment by svillar** [comment]
> Our company also has the first customers that are interested using Wolvic on their Meta Quest 3S devices. Do you have a timeline on when you're expecting to implement full support for these devices? Unfortunately, we can't ask our customers to join the PTC.
> 
> I am looking forward to your response!

Suporting Wolvic's development (by partnering or via the OpenCollective) is the way to accelerate the landing of all those fixes and new features that customers expect. That said we aim to release it as soon as we can.
