### ISSUE TITLE
[Meta] Left menu button not triggering exit action from WebXR

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#1631]
I can only reproduce it with v72 Meta OS. The event is received as it can be seen in the logs, however the exit action is not triggered. When that happens the exit action executed with the left hand does not work either.

**EDIT**: note that it works the first time you exit. Subsequent actions do not exit immersive mode. I've just verified that the back action is properly detected but it is not received on Java side. Apparently there is no JNI error and the JNI invocation succeeds.

**Comment by svillar** [comment]
It looks like somehow the main UI thread stops handling events. We have verified it by setting message logging in the main looper. That's why the code in `runOnUiThread()` is not executed and thus, Wolvic don't exit WebXR session.

It works fine if we call `dispatchKeyEvent()` outside the UI thread, somehow after that the main thread resumes the loop. At this point maybe it's better to wait for following beta releases (as this does not happen on any other device). In case it isn't fixed on the OS side, we would have to implement that workaround.

**Comment by svillar** [comment]
So I did some more research using some perfetto tracing. What I found is that when the button stops working it's basically because the UI thread is blocked as mentioned above. The reason why it's blocked is because it's waiting in a `dequeueBuffer` call. This usually means that we run out of buffers and the process is waiting until there are new ones available. Still not sure why this happens.
![Captura de pantalla de 2024-11-21 14-12-55](https://github.com/user-attachments/assets/8c2fd5d0-6439-4632-8b49-3fce0dc8720b)

**Comment by javifernandez** [comment]
I have updated my Quest2,  so now I've got: 
  -  SO version 72.0.0.505.347
  - Runtime version: 72.0.0.506.346

I've tried the Shooting Balls and Magical Reflections and the issue is not reproducible there; I can exit the WebXR session by using the left-hand gesture.

I also tried a few immersive videos in YouTube and it worked fine as well.

**Comment by svillar** [comment]
Same here. Looks like Met fixed the issue
