### ISSUE TITLE
Latest Wolvic can't be installed on Quest 1

### ISSUE THREAD

**Issue by orest-d** [Igalia/wolvic#1659]
## Configuration

Wolvic version: Can't figure out
Wolvic build ID:  ???

Hardware:  Meta Quest (Quest 1)

## Steps to Reproduce

1. When I try to install Wolvic on Quest 1, it fails.
2.
3.

## Current Behavior

I used to  have working version of Wolvic couple of days ago. Then I tried to update. First it uninstalled the old version.
When pressing on Download, it starts downloading, but it stops in a fraction of a second.
Note that the "Meta Quest" is listed among the supported platforms in the Meta Quest Shop.

## Expected Behavior

I should be possible to instal and use Wolvic on Quest 1.

## Possible Solution

If the Quest 1 is not supported any longer, it would be nice if the old version (which worked) would be possible to instal.

## Context

Well - right now I can't use Wolvic. It is IMHO best app for watching Prime Video. The built in browser does not work on Quest 1. Netflix stopped being supported a while ago. Bigscreen is an option, but it is kind of buggy, often refuses to work.
Of course I used Wolvic for browsing and for VR webapps. Now I lost 50% of my favourite functionality... 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. That said, if the problem is that the download of Wolvic gets stalled/stops then the problem is not on Wolvic side. You might need to ask in Meta Quest forums because looks like an error in the Meta Store.

Please reopen if we haven't understood you correctly and the problem happens when launching Wolvic.

**Comment by theoparis** [comment]
I had the same issue here unfortunately. @orest-d, if you manage to find a solution or receive a response from the meta forums can you link it here

**Comment by Ced-le-pingouin** [comment]
I have the same issue. I guess one year later, no one found a fix ? Is there a good alternative VR browser that still works on the Quest 1 ?

**Comment by Ced-le-pingouin** [comment]
> The last version I was able to get working on my Quest 1 (with all post Zuckerberg acquisition updates blackholed, because ❤️❤️❤️❤️ Facebook), was [1.3.4](https://github.com/Igalia/wolvic/releases/tag/v1.3.4). Obviously this is not secure as a browser because it's massively out of date so it may not be acceptable for your use case, but as long as you only visit trusted locations, it does technically still work.

Thanks for your answer. I'll have to check the version I have, which doesn't work anymore. And actually, like the OP, it's not the app that doesn't work/start, it's the installation that doesn't even work anymore. How do you get the exact 1.3.4 version on your Quest to install ?

**Comment by Rainyan** [comment]
> Thanks for your answer. I'll have to check the version I have, which doesn't work anymore. And actually, like the OP, it's not the app that doesn't work/start, it's the installation that doesn't even work anymore. How do you get the exact 1.3.4 version on your Quest to install ?

I am using the Windows "Desktop App" version of [SideQuest](https://sidequestvr.com/setup-howto) to "side load" the specific APK file to the device. Honestly, I am not too familiar with the technical details of how it all works (and it's been a while), but I remember it being quite straightforward and just following documentation with no trouble.

Essentially just:
* Download the SideQuest app
* Connect the headset to the PC via USB cable
* Use the SideQuest app to "side load" the Wolvic APK file into the headset
* Disconnect the USB from the headset
* Launch the Wolvic app in the headset

If you need more (non Wolvic specific) specific help, then this issue might be somewhat off-topic, but perhaps some active Meta Quest (or SideQuest) sub-reddit or similar community could help you further? I am no expert with Android nor VR, so this is the limit of my knowledge on the topic, but I wish you the best of luck 😆
