### ISSUE TITLE
Quest 3, SW: 71/72, Bluetooth headphones - video(audio) playback issue

### ISSUE THREAD

**Issue by bmalnersic** [Igalia/wolvic#1661]
## Configuration

Wolvic version: Gecko: 1.7.1 / Chromium 1.1
Wolvic build ID: 1012018/b360810

Hardware: Meta Quest 3, SW: v71, v72;  Sony WH-1000XM5

## Steps to Reproduce

1. Connect Bluetooth headphones with Quest 3.
2. Open Wolvic web browser.
3. Browse YouTube and open any video.

## Current Behavior

Observe how video will play very sporadically, looks like 1 FPS. Audio will be clipped to few seconds. If steps are reproduced without Bluetooth headphones (using built-in headphones), video and audio will play normally.

## Expected Behavior

Video along with audio should play normally when viewed via the web browser with Quest 3 used with Bluetooth headphones. This issue did not exist in older versions of the Quest 3 SW.

## Possible Solution

Same issue occurs in native Quest 3 browser (also in other browsers like Opera). The solution  that I found for the native Quest Browser was to **disable _AAudio Output_** via _chrome://flags_. This solution cannot be used with Wolvic  browser. 
Meta will probably fix this issue at some point - it does look to be related to their integration of Android Audio library in the latest version of the Quest SW, where a lot of audio enhancements have been added.
Wolvic could add the option to disable AAudio in the configuration menu.

## Error Logs and Stack Traces

<details open>
No error logs

```
```

</details>

**Comment by svillar** [comment]
So this is indeed a platform issue. We could apply a similar workaround than the one you mentioned but I believe it's a step in the wrong direction, Meta should fix that, adding a workaround would just hide a bug that will emerge in a different way. Thanks for reporting anyway!!!

**Comment by svillar** [comment]
@bmalnersic BTW I'd recommend filing this report in Meta forums. There is even a thread dedicated to v72 PTC, so far they have attended our requests.

**Comment by bmalnersic** [comment]
Agreed, Meta should fix this, will check their threads. Main reason for posting this is to make other users aware, that issue has been identified - no need for factory resets and all that comes along, as I see quite some people suggest to do or do when they stumble on issues like this. Thank you for your comment.

**Comment by svillar** [comment]
> Agreed, Meta should fix this, will check their threads. Main reason for posting this is to make other users aware, that issue has been identified - no need for factory resets and all that comes along, as I see quite some people suggest to do or do when they stumble on issues like this. Thank you for your comment.

BTW I think I have good news. I got a new PTC update overnight in a Quest2, in particular 72.0.0.530.347 with runtime version 72.0.0.531 and both the Meta Browser and Wolvic are able to play YouTube videos successfully when bluetooth headphones are paired (I've tested with an older version of your Sony WH-1000X).

**Comment by bmalnersic** [comment]
Thank you:) - thread on Meta Forum: [Problem watching videos when connected to Bluetooth Audio?](https://communityforums.atmeta.com/t5/Get-Help/Problem-watching-videos-when-connected-to-Bluetooth-Audio/m-p/1263468) First posted ~2024-11-21.

Nice to hear this has been fixed in the latest PTC:)
