### ISSUE TITLE
Consider updating Android Components to newly maintained versions

### ISSUE THREAD

**Issue by jonalmeida** [Igalia/wolvic#17]
Hello!

In Android Components, there are features built for browsers that make it easier to build browsers and offer customization along the way. There have been many changes off late that give support for things like tabs, prompts, history, downloads which might be useful for your browser too. 🙂 

In Reality, these [components were used as well](https://github.com/Igalia/wolvic/blob/9fd07714b64f6e9fafa51f870b5e8d538ebc4686/app/build.gradle#L475-L498) but have not been updated in a while. The wolvic is using version [63](https://github.com/Igalia/wolvic/blob/9fd07714b64f6e9fafa51f870b5e8d538ebc4686/versions.gradle#L30) and Android Components' latest release is on [96](https://github.com/mozilla-mobile/android-components/releases).

You can find the code here: https://github.com/mozilla-mobile/android-components/

Here are a list of browsers that are using them extensively which are good references:
 - https://github.com/mozilla-mobile/reference-browser/
 - https://github.com/mozilla-mobile/fenix
 - https://github.com/mozilla-mobile/focus-android

There are folks available on the Matrix channel as well: https://chat.mozilla.org/#/room/#android-components:mozilla.org

**Comment by jonalmeida** [comment]
Ah, we noticed you have updated to release version of GeckoView which may have problems in the future if the AC versions are not synced.

**Comment by svillar** [comment]
Thanks for the suggestion!

**Comment by felipeerias** [comment]
I have started working on this branch: [felipeerias/updateComponents](https://github.com/Igalia/wolvic/tree/felipeerias/updateComponents)

Among others, the following are updated:

- GeckoView nightly: 100.0.20220308100756
- Android components: 100.0.0
- Mozilla appservices: 91.1.1
- Android Gradle plugin: 4.2.2
- Kotlin: 1.6.0

A good number of changes were needed. The code in that branch compiles and seems to run fine, but more careful testing would be required.

The `browser_search` component has been replaced upstream by [`feature_search`](https://github.com/mozilla-mobile/android-components/tree/main/components/feature/search), which has a different API. I have updated Wolvic's dependencies to the latest version of `browser_search`, but we might have to replace the component eventually.

**Comment by svillar** [comment]
Uhu @felipeerias I didn't know that you were working on this. I landed #313 without knowing that you were working on this.

I also noticed that there is a huge change in browser search component. That was actually my main blocker when I tried to migrate first to the latest AC (105 by that time). Do you have those changes in your branch?

**Comment by jonalmeida** [comment]
@svillar based on your needs you might find the [`SearchMigration.kt`](https://github.com/mozilla-mobile/fenix/blob/2bccb86a9bcaf567841161da4ce381e84ae5a659/app/src/main/java/org/mozilla/fenix/components/search/SearchMigration.kt) in Fenix useful and maybe these two/three other patches as well:
* Migrating to SearchState: https://github.com/mozilla-mobile/fenix/commit/2b759e9d6f326bf20faa4ca6091a2558b90b47f6
* Removing `browser-search` component: https://github.com/mozilla-mobile/fenix/commit/cf4847dc174e2112bf3053b76899d684e1c6832d
* Using the new SearchState in the sample-browser without migration: https://github.com/mozilla-mobile/android-components/commit/73627e8577eb4f0c64649789b010afe1adbe344e

**Comment by svillar** [comment]
> @svillar based on your needs you might find the [`SearchMigration.kt`](https://github.com/mozilla-mobile/fenix/blob/2bccb86a9bcaf567841161da4ce381e84ae5a659/app/src/main/java/org/mozilla/fenix/components/search/SearchMigration.kt) in Fenix useful and maybe these two/three other patches as well:
> 
> * Migrating to SearchState: [mozilla-mobile/fenix@2b759e9](https://github.com/mozilla-mobile/fenix/commit/2b759e9d6f326bf20faa4ca6091a2558b90b47f6)
> * Removing `browser-search` component: [mozilla-mobile/fenix@cf4847d](https://github.com/mozilla-mobile/fenix/commit/cf4847dc174e2112bf3053b76899d684e1c6832d)
> * Using the new SearchState in the sample-browser without migration: [mozilla-mobile/android-components@73627e8](https://github.com/mozilla-mobile/android-components/commit/73627e8577eb4f0c64649789b010afe1adbe344e)

Thank you very much @jonalmeida, that really helps a lot. I tried going directly from v63 to v107 but the amount of work to migrate the search was way too big for the available time I have, so thanks for the pointers!

**Comment by svillar** [comment]
As stated, we have already landed #313 so let's close this. Will face the search migration later.
