### ISSUE TITLE
Fragmented subtitles in 3D side-by-side movie

### ISSUE THREAD

**Issue by WENDI-YUAN** [Igalia/wolvic#171]
问题1.电影片源是左右显示模式的，而字幕居中显示，然后在VR模式下，字幕明显割裂无法观看。
2.浏览器没法移动，我想躺着看，但是浏览器没有跟随眼睛移动的方式。
3.VR模式没有上下显示的模式，上下显示的电影片源无法使用。

**Comment by svillar** [comment]
Mind using english for the reports? Also please use one issue for each problem you detect

**Comment by WENDI-YUAN** [comment]
Question 1：a 3D movie in the side by side format，when subtitles are centered，and then in VR mode，the subtitles are obviously fragmented and cannot be viewed.
Question 2：VR mode has no up and down display mode, and the movie source displayed up and down cannot be used.
Suggestions: THE Browser cannot be moved.I want to lie down and watch, but the browser doesn't follow the way the eyes move.

**Comment by svillar** [comment]
Regarding question 2 I think that you want the same as #159

I'll then change the scope of this issue to question 1. If you don't mind I'll rename the title.

**Comment by svillar** [comment]
@WENDI-YUAN do you have an example of movie where that happens? This will help us debugging the issue

**Comment by WENDI-YUAN** [comment]
My personal theater is http://dickyuan.tpddns.cn:8888 , account AAA, password 111. The example cited is Rita: Battle angel. In the first picture, the subtitle of example1 is in the middle, with zhch3 (ASS) subtitle, and the subtitle is displayed in the middle. But from wolvic's point of view, the subtitles are misplaced.
If you switch to zhch3d (ASS) subtitles, the subtitles will be displayed at the left and right ends. In this way, the subtitles will be displayed normally when using wolvic. This subtitle is processed by code. Add {\pos (97272) \fscx50} after the subtitle. But this is only about format movies can be used, up and down format requires other settings. I hope wolvic can judge the format of VR video and automatically modify subtitles to adapt








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月25日(星期一) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Igalia/wolvic] Fragmented subtitles in 3D side-by-side movie (Issue #171)



@WENDI-YUAN do you have an example of movie where that happens? This will help us debugging the issue

**Comment by WENDI-YUAN** [comment]
My personal theater is http://dickyuan.tpddns.cn:8888 , account AAA, password 111. The example cited is Rita: Battle angel. In the first picture, the subtitle of example1 is in the middle, with zhch3 (ASS) subtitle, and the subtitle is displayed in the middle. But from wolvic's point of view, the subtitles are misplaced.
If you switch to zhch3d (ASS) subtitles, the subtitles will be displayed at the left and right ends. In this way, the subtitles will be displayed normally when using wolvic. This subtitle is processed by code. Add {\pos (97272) \fscx50} after the subtitle. But this is only about format movies can be used, up and down format requires other settings. I hope wolvic can judge the format of VR video and automatically modify subtitles to adapt


------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月25日(星期一) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Igalia/wolvic] Fragmented subtitles in 3D side-by-side movie (Issue #171)


@WENDI-YUAN do you have an example of movie where that happens? This will help us debugging the issue

**Comment by HollowMan6** [comment]
> Question 1：a 3D movie in the side by side format，when subtitles are centered，and then in VR mode，the subtitles are obviously fragmented and cannot be viewed.

Unfortunately, this should be solved by the video provider, they should be able to turn off the subtitles or simply have separate subtitles for each eye. We just simply do the projection here and we can't distinguish subtitles and videos on our side.

Question 2：VR mode has no up and down display mode, and the movie source displayed up and down cannot be used.

PR #1008 should fix this.

Suggestions: THE Browser cannot be moved. I want to lie down and watch, but the browser doesn't follow the way the eyes move.

Same as #927
