### ISSUE TITLE
Use (or give option to) higher screen refresh rate on Oculus Quest

### ISSUE THREAD

**Issue by revanmj** [Igalia/wolvic#18]
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 9fd0771

Hardware: Oculus Quest 2

## Steps to Reproduce
1. Open dominantly bright webpage (like google.com) in Wolvic

## Current Behavior
You can notice subtle flickering on white background due to low screen refresh rate

## Expected Behavior
Wolvic uses (or at least gives an option to) higher (at least 90 Hz) screen refresh rate like other Quest apps

## Context
Due to mentioned subtle flickering on bright backgrounds, eyes are getting irritated quite quickly

<details open>

```
```

</details>

**Comment by svillar** [comment]
Refresh rate has been upgraded to 90Hz. Let us know if that improves your experience after the fix is released.

**Comment by revanmj** [comment]
Confirmed that version 0.9.4 from Oculus Store doesn't that annoying flicker anymore. Sorry for being so late, but you didn't add new release here or announced it on Twitter so only noticed it's there today :)
