### ISSUE TITLE
third-party SDK not found

### ISSUE THREAD

**Issue by businezcc** [Igalia/wolvic#184]
remote: Repository not found.
fatal: repository 'https://github.com/Igalia/wolvic-third-parties.git/' not found

**Comment by svillar** [comment]
Note that the third parties repo is private because it includes software under EULA's, so we cannot make it public. You can download the SDK's on your own though.

**Comment by businezcc** [comment]
> Note that the third parties repo is private because it includes software under EULA's, so we cannot make it public. You can download the SDK's on your own though.

ok.
