### ISSUE TITLE
which openxrsdk do I need to put into third_party?

### ISSUE THREAD

**Issue by anyuanzhao** [Igalia/wolvic#192]
## Configuration

Wolvic version: 33
Wolvic build ID: unknown

Hardware: Oculus

## Steps to Reproduce

1.add "openxr=true" to user.properties
2.Download oculus open xr mobile sdk from
https://developer.oculus.com/downloads/package/oculus-openxr-mobile-sdk/40.0
3.put oculus open xr mobile sdk into third party
4.run

## Current Behavior

In file included from /Users/one/AndroidStudioProjects/VRBrowser/wolvic/app/src/openxr/cpp/OpenXRExtensions.cpp:1:
/Users/one/AndroidStudioProjects/VRBrowser/wolvic/app/src/openxr/cpp/OpenXRExtensions.h:5:10: fatal error: 'openxr/openxr.h' file not found

## Expected Behavior

no error

## Possible Solution

what openxr sdk do I need to put into the third_party?

## Error Logs an
<img width="1413" alt="企业微信截图_fedd24dc-3fdd-4ca2-86ab-67c67da5987e" src="https://user-images.githubusercontent.com/7939199/177973510-a3e7db46-9b76-4a16-b5b4-1237e0b4796c.png">
d Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
For building the OpenXR backend with a Meta/Oculus device check [these lines](https://github.com/Igalia/wolvic/blob/main/app/CMakeLists.txt#L94). The OpenXR-SDK is distributed by Khronos, we just add there the `openxr_oculus.h` file coming from the oculus mobile SDK package.

For the`ovr_openxr_mobile_sdk` it used to be available for download from [here](https://developer.oculus.com/downloads/package/oculus-openxr-mobile-sdk/)
