### ISSUE TITLE
isSessionSupported('immersive-vr') got false in molvic but true in FirefoxReality

### ISSUE THREAD

**Issue by lcgao** [Igalia/wolvic#196]
Hi, anyone has solution for this issue?

1. Use the latest code and build with flavor noapiArm64Debug.
2. Access website: https://immersive-web.github.io/webxr-samples/.
3. Show ❌ - VR support not detected.
4. But it works on Firefox Reality browser.

Thanks!

**Comment by svillar** [comment]
Noapi flavour precisely means that no XR api is used, and thus no XR session could be created.

**Comment by lcgao** [comment]
Thanks but Firefox Reality also build with noapi flavour and created VR session. So what should I do if I want to have the same effect as Firefox Reality in Wolvic? Thank you in advance.

**Comment by lcgao** [comment]
Hi, I went through all the commits and found commit #70 and #145 make this situation.

I would like to know how to create a XR session with my own XR device in a new flavor, please advice.
Thanks a lot!

**Comment by svillar** [comment]
> Hi, I went through all the commits and found commit #70 and #145 make this situation.
> 
> I would like to know how to create a XR session with my own XR device in a new flavor, please advice. Thanks a lot!

That's because in #70 we changed the protocol to talk to Gecko. See https://github.com/Igalia/wolvic/issues/210#issuecomment-1193691252

**Comment by lcgao** [comment]
OK, so I just need to use the [branch wolvic_release](https://github.com/Igalia/gecko-dev/tree/wolvic_release) instead, right?

**Comment by svillar** [comment]
> OK, so I just need to use the [branch wolvic_release](https://github.com/Igalia/gecko-dev/tree/wolvic_release) instead, right?

Correct. We're currently evaluating reverting #70 because in the end it didn't work as expected and seems to be causing major disruptions for potential new contributors.

**Comment by lcgao** [comment]
OK, this is great! Actually I did the revert-operation in our own Wolvic for this issue.
Anyway it would be better if Wolvic official do a fix (integrate new Gecko or revert #70), expecting it.

Thanks.

**Comment by lcgao** [comment]
Please also check commit [`24902f1`](https://github.com/Igalia/wolvic/pull/145/commits/24902f1d36489ea85d780987acd3ecd3316856ea).
I think `VRBrowser::InitializeJava()` should be called before `VRBrowser::RegisterExternalContext()` because the latter is a function that calls Java method. Otherwise, `ValidateStaticMethodID()` may return `false` with error message "`JNI::%s failed. Java not initialized.`"

**Comment by lcgao** [comment]
But actually this does cause `isSessionSupported('immersive-vr')` returning `false`.

**Comment by svillar** [comment]
> But actually this does cause `isSessionSupported('immersive-vr')` returning `false`.

That should not be the cause. That call only returns false (using Gecko) whenever the XR library is not able to list the available devices.

**Comment by DavidChen528** [comment]
@lcgao ，Hi，Have you solved this problem yet?
