### ISSUE TITLE
No common place for discussions? Slack, etc.?

### ISSUE THREAD

**Issue by kylebakerio** [Igalia/wolvic#198]
This projects needs a slack/discord/whatever. Any strong opinions on this?

Reason I'm looking right now: the FAQ mentions that we shouldn't be using browser string sniffing for VR. A-Frame enables this kind of thing by default, and I've certainly used it. I would love to use a better option, and likely suggest pull requesting a feature to aid in that to A-Frame.

But what should we use? What is the best practice here? How can I detect Wolvic?

(Again, though, probably better to have a forum/chat than to discuss that here I imagine.)

**Comment by msub2** [comment]
Agreed, FxR had a Matrix chat and it's a bit unfortunate that there isn't a currently active one to continue discussion.

As for detecting Wolvic (and honestly in general) feature detection is the way to go, while the UA string can be used for extra confirmation. I recently needed to do differentiation between multiple browser types for metrics purposes and here's what I wrote for Wolvic:
```js
const checkWolvicBrowser = () => {
  // While Wolvic is still shipping with a GeckoView backend, this feature detect should hold true.
  // Once versions with different backends start showing up in the wild, this will need revisiting.
  const featureDetect = (window.mozInnerScreenX != null && window.speechSynthesis == null);
  const uaCheck = navigator.userAgent.includes('Mobile VR') && !navigator.userAgent.includes('OculusBrowser');
  const confidence = featureDetect && uaCheck ? 'Full' : 
                     featureDetect || uaCheck ? 'Partial' : 
                     'None';
  return { match: confidence !== 'None', confidence: confidence }
}
```

As you can see my first thought was to look for a moz-prefixed variable somewhere on the window to narrow it down to Gecko, then to differentiate between desktop I check if speechSynthesis is available, which is not true for Wolvic.

**Comment by kylebakerio** [comment]
Hm. I said "how can I detect Wolvic?" but what I really was pondering was, "what's the ideal alternative to detecting the oculus browser, in a generic way that includes wolvic, and other potential future browsers?"

My aim is to potentially come up with a proposal for A-Frame, to include a built-in detection to offer alongside the existing oculus browser detection.

**Comment by kylebakerio** [comment]
> Agreed, FxR had a Matrix chat and it's a bit unfortunate that there isn't a currently active one to continue discussion.

What are the next steps to getting this up? I lean towards discord myself these days. A-Frame uses slack. I've seen projects use gitter. I haven't heard of matrix in a while, but they exist too.

Most important is somewhere you'll be, just don't want to clog up issues with discussions I guess.

**Comment by msub2** [comment]
Another reason I suggested Matrix is because Igalia seems to already have a server for it set up at https://chat.igalia.com/, though I suspect it's for internal use only since I'm not allowed to see the room list. Any thoughts on this @svillar?
