### ISSUE TITLE
Cannot log into Firefox Accounts, login page stalls

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#205]
## Configuration

Wolvic version: 1.0
Wolvic build ID: d7b28877 (ac 63.0.0)
Hardware: Any

## Steps to Reproduce
1. Open Wolvic and Settings, select Sign Into Account 
2. The browser window is redirected to FxA login page

## Current Behavior
The FxA login page stalls loading and it is not possible to log into FxA.

## Expected Behavior
The FxA login page open and one can successfully log Wolvic into Accounts.

## Additional info
There is a URL query parameter that causes the page to load forever: `context=oauth_webchannel_v1`. Removing this parameter allows page to load and the login page is shown. However, after logging in, Wolvic doesn't connect to Accounts, so synch'ing doesn't work.

This is a regression, so the API must have changed recently. Since the FxA service is provided by a Mozilla Android component, we probably need to track this is down in gecko-dev.

**Comment by Kiki-Kona** [comment]
Same issue

**Comment by elima** [comment]
This has been (temporarily) fixed and released in 1.0.1.

We added an UA override for the relevant FxA domain and the page loads normally again.
