### ISSUE TITLE
Not possible to upload files

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#208]
It is not possible to select and upload files using Wolvic. This limits the functionality of many different websites.

In mobile phones, this can be implemented with a simple `Intent` that opens a file picker in a separate activity.

However, in VR we can not take the user out of the immersive environment, so fixing this issue would probably involve creating a custom UI within Wolvic to select the files.

**Comment by svillar** [comment]
To be likely fixed by #361

**Comment by felipeerias** [comment]
An initial implementation of file uploads is being worked on at [PR #361](https://github.com/Igalia/wolvic/pull/361).

When the user clicks on the `"Browse…`" button we display a dialog to pick between the files that have been previously downloaded by Wolvic.

We support selecting and uploading multiple files at the same time ([`multiple`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#multiple)).

We also support restricting the accepted file types ([`accept`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept)).

Finally, the list displayed in the file selection dialog now includes a small thumbnail for each file in the list, which makes it much easier to find the item that you want.
