### ISSUE TITLE
isSessionSupported('immersive-vr') is false for oculusvrArm64WorldDebug using either openxr or oculus sdk

### ISSUE THREAD

**Issue by nkozakis-csu** [Igalia/wolvic#210]
## Configuration

Wolvic version: 1.0
Version Code: 41

Hardware: Oculus Quest 2

## Steps to Reproduce
I'm trying to build oculusvrArm64WorldDebug for arm64-v8a with webxr working but can't figure out what's going wrong.
- main branch
- versions.gecko_view_nightly = "96.0.20211126093927"
- all third_party sdks present (ovr_moble, ovr_openxr_mobile_sdk, OVRPlatformSdk)
- webxr fails for both user.properties settings openxr=true and openxr=false

## Current Behavior
- No VR devices are found by webxr on sample apps found on https://immersive-web.github.io/webxr-samples/
- device capability flags appear to be correct when debugging with position, orientation, present, stageParameters, inline, immersiveVR, and ImmersiveAR set.
- from my debugging and logging I believe externalvr context is registering **before** gecko runtime starts up

## Expected Behavior
Webxr samples should be working like they do with the Igalia apk hosted [here](https://github.com/Igalia/wolvic/releases/download/v1.0/Wolvic-oculusvrStore-arm64-world-release.apk) 

## Possible Solution
- wrong branch?
- I noticed the igalia apk download is an oculusvrStore build, would that make a difference?
- building igalia/gecko-dev and using dependencySubstitutions rather than gradle gecko
- I have tried setting fx_config dom.vr.enabled=true but that didn't fix it.

## Error Logs and Stack Traces
`I/GeckoRuntime: Adding debug configuration from: /data/user/0/com.igalia.wolvic/files/fxr_config.yaml
D/GeckoDebugConfig: Adding prefs from debug config: {dom.vr.enabled=false, dom.gamepad.extensions.enabled=true, dom.vr.external.enable=true, dom.vr.webxr.enabled=true, webgl.enable-draft-extensions=true, webgl.msaa-force=true, dom.webcomponents.customelements.enabled=true, javascript.options.ion=true, media.webspeech.synth.enabled=false}`

```
```

</details>

**Comment by nkozakis-csu** [comment]
I'll try substituting gecko for igalia/gecko_dev wolvic_release as suggested in this issue https://github.com/Igalia/wolvic/issues/73

**Comment by svillar** [comment]
That's because we changed the protocol to talk to Gecko. You should use this branch instead https://github.com/Igalia/gecko-dev/tree/wolvic_release. Then in a `local.properties` file you have to specify:
```
dependencySubstitutions.geckoviewTopsrcdir=<SOME_PATH>/gecko-dev
dependencySubstitutions.geckoviewTopobjdir=<SOME_PATH>/gecko-dev/obj-aarch64-unknown-linux-android
```
with your own value for SOME_PATH

**Comment by svillar** [comment]
I'm closing this, please reopen if that does not work for you
