### ISSUE TITLE
Rules for commercial use

### ISSUE THREAD

**Issue by lcgao** [Igalia/wolvic#212]
Hi, I would like to know are there any rules we should follow for commercial use? Thanks.

**Comment by svillar** [comment]
You should refer to the [license](https://github.com/Igalia/wolvic/blob/main/LICENSE)

**Comment by lcgao** [comment]
Thanks.
For the section [3. Responsibilities](https://github.com/Igalia/wolvic/blob/main/LICENSE#L157-L217), does it mean need to make our changes of the source code public and publish it to GitHub or somewhere else?

**Comment by svillar** [comment]
[This](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) should solve your doubts

**Comment by svillar** [comment]
I'm closing this, feel free to reopen in case of doubt although IANAL :smile:

**Comment by lcgao** [comment]
Okay, thanks a lot.
