### ISSUE TITLE
Developer experimental setting to allow .xpi installation

### ISSUE THREAD

**Issue by Utopiah** [Igalia/wolvic#22]
**Is your feature request related to a problem? Please describe.**
Currently only Firefox recommended addons are installable.

**Describe the solution you'd like**
Provide a setting to allow the installation of .xpi directly or after download.

**Describe alternatives you've considered**
Building the browser back with a custom list of recommendations pointing to my own addons with their xpis.

**Comment by svillar** [comment]
Our idea would be to improve the interface so that more addons are available for installing without the burden of having to download and install xpi directly. We're tracking that in issue #58. Hope that would be fine for you.

**Comment by Utopiah** [comment]
I believe that a broader curated list is indeed quite valuable. If there is an easy for me and crazy experimentation that don't require a lengthy approval process then yes, that'd be great. If that prevents entirely from development alternatives (hence the `.xpi`) then I'm worry it will slow down the development of WebXR specific more interesting plugins.

**Comment by svillar** [comment]
> I believe that a broader curated list is indeed quite valuable. If there is an easy for me and crazy experimentation that don't require a lengthy approval process then yes, that'd be great. If that prevents entirely from development alternatives (hence the `.xpi`) then I'm worry it will slow down the development of WebXR specific more interesting plugins.

I agree they're different issues. Let's reopen this, we'll eventually get back to it

**Comment by svillar** [comment]
@Utopiah I think @DevPika work in #391 will be of your interest :smile:

**Comment by Utopiah** [comment]
Thanks indeed can’t be wait to try it!

**Comment by Utopiah** [comment]
Out of curiosity what's the average release cycle time to get this to the store, i.e when can I try that new feature without building and installing it myself but rather "just" installing?

**Comment by svillar** [comment]
> Out of curiosity what's the average release cycle time to get this to the store, i.e when can I try that new feature without building and installing it myself but rather "just" installing?

It's still not set on stone, but our idea is to release this month
