### ISSUE TITLE
Some VR website rotates in the opposite direction in VR mode

### ISSUE THREAD

**Issue by lcgao** [Igalia/wolvic#221]
## Configuration

Wolvic version: main branch - noapi
Wolvic build ID: main branch - noapi

Hardware: 

## Steps to Reproduce

1. Access webset: https://720yun.com/vr/9e426qO6ul6.
2. Click the VR button on the top right button to enter VR mode.
3. Click right-turn and left-turn button on the bottom left of Wolvic native button area.

## Current Behavior

Website content rotates(right-left, up-down) in the opposite direction(left-right, down-up)
## Expected Behavior

Website content rotates(right-left, up-down) in the direction as expected(right-left, up-down).
## Possible Solution

I found the key point is in this commit: https://github.com/Igalia/wolvic/commit/80a501266bbbb9b7f47d99cde14bd69a630730fd#diff-7ed70199d3f1b35b205846662071f83d9e5b8927d5c493d862505da0d6b9d975R11.

**So why set `dom.vr.enabled` to false? And is there any risk if I set it to true again?**
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
`dom.vr.enabled=false` disables the deprecated WebVR spec. We did that because we just want to focus on WebXR and not maintain deprecated APIs

**Comment by lcgao** [comment]
Okay, understood.

**Comment by lcgao** [comment]
So jus for now, is there any risk if I enable WebVR in Wolvic?

**Comment by svillar** [comment]
I don't think there is any risk

**Comment by lcgao** [comment]
Okay, clear. Thank you.
