### ISSUE TITLE
No sound effects playing Moon Rider (https://moonrider.xyz)

### ISSUE THREAD

**Issue by mariospr** [Igalia/wolvic#226]
## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 9baee63c (AC 63.0.0)

Hardware: Meta Quest 2

## Steps to Reproduce

1. Open Wolvic and navigate to https://moonrider.xyz
2. Pick a song and start playing either in punch or classic (sabers) mode

## Current Behavior

The game starts and you can hear the song playing but you can't hear any sound effect when hitting the blocks (e.g. sound of breaking the block), which you can hear when playing the game via the Meta Quest Browser.

## Expected Behavior

It should be possible to hear the sound effects when hitting the blocks when playing this game on Wolvic.

## Context

The game is perfectly playable without this, but having these sound effects make it even more fun and nice.

</details>

**Comment by svillar** [comment]
Thanks for reporting. We are aware of sound issues in some XR experiences. We'll check what's going on.

**Comment by HollowMan6** [comment]
I can see the sound effect when hitting the blocks is actually played in Wolvic main (1.5), but got significantly delayed. Maybe it's related to https://github.com/Igalia/wolvic/issues/86#issuecomment-1730988547 as of https://github.com/Igalia/wolvic/issues/86#issuecomment-1667631642, maybe a Gecko issue as well.
