### ISSUE TITLE
No song playing nor blocks showing up sometimes when playing Moon Rider (https://moonrider.xyz)

### ISSUE THREAD

**Issue by mariospr** [Igalia/wolvic#227]
## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 9baee63c (AC 63.0.0)

Hardware: Meta Quest 2

## Steps to Reproduce

1. Open Wolvic and navigate to https://moonrider.xyz
2. Pick a song and start playing either in punch or classic (sabers) mode

## Current Behavior

When loading certain songs, it sometimes happens that the song never plays and the blocks never show up, despite of seeing the VR user moving forward over the track over which the blocks should show up.

This happens to me with a few songs I tried, for instance "Happy" by Pharrell Williams, which I double-checked works just fine on the Meta Quest Browser.

## Expected Behavior

After picking up a song and loading the game for it, the song should play and the blocks should show up.

</details>

**Comment by mariospr** [comment]
FWIW, I can confirm this works fine now with version 1.1 of Wolvic. Thanks!

**Comment by svillar** [comment]
> FWIW, I can confirm this works fine now with version 1.1 of Wolvic. Thanks!

BTW just to avoid confusions there is no 1.1 release of Wolvic yet. @mariospr is talking about an internal build for a group of testers.
