### ISSUE TITLE
How to add  a fixed widget on FOV

### ISSUE THREAD

**Issue by lcgao** [Igalia/wolvic#231]
Hi, I would like to add a fixed widget(a bit like system UI) on FOV.
- It will always follow my eyes no matter I turn left or right. 
- User can interact with it via the Ray-controller.

Is this possible? Thanks advance!

**Comment by svillar** [comment]
This is more a development question than an enhancement or a bug report. In general to achieve what you want you have to tie the widget to the orientation of the user's head.
