### ISSUE TITLE
Youtube straight up crashing when playing 8K video

### ISSUE THREAD

**Issue by SamuelChih** [Igalia/wolvic#235]
## Configuration

Wolvic version: 1.0.1
Wolvic build ID: 

Hardware: Oculus Quest 2

## Steps to Reproduce

1. Open Wolvic and navigate to [https://www.youtube.com/watch?v=w1ABOYXXGzY](https://www.youtube.com/watch?v=w1ABOYXXGzY)
2. Set the video quality to 8K(2360p) , turn to full screen and plays it.

## Current Behavior

The video plays with only sound and static view in low quality, and crashes after ~30 seconds.

## Expected Behavior

Video plays normally.

## Context

- Tried to turn Hardware UI acceleration off. It makes thing worse, crash the whole browser when playing the video in Fullscreen.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. Does it also crash with lower resolutions? If not it might be the case that we're hitting some memory-wise hardware limit

**Comment by SamuelChih** [comment]
It does not crash in lower resolutions, the memory hardware limit might be the reason.
