### ISSUE TITLE
Pico Neo3 prebuilt APK

### ISSUE THREAD

**Issue by issacclee** [Igalia/wolvic#24]
Hi Guys,
Would you consider provide prebuilt APK that is compatible with Pico devices? Currently there's only Huawei & Quest build in the release page.

**Comment by EremuBirtualak** [comment]
I need that apk file too. THANKS

**Comment by zandercodes** [comment]
Build it yourself

**Comment by betheshooter** [comment]
If you hear anything on this progress please let me know. Thank you

**Comment by zandercodes** [comment]
Hey Guys, i build prebuilds for picovr and oculusvr (meta)
[https://github.com/zandercodes/wolvic-nightly/releases](https://github.com/zandercodes/wolvic-nightly/releases)

**Comment by issacclee** [comment]
@zandercodes It seems like the MSAA option has no effect in webxr scene even if it is set to 4x for this build.
Maybe these old issues from FirefoxReality repo regarding to Pico and MSAA are related?

https://github.com/MozillaReality/FirefoxReality/issues/2953
https://github.com/MozillaReality/FirefoxReality/issues/3293

**Comment by zandercodes** [comment]
> @zandercodes It seems like the MSAA option has no effect in webxr scene even if it is set to 4x for this build. Maybe these old issues from FirefoxReality repo regarding to Pico and MSAA are related?
> 
> [MozillaReality/FirefoxReality#2953](https://github.com/MozillaReality/FirefoxReality/issues/2953
> [MozillaReality/FirefoxReality#3293](https://github.com/MozillaReality/FirefoxReality/issues/3293)

@[issacclee](https://github.com/issacclee) The problem is that the build goes through the old API of the Pico2 SDK. The new SDK goes through OpenXR. But since this is not yet integrated and I myself do not know how this then goes with OpenXR, I could not create a build for the new Pico3.
Is then normal that the bugs of Firefox Reality are still there.

**Comment by betheshooter** [comment]
Thank you!

**Comment by cooolinx** [comment]
Any news?

**Comment by HoboDev** [comment]
Hm... the website says headsets from pico interactive are supported. But the current apk does not launch on the neo 3...

**Comment by svillar** [comment]
> Hm... the website says headsets from pico interactive are supported. But the current apk does not launch on the neo 3...
> So either there need to be an official apk for pico - sort of what 'supported' implied - or the text should be changed to "can be build for..."

Yeah, sorry for the confusion. The code does indeed support building for Pico devices, but we haven't had the time to work on that (it's outdated) and we haven't released any version for Pico yet. So far the only released versions are for Meta Quest and Huawei glasses devices.

**Comment by lubobill1990** [comment]
> Hey Guys, i build prebuilds for picovr and oculusvr (meta) https://github.com/zandercodes/wolvic-nightly/releases

Hi zandercodes,

How did you build the apk for picovr? Where to find any instruction to follow and modify to build wolvic for pico4?

**Comment by willguest** [comment]
@svillar @lubobill1990 I have tried to use the nightly apk on the pico 3, but with no luck. The app did not even start. I would love to hear about any progress, or what pieces are missing to make this happen, or how to properly debug this... the pico is much more accessible than the quest - any idea how to get system logs that might help fix it?

**Comment by zandercodes** [comment]
@lubobill1990 
> How did you build the apk for picovr?

I have built it with the old PicoVR SDK.
Added the SDK to the third_party folder and built it with gradle

> Where to find any instruction to follow and modify to build wolvic for pico4?

The Pico 3 and Pico 4 have a new SDK which makes building difficult. You have to write your own code.
Since I don't own a Pico 3 or 4 myself, I can't implement this.

**Comment by willguest** [comment]
@svillar I really would like to know about the pico 3 apk... 

fyi, i'm a VR dev, programmer and founder of a company that, currently, is 100% on WebXR projects. We love Wolvic, we see the potential and want it to be our no 1 recommendation for all new VR users. I don't want to pressure you into promises, rather I want to find a route to a solution, even perhaps one that involves me contributing in some way.

I could really use a foot-hold here... what are the stumbling blocks? what is standing in the way? where can I look to find answers (please don't say google). I know I can just dive into the code, but as we both know, having a guide is very time-saving.

Pls reply, I want to help
