### ISSUE TITLE
userAgent lost "Mobile VR" on http://localhost:8088/

### ISSUE THREAD

**Issue by mrjoshuaesmith** [Igalia/wolvic#245]
## Configuration

Wolvic version: 46
Wolvic build ID: 2974e751 (ac63.0.0)

Hardware: Meta Quest 2

## Steps to Reproduce

Connect to any web server and observe the userAgent

## Current Behavior

Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0

## Expected Behavior

Mozilla/5.0 (Android 10; Mobile VR; rv:98.0) Gecko/98.0 Firefox/98.0

## Possible Solution

Please re-add "Mobile VR" to the userAgent on the Quest 2

## Context

My website serves a different version of pages to VR headsets. The only reasonable way to do this is by looking at the userAgent. On the Quest 1 headset, the userAgent reported by Wolvic retains the Firefox Reality "Mobile VR". However when we run on a Quest 2, it reports an extremely generic and inaccurate "Linux x86_64". While userAgent sniffing is obviously a deprecated approach where you have the option of doing capability detection (that is, client side), it's still the only option for customizing things server-side. (And even client-side, capability detection is getting harder and harder given increasing "fingerprinting" prevention. There's no way to detect whether someone is on a VR headset without them clicking a button.) Given that using a VR headset on the web is still a new and novel feature for users, it's critical that I be able to customize that experience from the outset, including server-side page generation.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Which website are you referring to? We haven't removed the "Mobile VR" part of the UA, but we unfortunately have to remove it from some specific sites because otherwise nothing works as many sites assume that Meta Browser is the only WebXR capable browser out there.

**Comment by mrjoshuaesmith** [comment]
Oh! This is very helpful. I was testing with a Quest 1 connecting to our live site, but my lead developer was testing with a Quest 2 connecting to localhost. So the difference is *not* that he's on a Quest 2 (I just confirmed it uses the right URL when connecting to the live website). The *actual* issue is that we are getting the generic userAgent when we connect to http://localhost:8088/. What are the chances of getting localhost off the naughty list?

**Comment by mrjoshuaesmith** [comment]
(Note that this userAgent issue is not critical for us now, since we can just change the port we are using to be unusual, and check for that in our code to recognize that we are running this configuration.)

**Comment by svillar** [comment]
> Oh! This is very helpful. I was testing with a Quest 1 connecting to our live site, but my lead developer was testing with a Quest 2 connecting to localhost. So the difference is _not_ that he's on a Quest 2 (I just confirmed it uses the right URL when connecting to the live website). The _actual_ issue is that we are getting the generic userAgent when we connect to http://localhost:8088/. What are the chances of getting localhost off the naughty list?

We don't have localhost in that list so I guess it's just Gecko using the default UA for localhost URIs

**Comment by mrjoshuaesmith** [comment]
Thanks. I'll close the issue since I have a workaround.
