### ISSUE TITLE
How do I launch Wolvic from a java app?

### ISSUE THREAD

**Issue by mrjoshuaesmith** [Igalia/wolvic#246]
**Is your feature request related to a problem? Please describe.**
We have a local web server that we use to host WebXR content. We want the user to start that program, which will in turn launch the Wolvic browser. We can't figure out how to launch Wolvic from a program on the Meta Quest 2.

**Describe the solution you'd like**
We'd like to know the correct way to launch Wolvic. If we do this:
    Intent launchIntent = new Intent( Intent.ACTION_VIEW, Uri.parse("http://localhost:8088/index.html") );
    startActivity(launchIntent);
it launches the Meta browser.
If we do this:
    Intent launchIntent = getPackageManager().getLaunchIntentForPackage("com.igalia.wolvic");
    startActivity(launchIntent);
Nothing happens.

**Describe alternatives you've considered**
We have used the above launchIntent approach successfully to launch Firefox Reality on the HTC Vive Focus 3.

**Additional context**

**Comment by mrjoshuaesmith** [comment]
That works from ADB, but if we try to do it from an app:

    Runtime.getRuntime().exec("am start -n com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity --ez create_new_window true \"http://localhost:8088/index.html\"");

We don't have permission:

    ActivityManager: Permission Denial: startActivityAsUser asks to run as user -2 but is calling from uid u0a81; this requires android.permission.INTERACT_ACROSS_USERS_FULL

I found a StackOverflow answer that says in order to get that we need to sign with the OEM key.
https://stackoverflow.com/a/40927392/531261

Is that for real?

**Comment by philip-lamb** [comment]
On Quest, all apps are sandboxed (so run as different users) and apps cannot setuid (note that INTERACT_ACROSS_USERS_FULL permission is useless on a non-rooted device). There is a half-workaround for apps from the same organization, in that you can use their Platform SDK to make apps part of an execution group.

Until such time as Meta deign to allow other browsers to be designated as the default handler for web URLs, there doesn't appear to be a way forward here. I'd love to be corrected.

**Comment by svillar** [comment]
@mrjoshuaesmith I guess we can close this as it isn't a Wolvic issue at all?
