### ISSUE TITLE
Non store apk for Quest2 included in future releases

### ISSUE THREAD

**Issue by Khiu** [Igalia/wolvic#250]
I would like to sideload the apk to my Quest2, but the store version will show you this error on startup and then quit:
"Wolvic does not have permission to run on this device and will now exit"
See here for more info: https://github.com/MozillaReality/FirefoxReality/issues/1407

Release [0.9.3] has a non store apk and works fine if you sideload it.
Can you include this package type in future releases so it can be sideloaded?

**Comment by svillar** [comment]
Have you tried with the package from https://wolvic.com/dl ?.

**Comment by Khiu** [comment]
That page points to the github release.

**Comment by svillar** [comment]
> I'm not sure if it was clear, but I would like this apk added to the releases:
> ![image](https://user-images.githubusercontent.com/1051349/196430516-d6552987-9054-4028-b755-6eea080a8753.png)

Sure we know. We'll try to include that version in future releases.

**Comment by Khiu** [comment]
Thank you

**Comment by svillar** [comment]
APK available in the [latest release](https://github.com/Igalia/wolvic/releases/tag/v1.2)
