### ISSUE TITLE
Triggering a file input crashes Wolvic

### ISSUE THREAD

**Issue by mrjoshuaesmith** [Igalia/wolvic#253]
## Configuration

Wolvic version: 46
Wolvic build ID: 2974e751 (ac63.0.0)

Hardware: Meta Quest 1

## Steps to Reproduce

1. Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
2. Click the "Choose File" button on the right in the demo

## Current Behavior

Complete browser crash back to "lobby"

## Expected Behavior

The Quest browser prompts for permission to access files, and then shows screenshots I've taken.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
This is fixed in the repo now, expect a fix in the next release
