### ISSUE TITLE
Build hvr error,  'openxr/openxr_reflection.h' file not found

### ISSUE THREAD

**Issue by SiyaoHuang** [Igalia/wolvic#265]
## Configuration

Wolvic version:  main branch, hash 41dc49b9f288a4d07497b0f149620b8d85df65bb
Wolvic build ID: 

Hardware: hvr

## Steps to Reproduce

1.  build variants hvr3dofArm64Chinese
2. build apk
3. get error during externalNativeBuildHvr3dofArm64CnRelease
```
* What went wrong:
Execution failed for task ':app:externalNativeBuildHvr3dofArm64CnRelease'.
> Build command failed.
  Error while executing process F:\Unity\2020.3.22f1c1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C F:\git\wolvic\app\.cxx\cmake\hvr3dofArm64CnRelease\arm64-v8a native-lib}
  ninja: Entering directory `F:\git\wolvic\app\.cxx\cmake\hvr3dofArm64CnRelease\arm64-v8a'
  [1/56] Building CXX object src/main/cpp/vrb/src/CMakeFiles/vrb.dir/BasicShaders.cpp.o
  [2/56] Building CXX object CMakeFiles/native-lib.dir/src/openxr/cpp/OpenXRSwapChain.cpp.o
  FAILED: CMakeFiles/native-lib.dir/src/openxr/cpp/OpenXRSwapChain.cpp.o 
  F:\Unity\2020.3.22f1c1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=F:/Unity/2020.3.22f1c1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=F:/Unity/2020.3.22f1c1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_lib_EXPORTS -I../../../../../third_party/hvr/include -I../../../../../app/src/openxr/cpp -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++14 -fexceptions -frtti -Werror -IF:\git\wolvic\app\src\main\cpp -IF:\git\wolvic\app\src\main\cpp\vrb\include  -DHVR -DOPENXR -IF:\git\wolvic\app\src\openxr\cpp -DXR_USE_PLATFORM_ANDROID -DXR_USE_GRAPHICS_API_OPENGL_ES -O2 -DNDEBUG  -fPIC   -std=gnu++1z -MD -MT CMakeFiles/native-lib.dir/src/openxr/cpp/OpenXRSwapChain.cpp.o -MF CMakeFiles\native-lib.dir\src\openxr\cpp\OpenXRSwapChain.cpp.o.d -o CMakeFiles/native-lib.dir/src/openxr/cpp/OpenXRSwapChain.cpp.o -c ../../../../src/openxr/cpp/OpenXRSwapChain.cpp
  In file included from ../../../../src/openxr/cpp/OpenXRSwapChain.cpp:2:
  ../../../../../app/src/openxr/cpp/OpenXRHelpers.h:8:10: fatal error: 'openxr/openxr_reflection.h' file not found
  #include <openxr/openxr_reflection.h>
```

The hvr openxr sdk provided by huawei does not contain openxr_reflection.h file. [link](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243)

Another issuse is that `import com.huawei.hvr.LibUpdateClient;` does not exisit in `wolvic\app\src\hvr\java\com\igalia\wolvic\PlatformActivity.java:29: `, which could be found in jar file inside hvr demo.

Thank you so much for providing help.

```
```

</details>

PS: What I want is to watch anime while laying on my bed. But the screen is always matching to horizental plane. I cannot recenter it. Is there anything like discord, we can discuss on? I really want to make some contribute. I guess building it is a trail.  HAHAHAH

**Comment by lzhangcs** [comment]
Investigation in progress, here is a new hvr apk. Maybe you can give it a try:
https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/demos/HVR_demo/Second_Signed_HVRSDKServerApp_9_18_22_fix_32_36.apk

**Comment by lzhangcs** [comment]
Got it, will keep you posted with HVR feedback.

**Comment by SiyaoHuang** [comment]
华为vr sdk 服务 3.5.0.78
华为VR 桌面 11.1.0.328
华为VR 12.2.1.301

Do you need `openxr_reflection.h` for building wolvic? What step does I miss?

1. clone wolvic repo
2. sync submodule
3. download huawei vr sdk from [Huawei](https://developer.huawei.com/consumer/cn/doc/development/graphics-Library/openxr-sdk-download-0000001148849243)
4. set build variants hvr3dofArm64Chinese
5. build apk

**Comment by lzhangcs** [comment]
Hi Siyao,

Got feedback from HVR, you only need to do:

.download huawei vr sdk from Huawei<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.huawei.com%2Fconsumer%2Fcn%2Fdoc%2Fdevelopment%2Fgraphics-Library%2Fopenxr-sdk-download-0000001148849243&data=05%7C01%7Clzhang2%40futurewei.com%7C2ea90721a27e49653cbe08da9ab5ada1%7C0fee8ff2a3b240189c753a1d5591fedc%7C1%7C0%7C637992402365981608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HiZq5PswkO1Em%2BMUbQK%2BX2WAtOLcjcpi6K7E2EOADms%3D&reserved=0>
No any other things you need to do so to build.

Best,
Linda

**Comment by SiyaoHuang** [comment]
> Hi Siyao, Got feedback from HVR, you only need to do: .download huawei vr sdk from Huawei<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.huawei.com%2Fconsumer%2Fcn%2Fdoc%2Fdevelopment%2Fgraphics-Library%2Fopenxr-sdk-download-0000001148849243&data=05%7C01%7Clzhang2%40futurewei.com%7C2ea90721a27e49653cbe08da9ab5ada1%7C0fee8ff2a3b240189c753a1d5591fedc%7C1%7C0%7C637992402365981608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HiZq5PswkO1Em%2BMUbQK%2BX2WAtOLcjcpi6K7E2EOADms%3D&reserved=0> No any other things you need to do so to build. Best, Linda From: Siyao Huang ***@***.***> Sent: Monday, September 19, 2022 7:42 PM To: Igalia/wolvic ***@***.***> Cc: Linda Zhang ***@***.***>; Comment ***@***.***> Subject: Re: [Igalia/wolvic] Build hvr error, 'openxr/openxr_reflection.h' file not found (Issue #265) 华为vr sdk 服务 3.5.0.78 华为VR 桌面 11.1.0.328 华为VR 12.2.1.301 Do you need openxr_reflection.h for building wolvic? What step does I miss? 1. clone wolvic repo 2. sync submodule 3. download huawei vr sdk from Huawei<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.huawei.com%2Fconsumer%2Fcn%2Fdoc%2Fdevelopment%2Fgraphics-Library%2Fopenxr-sdk-download-0000001148849243&data=05%7C01%7Clzhang2%40futurewei.com%7Cbf5a58a6ff9349f29d8a08da9ab1a9c7%7C0fee8ff2a3b240189c753a1d5591fedc%7C1%7C0%7C637992385103425473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mwY4UTyvlLHzGuIyeAJdMA0OJbhtyJLAcKowX%2BDHjjI%3D&reserved=0> 4. set build variants hvr3dofArm64Chinese 5. build apk — Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIgalia%2Fwolvic%2Fissues%2F265%23issuecomment-1251767502&data=05%7C01%7Clzhang2%40futurewei.com%7Cbf5a58a6ff9349f29d8a08da9ab1a9c7%7C0fee8ff2a3b240189c753a1d5591fedc%7C1%7C0%7C637992385103425473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zE%2BOMNYimADz65PT43R7W0ERfRMhNDDMzOBCFyLv9Hg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPBUXYTYJTMITPAOWJ7RE4LV7EP6VANCNFSM6AAAAAAQN622P4&data=05%7C01%7Clzhang2%40futurewei.com%7Cbf5a58a6ff9349f29d8a08da9ab1a9c7%7C0fee8ff2a3b240189c753a1d5591fedc%7C1%7C0%7C637992385103425473%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WcKoO6gsTC32vu4%2FrY25UKo73cuOzcDaSwaVxm2l5eY%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.******@***.***>>

So what setep does I missed? After putting this into `third_party\hvr`, I get build error durring ` Task :app:externalNativeBuildHvr3dofArm64CnDebug` 
```
In file included from F:\git\wolvic\app\src\openxr\cpp\OpenXRSwapChain.cpp:2:
F:\git\wolvic\app\src\openxr\cpp\OpenXRHelpers.h:8:10: fatal error: 'openxr/openxr_reflection.h' file not found
```
Is this the repo for building hvr wolvic? Or I have to be member of Igalia to build hvr wolvic?

**Comment by SiyaoHuang** [comment]
Not all build lib and header is inside `hvrsdk-openxr-3.0.0.33.zip`, which is downloaded from the previews link. 

As I mentioned, `import com.huawei.hvr.LibUpdateClient;` could not resolve symbol `hvr`. I found a jar file in demo project, which contains that class.

I don't think this is a reasonable way to find missing jar file. This should be inside `exrternal Library` in gradle file or inside `hvrsdk-openxr-3.0.0.33.zip`.

**Comment by lzhangcs** [comment]
Any log file that can share with us? Thanks

**Comment by lzhangcs** [comment]
Please try to use HVR SDK v79: https://github.com/hms-ecosystem/OpenXR-SDK/blob/main/demos/HVR_demo/Second_Signed_HVRSDKServerApp_v79_4_fix_32_35.apk

**Comment by svillar** [comment]
Closing as this was a HVR SDK issue not Wolvic's

**Comment by SiyaoHuang** [comment]
> 

Could you provide the version for build success? Or where could I find it?
