### ISSUE TITLE
File Explore 

### ISSUE THREAD

**Issue by F4XTS** [Igalia/wolvic#266]
Hello im am requesting for some kinda built in file explorer so you can download .png and other kinda stuff it would really help with future development oh and also a feature to use built in keyboard on quest on wolvic.

**Comment by svillar** [comment]
So, the downloads can be seen in the downloads list accesible via the toolbar.

That said we know that the downloads are not accesible from the outside, that is tracked in bug #207 

If you're OK we can close this and track the work in those other issues. Please reopen if you consider that what you describe is different.
