### ISSUE TITLE
https://sprayspace.art/app/  will not open on Wolvic

### ISSUE THREAD

**Issue by matlu** [Igalia/wolvic#267]
Try to open the Wonderland Engine based experience, https://sprayspace.art/app/
You will notice it does not open on Wolvic (1.0.2/1.1)/Quest 2, but it opens on Quest browser/Quest 2.

```
```

</details>

**Comment by Srile** [comment]
Hello, creator of Spray Space here!

I have updated the app to Wonderland Engine 0.9.1 and opened it in Wolvic 1.1 (Quest 2). It works, but there is a quite visible performance difference compared to Oculus Browser. I'll further investigate what's causing the performance issues.

**Comment by matlu** [comment]
@Srile 
We tested again and these are our findings:
For Wolvic 1.1 and Quest Browser (on Quest 2): Both have the exact same experience.
But, not related to these browsers, I could not get close to the wall and actually spray paint anything. You hear the audio when pressing the spray can top (“psss”), but no paint is coming out of the spray can.

Not on desktop browser on your PC/Mac you can spray (works as expected).

**Comment by svillar** [comment]
> @Srile We tested again and these are our findings: For Wolvic 1.1 and Quest Browser (on Quest 2): Both have the exact same experience. But, not related to these browsers, I could not get close to the wall and actually spray paint anything. You hear the audio when pressing the spray can top (“psss”), but no paint is coming out of the spray can.
> 
> Not on desktop browser on your PC/Mac you can spray (works as expected).

I can, you have to use the left controller to teleport you next to the wall. Then you could start painting

**Comment by matlu** [comment]
@Srile 
Another issue which is not WebXR specific is that if you e.g. pick Brick as you background and then do some spraying and finally press: "Save drawing to device"
You will notice that the you will only get the spray pattern not the actual wall texture behind (that you have picked).

I believe this a bug that should be fixed.
Issue can easily be reproduced by using Sprayspace on your Desktop Browser as well as with the Meta Quest Browser on Quest 2.

A future feature could maybe be to download 2 files, both the pattern so you can overlay on any background and the complete work.

**Comment by Srile** [comment]
I can add an image explaining the controls in the beginning to remove some of the confusion regarding locomotion and other more complex interactions in the app. I think that could help.

**Comment by Srile** [comment]
@matlu It is intended, but I think what you are suggesting is a good feature to add. I think I will add a second button to save it with the wall.

**Comment by matlu** [comment]
@Srile 
Thanks for consideration. Your app works pretty good on a desktop browser with a mouse as input. Based on that would it be possible to make a WebXR 3DoF version?
There is a lot of 3DoF VR Glasses still around including in China that works with Wolvic.

**Comment by Srile** [comment]
@matlu 
Yes, the feedback on 3DoF is appreciated as well. I will add that to the upcoming feature list for Spray Space.

My goal is to make the app as accessible as possible for all kinds of devices, so feedback like this is really useful. If there are any other recommendations on your end for making it more accessible(controls, input methods, etc.), do let me know.

**Comment by svillar** [comment]
So it looks like the original issue is fixed now, I'll close this then. Discussions about specific apps should happen in other forums.
