### ISSUE TITLE
Setup instructions third party unclear

### ISSUE THREAD

**Issue by worph** [Igalia/wolvic#270]
**Is your feature request related to a problem? Please describe.**
It's not easy to find the various SDK to add in the third_party folder especially the one for OVRPlatformSDK

**Describe the solution you'd like**
Link to the SDK to download in ReadMe.md

**Describe alternatives you've considered**
Searching the SDK myself

**Additional context**
Still looking for the SDK to download and put in this folder OVRPlatformSDK

**Comment by svillar** [comment]
You're absolutely right, we need to improve that. In the particular case of OVR you should have something like this
```
➜  OVRPlatformSDK git:(main) tree 
.
├── Android
│   └── libs
│       ├── arm64-v8a
│       │   └── libovrplatformloader.so
│       └── armeabi-v7a
│           └── libovrplatformloader.so
└── Include
    ├── OVR_AbuseReportOptions.h
    ├── OVR_AbuseReportRecording.h
    ├── OVR_AbuseReportType.h
     | ... up to 204 include files in that dir
```

**Comment by svillar** [comment]
OVR is already deprecated, we do use OpenXR for Meta devices. So closing this

**Comment by underoot** [comment]
Does it mean that README also should be updated?

**Comment by svillar** [comment]
> Does it mean that README also should be updated?

It's already updated, it does not refer to the deprecated OVR SDK. It only contains a reference to `third_party/OVRPlatformSDK/` which is still needed for release packages for the store, because include API calls that are required by the Meta store. It is not a VR SDK but a app store SDK.
