### ISSUE TITLE
Background music not stopped after closing tab/window

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#271]
## Configuration

Wolvic version: 1.1
Hardware: Oculus Quest 2, HVR

## Steps to Reproduce

1. Open Wolvic and navigate to https://constructarcade.com/game/archery-training/
2. Enter immersive mode (VR button) so that background music start playing.
3. Open a new tab and switch to it.
4. Close the previous tab where Archery Training game is running.

## Current Behavior

Music keeps playing in the background.

## Expected Behavior

Music should stop, since tab was closed and web app is no longer running.

**Comment by svillar** [comment]
I guess it'd be a good idea to contact the creator(s) of the game, in order to know which kind of APIs they're using.

**Comment by svillar** [comment]
> I guess it'd be a good idea to contact the creator(s) of the game, in order to know which kind of APIs they're using.

Replying to myself this is a problem in Wolvic/Gecko so no need for that.

**Comment by svillar** [comment]
I'm going to close this as I'm pretty sure this is a [Gecko issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1766545) which is also the source of the many audio start/stop issues we have.
