### ISSUE TITLE
The VR picture blinks

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#28]
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 

Hardware: HUAWEI VR Glass 6dof

## Steps to Reproduce

1.
2.
3.

## Current Behavior

Blinking: On a normally displayed screen, there is a possibility that a picture is displayed, and the content is the same as that already displayed.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by dingsing2021** [comment]
> Could be related to refresh rate, as I only reproduced this with Quest and not with other devices. We have updated it to 90hz, let's see if this has a impact here

-- I have tried the 3dof version , huawei VR runtime version 3.5.0.75,There is almost no picture flicker.

**Comment by svillar** [comment]
Thanks for verifying. I guess we can close this know. Let us know if you experience the same issue again.
