### ISSUE TITLE
WebXR: Anti-aliasing not enabled on XR Session

### ISSUE THREAD

**Issue by Squareys** [Igalia/wolvic#284]
## Configuration

Wolvic version: Wolvic 1.1 Quest2 & Latest App-Gallery version on HVR (09/28/2022)
Wolvic build ID: 

Hardware: Quest 2, HVR 6dof with Mate 40 Pro

## Steps to Reproduce
1. Start any Wonderland Engine based experiences. It's not possible to deactivate antialiasing, so it should be enabled for any.
2. Enter VR

## Current Behavior
Anti-aliasing is not enabled, visuals appear pixelated

## Expected Behavior
Anti-aliasing is enabled

```
```

</details>

Follow-up on https://github.com/Igalia/wolvic/issues/111, which only fixed anti-aliasing in the browser app itself, not when entering the VR session.

**Comment by svillar** [comment]
Antialiasing in #111 was enabled for XR sessions. You can check the MSAA values in Settings->Display->MSAA

It's definitely working, I've just tried the simple examples in [WebXR samples](https://immersive-web.github.io/webxr-samples/) and the difference is quite significant.

Note that HVR platform has MSAA disabled by default as in the tests we did after #111, activating MSAA was causing a severe performance drop in most of the cases.

Visuals do indeed appear pixelated in WonderlandEngine experiences as far as I can see, but not sure antialiasing is the culprit, as it should be enabled. I will check with the inspector later, maybe there is some JavaScript issue in the console while initializing the canvas.

**Comment by Squareys** [comment]
> activating MSAA was causing a severe performance drop in most of the cases.

It certainly should, it's doing a lot more work :)

But that explains why the MSAA was (intentionally) "missing" on HVR at least. Is there a way to enable it anyway as a user app?

**Comment by svillar** [comment]
> > activating MSAA was causing a severe performance drop in most of the cases.
> 
> It certainly should, it's doing a lot more work :)
> 
> But that explains why the MSAA was (intentionally) "missing" on HVR at least. Is there a way to enable it anyway as a user app?

Yeah, go to Settings->Display and then you have the option to disable MSAA or set it to 2x or 4x. I've just tried several WonderlandEngine games with 2x in HVR and it's working fine, no jagged edges I mean.

**Comment by svillar** [comment]
Note that I've [landed](https://github.com/Igalia/wolvic/pull/300) a patch that enables MSAA 2x by default in HVR devices with Harmony 3.0. Closing this now.
