### ISSUE TITLE
How to set the homepage? Also how to make 360 videos the default?

### ISSUE THREAD

**Issue by syami** [Igalia/wolvic#285]
**Is your feature request related to a problem? Please describe.**
Every time I open Wolvic, I need to go to the specific website and need to type the entire address. Also I need to change the default to 360 degree videos. Perhaps this is a feature that already exists?

**Describe the solution you'd like**
Make it part of the settings

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by svillar** [comment]
You can set the homepage in settings.

WRT 360 videos the default, I am not sure what you mean. In which platform?

**Comment by syami** [comment]
Thanks for the reply.
In Oculus, how can I update the settings?
Also wrt 360 videos, in oculus, how do I make them as the default?
For that matter, in any other platform, how can I make them as default?

**Comment by svillar** [comment]
You can access settings from the icon in the tray bar.

Again I don't undestand what do you mean with making 360º the default. Please explain it better or with an example.

**Comment by syami** [comment]
I can bookmark a page using the settings. However, I don't see an option to make it the home page. Am I missing something here?

As for 360 degree videos - for example, when I open a video and start running it, I can go to the bottom right of the browser and choose the video type - 3-d side by side, 360, 360 degree stereo, 180 degree and so on. I would like to choose 360 degree as the default. Is that possible?

**Comment by svillar** [comment]
You can set the homepage in `Settings->Display->Homepage` (click on `Edit` button).

With regard to the format of the video, we do have heuristics in place that try to detect the most suitable version. They're heuristics after all so they won't work in all of the cases. If you have a specific video that is not properly detected, please reopen this issue and let us know. Thanks!
