### ISSUE TITLE
A blue line appears in the middle of the screen.

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#29]
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 

Hardware: huawei vr glass 6dof

## Steps to Reproduce

1. open wolvic
2. open a 6dof game：moon rider
3.

## Current Behavior

A blue line appears in the middle of the screen.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by fwei-io** [comment]
![image](https://user-images.githubusercontent.com/57159719/153505509-f10982f8-64ab-4be3-b99d-44c17383b825.png)
Attached screenshot to show the blue line.

**Comment by juanjosanchez** [comment]
Is this happening with Moon Rider or always when you open Wolvic? The screenshot seems to be showing a configuration screen.

**Comment by dingsing2021** [comment]
> Is this happening with Moon Rider or always when you open Wolvic? The screenshot seems to be showing a configuration screen.
When the blue line appears, it will appear on all images. not only the configuration  screen.
However, the blue line does not appear every time, but there is a certain probability. The regularity of the blue line has not been found yet.

**Comment by svillar** [comment]
As mentioned in issue #50 that blue line is basically the security fence that is not properly shown. I'll close this as duplicate. Thanks for reporting!
