### ISSUE TITLE
Oculus Go please

### ISSUE THREAD

**Issue by TA-001** [Igalia/wolvic#291]
Noted that on the statement in Sept that Oculus Go is counted as legacy. Does this mean it will never be supported or the changes required will be to great to ever get it working?

**Comment by svillar** [comment]
> Noted that on the statement in Sept that Oculus Go is counted as legacy. Does this mean it will never be supported or the changes required will be to great to ever get it working?

Maintaining a web browser like Wolvic it's a huge amount of work: releasing, bug fixing, QA, new features, integration of new platforms.... Our team is small at the moment, so we have to focus on high priority tasks for now. If at some point there is enough interest (and more importantly funding) for some other platform (like Go) then we could evaluate that. In the meantime, we have to focus on the requirements of the partners which are currently supporting the development of Wolvic.

**Comment by svillar** [comment]
I closed this, and I noticed that it might seemed a bit harsh. Nothing farther from my intention :smile:. I hope you understand the motivation of our decisions.
