### ISSUE TITLE
in kiosk mode, maybe it needs a loading progress bar of the webxr content

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#299]
## Configuration

Wolvic version: 1.1.1
Wolvic build ID: 

Hardware: huawei vr glass 3dof/6dof

## Steps to Reproduce

1.open wolvic , and enter some webxr contents
2.
3.

## Current Behavior

because some website loading take some times (several seconds), if there is no Web page loading progress bar, the user maybe confused and restless.

## Expected Behavior

maybe it needs a loading progress bar.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by HollowMan6** [comment]
We actually have a stop-loading/refresh button that can indicate the current status of the page. Maybe we can wrap a ring to that button for an indication of the loading progress.
