### ISSUE TITLE
Any plans to support PICO 4?

### ISSUE THREAD

**Issue by srjanese** [Igalia/wolvic#306]
Any plans to support PICO 4?

**Comment by lubobill1990** [comment]
+1

**Comment by svillar** [comment]
It's definitely an interesting platform for us.

**Comment by DennieBee** [comment]
Definitely would like Wolvic support for the PICO 4. Current build in browser on PICO OS 5 seems to have limited WebGL support, resulting in (for example) a maximum texture size of 4096x4096, which is not always sufficient for simple skydomes, or stereoscopic photo and video.

**Comment by rekliner** [comment]
would also be cool to have web AR with the color camera.

**Comment by Hotcooler** [comment]
Would indeed be nice.

**Comment by Kalrkloss** [comment]
Please please please. Wolvic is by far my favorite browser in VR.

**Comment by rpavlik** [comment]
Once it has an OpenXR runtime it should just work, right?

**Comment by acfsmith** [comment]
> Once it has an OpenXR runtime it should just work, right?

Few additional small steps needed: use Pico's input profile for controllers, small corrections in manifest and embed copy of Pico's OpenXR library.

**Comment by svillar** [comment]
> Once it has an OpenXR runtime it should just work, right?

As pointed out in the previous comments there are additional steps needed for that. Also it's worth noting that the current OpenXR backend does not completely support all kind of XRLayers (we're working on that right now). It's however indeed possible to run a layer-less OpenXR session as we have a geometry fallback.

**Comment by rpavlik** [comment]
Pico should be using the normal standard loader once their runtime rolls out. I should know: I maintain the OpenXR software as part of being the spec editor
