### ISSUE TITLE
Is it possible to Integrate Wolvic browser inside unity?

### ISSUE THREAD

**Issue by JerrieSteve** [Igalia/wolvic#307]
Hi,
This more like a info request not issue or feature request!
Am new to VR and am trying to integrate a browser inside a unity project.
I am interested in integrating Wolvic Browser in my project and how can it be carried out!
Any kind of information will be helpful!

Thanks

**Comment by willguest** [comment]
I have looked into this, but wanted to do it in a webgl build, which isn't yet supported anywhere. best thing around at the moment is probably [webview 3d](https://developer.vuplex.com/webview/overview), but there may be others

**Comment by RoxDevvv** [comment]
+1

**Comment by svillar** [comment]
What do you exactly need, something like a WebView? If that's the case then I wouldn't use Wolvic because we don't provide that. Wolvic is a browser by itself.

**Comment by RoxDevvv** [comment]
@svillar yes i need to allow my game player to access some web pages inside the game

**Comment by svillar** [comment]
> @svillar yes i need to allow my game player to access some web pages inside the game

Then my advice would be to use the android WebView or Mozilla's GeckoView as Wolvic does. We basically don't provide the option of embbeding Wolvic because we're already a browser, you need something in a lower level.
