### ISSUE TITLE
No clear way to submit links for the start page (wolvic.com/*/start)

### ISSUE THREAD

**Issue by DougReeder** [Igalia/wolvic#318]
**Is your feature request related to a problem? Please describe.**
The curated links are an excellent set of sites to start, but they are at least somewhat arbitrary.

**Describe the solution you'd like**
A form on the web to submit WebXR experiences, and machinery behind it to vet webapps (to the extent possible) to minimize the time curators need to spend on each submission.

**Describe alternatives you've considered**
Emailing the developers is not a sustainable solution.

**Comment by svillar** [comment]
There are plans to have a more dynamic start page. In the meantime what about opening issues here in github with suggestions? We cannot fulfil everyone's desires but it will definitely help us to have a more appealing start page

**Comment by DougReeder** [comment]
These experiences are good:

https://travisbarrydick.github.io/vr-planets/dist/
https://whiteboard-vr.herokuapp.com/


These games are good:
https://constructarcade.com/game/trajectile-command/
https://constructarcade.com/game/archery-dungeon/
https://de-panther.itch.io/dualitower
https://roguesaber.rvdleun.com/
https://js13kgames.com/games/c991/index.html
https://plockle.com/play
https://constructarcade.com/game/back-to-space/




This is a great example of what VR can do, but the controllers aren't showing up:
https://virtualice.byrd.osu.edu/

When you have resources to implement the Layers API:
https://diegomarcos.com/render-the-metaverse/

**Comment by svillar** [comment]
Many thanks, some of them are already in our lists (like plockle, archery dungeon or rogue saber) but we'll definitely consider adding some of them.

**Comment by svillar** [comment]
Closing this. People can suggest new environments here in github or in the discord channel.
