### ISSUE TITLE
wolvic home page "https://www.wolvic.com/zh/" ,  a wrong link to huawei app gallery@CN , it seems a wrong app id 

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#319]
## Configuration

Wolvic version: 1.1.1
Wolvic build ID: 

Hardware: huawei vr glass

## Steps to Reproduce

1.  https://www.wolvic.com/zh/

2. click "HUAWEI Appgallery", it will go to https://appgallery.huawei.com/app/C105177629  , maybe "C105177629  "  is wrong for the CN users.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
You're right, it's pointing to the overseas version. We'll fix that, thanks for reporting.

**Comment by dingsing2021** [comment]
here is the wolvic link in huawei appgallery for CN user
https://appgallery.huawei.com/app/C106964279

**Comment by svillar** [comment]
Thanks this should be fixed now.
