### ISSUE TITLE
A black window shows instead of the volume adjustment window , when you adjust the volume

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#322]
## Configuration

Wolvic version: wolvic 1.2 & harmony OS3.0 & vr sdk 3.5.0.79
Wolvic build ID: 

Hardware: huawei vr glass & mate40pro

## Steps to Reproduce

1.open wolvic 
2. adjust the volume , by the 3dof controller or the button on the cable.
3.

## Current Behavior

when you adjust the volume, A black window shows instead of the volume adjustment window.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
We don't show the volume adjustment slider. That's done by the system. I guess there is some regression there.

Interestingly I don't see that behaviour when trying with a basic OpenXR demo I have. Will have to take a deeper look.

**Comment by svillar** [comment]
@dingsing2021 could you please check 1.2 with Harmony 2.0? I know some stuff won't properly work, but it would be nice to know whether this is reproducible in previous versions of the OS. I suspect this is caused by a regression in the OpenGL stack in Harmony 3.0

**Comment by svillar** [comment]
> @dingsing2021 could you please check Wolvic 1.2 with Harmony 2.0? I know some stuff won't properly work, but it would be nice to know whether this is reproducible in previous versions of the OS. I suspect this is caused by a regression in the OpenGL stack in Harmony 3.0

So we have just tried Wolvic 1.2 with a Harmony 2.0 device and everything is working as expected so it must be a regression on the graphics stack in Harmony 3.0. Reported against the [SDK](https://github.com/hms-ecosystem/OpenXR-SDK/issues/46)
