### ISSUE TITLE
Controllers tracking not working with 3DVista player

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#328]
Experiences run with the 3DVista player tool lack controller tracking, i.e., VR controller is shown but it does not follow the movements of the real one.

Examples of it:
* https://virtualice.byrd.osu.edu/
* https://www.3dvista.com/samples/real_estate_virtual_tour.html

It might be a server side issue, but I'll open this for tracking purpouses.

**Comment by lukefwilson** [comment]
Hi there, we're experiencing this issue as well with the latest Wolvic build (v1.4.1) on Quest 2. Any tips for how to fix this? Thank you!

**Comment by svillar** [comment]
Works fine in 1.6.1. So closing this
