### ISSUE TITLE
No mic button in the Keyboard for HVR build

### ISSUE THREAD

**Issue by matlu** [Igalia/wolvic#33]
## Configuration

Wolvic version: 
Wolvic build ID: 0.9.3

Hardware: Huawei VR Glass 6DoF

## Steps to Reproduce

1. Go Wolvic Settings and Privacy
2. Enable Microphone settings and observe the browser app restarting
3. Try to type in a URL using the keyboard, notice that the Mic button is not visible (It is visible in the Oculus build)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I've tested the latest build and the mic button is shown in the URL bar. Note that once you click on the url bar and the keyboard is shown then we hide the mic button. We do that always, for the Oculus build as well.

I'm closing this now. Please reopen in case you have additional concerns.
