### ISSUE TITLE
Fail to load application "https://app.3dcat.live/raystreaming/rayvision/player-normal.html?appKey=UQ0sE3e5UZfKhZtp"

### ISSUE THREAD

**Issue by XujieHong** [Igalia/wolvic#330]
Hi, 
I try to load web application "https://app.3dcat.live/raystreaming/rayvision/player-normal.html?appKey=UQ0sE3e5UZfKhZtp" on my Android phone with wolvic(v1.2, noapi variant), but failed.  
It doesn't work with Android Firefox brower either, however, seems it works well with any other browers.

BR

**Comment by svillar** [comment]
Thanks for reporting. If it does not work on Android Firefox then it's a problem in Gecko. That site seems not to work for me either on desktop, for example with Firefox Desktop I get this in the console `WebRTC: ICE failed, your TURN server appears to be broken, see about:webrtc for more details`. In the case of Chrome it does not complain but it does nothing apart from showing a neverending animation.

So my recomendation would be to file a bug in https://bugzilla.mozilla.org against Fenix (Firefox for Android).

BTW I'm curious, the last time I tried the noapi backend, it was broken, if you managed to create a package with it, mind sending a PR with your changes?

**Comment by svillar** [comment]
The page returns a 404. Closing this as non-actionable
