### ISSUE TITLE
on a shared device clearing cache and history it does not reset everything 

### ISSUE THREAD

**Issue by bghrb** [Igalia/wolvic#345]
If you have a shared vr device (for demonstrations) and you want to reset it for the next user.

 Clearing cache and history does not seem to reset everything.

You also have to click don't reopen open tabs.

But even then if you browse pages it still has advertising suggestions for the last person that used possibly because  it remembers the last persons advertising ID
 
The only way I have found that resets everything is to uninstall and reinstall the app.

Could the clear cache and cookies be improved to clear everything similar to uninstall and reinstall?

## Configuration

the latest download as of Nov 18 on meta quest 2

Wolvic version: see above
Wolvic build ID: see above

Hardware: meta quest 2

## Steps to Reproduce

Browse to and web page and then another one
Clear cache and history and turn off reopen open tabs 
exit app 
Open app
Start typing a web page address anyone. Google search still seams to remember your last web pages and they appear at the top even though the delete cookies were pressed before closing the app .

1.
2.
3.

## Current Behavior

I would think clear cache and history would clear all data including ie advertising or tracking cookies but it doesn't seem too

If you clear cache and history it should behave like a fresh user and not show advertising for the last user due to saved cookies

## Possible Solution

Uninstall and reinstall is the current only solution.
It's not clear what needs to be reset without doing that

For shared kiosk virtual reality sets used at demonstrations so the next user gets a fresh clean start.

Add a better clean cookies and advertising I'd button

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Hi,

so for your use case I see a couple of things that I think could fit without any change in Wolvic
1. Go to the device settings and select the option to clear data (normally under Storage section)
1. Use the incognito mode for each user. That mode does not permanently store things like cookies, history etc so you'd start fresh everytime

Does it make sense?

**Comment by bghrb** [comment]
> Hi,
> 
> so for your use case I see a couple of things that I think could fit without any change in Wolvic
> 1. Go to the device settings and select the option to clear data (normally under Storage section)
> 1. Use the incognito mode for each user. That mode does not permanently store things like cookies, history etc so you'd start fresh everytime
> 
> Does it make sense?

That would work if people followed instructions but when people don't follow instructions and they exit incognito  lots of random stuff gets saved the only way to clear is to uninstall and reinstall . I was just suggesting a button to add better clear funtionity. For instance at a store when customers want to test out a computer or a tv some of them have a store mode or demonstration option so that it can easily be cleared for the next customer or the start of the new sales day. My suggestion is along those lines but for the wolvic browser.

Is what I am describing above possible?
