### ISSUE TITLE
Links for Oculus AppStore and Huawei AppGalery on your website are swapped.

### ISSUE THREAD

**Issue by dustojnikhummer** [Igalia/wolvic#352]
Not really an app bug report, just a website bug report.

https://www.wolvic.com/en/#:~:text=Look%20for%20the%20Wolvic%20in%20the%20Oculus%20App%20store%20and%20the%20Huawei%20AppGallery%2C%20or%20you%20can%20download%20and%20build%20it%20yourself.

**Comment by svillar** [comment]
Hmm, I think they are correct, I have https://appgallery.huawei.com/app/C105177629 for the AppGallery and https://www.oculus.com/experiences/quest/4812663595466206/ for the Oculus store.

**Comment by dustojnikhummer** [comment]
I'm talking about the "Target devices and how to get Wolvic" section, not the AppGalery, Oculus and Vive buttons at the top.
https://i.imgur.com/Z2bSXuC.png

Still happens. In Edge, Chrome and Firefox. Also happens on my phone in Chromium based Kiwi Browser

**Comment by svillar** [comment]
Oh... sorry about that, I thought you meant the icons. Yeah you're totally right, thanks for reporting!

**Comment by svillar** [comment]
Should be fixed now.
