### ISSUE TITLE
Fail to Enter Full-Screen Mode

### ISSUE THREAD

**Issue by ZengRun** [Igalia/wolvic#362]
## Configuration

Wolvic version: any
Wolvic build ID: any

Hardware: any

## Steps to Reproduce

1. load https://m.v.qq.com/x/m/play?cid=mzc00200kf65gbf&vid=&ptag=v_qq_com%23v.index.adaptor%233
2. click play button on the video area
3. click fullscreen button on the right of the video control bar

## Current Behavior

Fail to enter fullscreen mode cause **onFullScreen** of ContentDelegate isn't called
![Screenshot_2022-11-28-19-48-19-49_0623c070449fb10dc4872d0619244d69](https://user-images.githubusercontent.com/10266846/204270547-263cc1c5-5c33-4920-9fb1-adb6976ebc56.jpg)
## Expected Behavior

Enter fullscreen mode expectedly after click the fullscreen button

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I wonder what happened with this?
