### ISSUE TITLE
No menu and search window in 1.2 version

### ISSUE THREAD

**Issue by Danielypzhang** [Igalia/wolvic#363]
## Configuration

Wolvic version: 1.2
Wolvic build ID: HVR

Hardware: 

## Steps to Reproduce

1. Open the Wolvic no menu  and search windows, can't open new web windows.  Mate20 X  HOS 2.0
2. Use the old version 1.0 works well.
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Hi @Danielypzhang, are you by chance using the mainland China version?

If that's the case then Wolvic is run in kiosk mode, meaning that you only get the browser window but no UI

**Comment by Danielypzhang** [comment]
I use Wolvic hvr arm64 cn release.  what's the kiosk mode? How to get the UI instead only the browser window?

**Comment by Danielypzhang** [comment]
@svillar

**Comment by svillar** [comment]
> I use Wolvic hvr arm64 cn release. what's the kiosk mode? How to get the UI instead only the browser window?

You have to use the overseas version of wolvic

**Comment by svillar** [comment]
@Danielypzhang was that the issue?

**Comment by Danielypzhang** [comment]
@svillar  using the overseas version works. Thank you.
