### ISSUE TITLE
Pico 4 WebXR Compatibility Issues

### ISSUE THREAD

**Issue by phr00t** [Igalia/wolvic#365]
Very excited to see Pico 4 support come in! I tried it out, and WebXR did load, but then I ran into some issues...

## Configuration

Wolvic version: https://github.com/rsjtdrjgfuzkfg/wolvic/releases/tag/testbuild-pico-2022-11-30
(this was the only Pico 4 build I could find)

Hardware: Pico 4

## Steps to Reproduce

1. Go to Moonrider.xyz
2. Click "Begin", Go into VR and "Press any key to continue" to start the "game"

- and -

1. Try playing 180/360 degree videos in VR / WebXR mode.

## Current Behavior

Everything seem to work fine while in the "browser", but things broke down when entering a WebXR environment (e.g. Moonrider).

Hands are not tracked and I couldn't find any buttons that worked to do anything. I was stuck in the game lobby and had to exit out of the browser completely.

Headtracking was working good and the game looked pretty cool, but I couldn't use my hands or interact with anything.

I also noticed when trying to play WebXR 180/360 videos, the video UI was attached to my head and I couldn't interact with the controls or play the video.

## Expected Behavior

Hands should be tracked and WebXR video player shouldn't be stuck to your head (and be pointed at to be clicked etc).

## Context

I want to play WebXR content.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Please do not report bugs about unofficial builds of Wolvic. That package you mention was not generated by us so we don't have any control over it.

With regard to the Pico 4 support it's still in early stages. There are no 3D models for the controls. Hand tracking is not supported yet. XR layers are not supported... You'd have to wait a  bit.

**Comment by svillar** [comment]
Thanks for reporting BTW. I hope I didn't sound harsh by closing the issue, it's just the support is still in very early stages, that's why we haven't released anything yet.
