### ISSUE TITLE
Wolvic browser interface without tracking

### ISSUE THREAD

**Issue by GXboy12345** [Igalia/wolvic#371]
## Hardware
Quest 2 standalone w/ applab

## Steps to Reproduce
Open Wolvic in a low-light etting or any situation that wouldn't allow quest/meta tracking
## Current Behavior
Interface is very far away, ~3-4 meters, andcontrollers are very far from actual positon
## Expected Behavior
Functionality similar to discontinued Firefox Reality (display ~1 meter away, controllers's position roughly accurate)
## Possible Solution
I feel there might be an issue with camera locaton.
## Context
Due to this, I have been forced to use the discontinued Firefox reality browser, with its freezing problems and such.

```
```

</details>

**Comment by svillar** [comment]
I think this is a duplicate of #338. Thanks for reporting anyway!
