### ISSUE TITLE
Unable to play any Netflix video

### ISSUE THREAD

**Issue by Gh20221205** [Igalia/wolvic#373]
## Hardware

Meta Quest 2
## Steps to Reproduce

1. Once logged in and try to play any video, no video will be played, instead there is this on the screen: error code F1721-1331
2.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Yep, it's a well known issue. It looks like Gecko's DRM code is not able to handle Netflix streams. If I am not wrong the Meta browser cannot play it either.

**Comment by Gh20221205** [comment]
You are correct. Quest's stock browser can't play Netflix either, neither
can DeoVR. Hopefully Wolvic can be the first that fixes this issue.
Currently I'm watching Netflix played by Firefox on my desktop through
Virtual Desktop to archive the resolution of 1080p. The Netflix app in
Oculus Store only delivers 480p at this moment.

**Comment by svillar** [comment]
There is no support for playing Netflix outside the official app and there is very little we could do about that. Closing this as there is no action point from our side.

**Comment by jdagdelen** [comment]
Now that Meta's Browser will support Netflix in v66, perhaps the correct WideVine will be available on the headset to play Netflix?

**Comment by svillar** [comment]
> Now that Meta's Browser will support Netflix in v66, perhaps the correct WideVine will be available on the headset to play Netflix?

Likely, let's hope for the best

**Comment by jdagdelen** [comment]
Any updates on this?
