### ISSUE TITLE
Include option to set Wolvic as default browser

### ISSUE THREAD

**Issue by johnmanagexr** [Igalia/wolvic#374]
We use another application to launch WebXR links via an android intent. Currently, these launch into the default device browser. There doesn't seem to be a way to change what the default device browser is though.

**Describe the solution you'd like**
A setting that enables android to change the default browser to be wolvic, instead of the existing default.

**Describe alternatives you've considered**
Manually typic WebXR links instead of launching them via our application, or custom launching to Wolvic if users set this as the default within our own application.

**Additional context**
If there's another way to set this, I would be curious to know - thanks!

**Comment by svillar** [comment]
Wolvic does handle URLs in the form of `wolvic://com.igalia.wolvic/?url=URL`. You can trigger a `android.intent.action.VIEW` or `android.intent.action.MAIN` actions with those special URLs passed as data, wolvic will open them.

See #268 for more details.

Would that work for you?

**Comment by svillar** [comment]
Already fixed in #697
