### ISSUE TITLE
Not Starting on Oculus Go

### ISSUE THREAD

**Issue by DraconicNEO** [Igalia/wolvic#38]
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: Cannot obtain, can't launch the app.

Hardware: Oculus Go 64GB

## Steps to Reproduce

1. Open Wolvic Browser on Oculus Go

## Current Behavior

Browser Gives a popup stating that the latest version of Oculus software is required

## Expected Behavior

Launch the browser

## Possible Solution

Update app to remove the version check

## Context

```
```

</details>

**Comment by TA-001** [comment]
in #53 it says 
"[svillar](https://issueantenna.com/author/svillar)
[Comment Added an answer on March 28, 2022, 8:36 am](https://issueantenna.com/repo/igalia/wolvic/issues/53#comment-IC_kwDOGkFGF85AZO80)
Already mentioned in issue https://github.com/Igalia/wolvic/issues/38"
Does this mean it is still open on this thread ? Any idea of whether an oculus go apk will be produced and when ?
Thanks

**Comment by svillar** [comment]
I will close this as there are no plans to support those devices. We have a lot of challenges with newer devices and supporting indefinitely old devices would just slow down development.

In any case this is a free software project, the code with the Oculus Go profile is still in the tree so people should be able to build it.
