### ISSUE TITLE
htc flow video is black in website

### ISSUE THREAD

**Issue by stankuhn** [Igalia/wolvic#380]
## Hardware

HTC Flow
Vive browser 1.10 version code 110

## Steps to Reproduce

1. open website with video e.g. https://developer.playcanvas.com/en/tutorials/webxr-360-video/
2. click to play video
3.

## Current Behavior

sound of the video plays. picture of the video is black.

## Expected Behavior

sound and picture of the video should play

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Likely a Gecko bug, I can reproduce it.

**Comment by matlu** [comment]
Yes same here on lastest Wolvic build. Note video struggles a bit to play also in Meta Browser (buffering issues). Might be part of the problem.

**Comment by svillar** [comment]
This is reproducible on Firefox for Android 106.1.1, so it's indeed a Gecko issue. I've [filed a bug report in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1805698). Thanks for reporting!

**Comment by svillar** [comment]
We have good news :tada: There is a patch for the [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1655101) that once applied to our Gecko fork makes videos work again. Will be part of the upcoming 1.3 release.
