### ISSUE TITLE
Adding Improved file:/// URL Support

### ISSUE THREAD

**Issue by TechnocampsJack** [Igalia/wolvic#390]
I'm using Wolvic to help with WebXR development on the Oculus/Meta Quest 2. Currently I'm looking for ways to test my app without needing to launch an entire webserver every time I make a change.

Instead I've been attempting to use Wolvic by directing it to file:///storage/emulated... and so on to the path of my html file. On desktop Firefox this is rather easy. I can clearly find the right files, and it even shows me a simple directory listing. However, on Wolvic, unless you type in the **exact** filepath with no mistakes, it instead mistakes your file:/// url for a search term and sends it to your default search engine.

My request is that Wolvic treats any url starting with file:/// as internal only, and instead of searching the web, opens a cut-down directory listing of the local filesystem.

The reason for my request is that there aren't many alternatives. Oculus File Browser will only open a few non-developer files such as .png. Certainly not .html files. The other file browsers on the system don't automatically open in Wolvic. As Wolvic already has file:/// support when viewing downloads, improving that slightly would have great benefits for normal users in terms of download management, and a great boon to developers for VR on the web.

**Comment by veryetti1** [comment]
Same request
Trying to open local html file of virtual tour
And also seems like in Ukraine Firefox Reality is unavaliable
