### ISSUE TITLE
Cannot select alternative Build Variant in Android Studio

### ISSUE THREAD

**Issue by ipeakermit** [Igalia/wolvic#398]
## Configuration

Wolvic version: 5ff9f6b96c721e89da095eec36162ac48b27f671
Wolvic build ID: 

Hardware: 

## Steps to Reproduce

1. Open Wolvic in Android Studio Electric Eel | 2022.1.1 RC 3, Android Gradle Plugin version 4.2.2
2. Go to Build Variants
3. Select any variant under Active Build Variant
4. Output appears under Build: Sync tab
5. Active Build Variant reverts to "hvrArm64CnDebug"

Clearly I have something misconfigured in Android Studio, but what?

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I'm sorry but we cannot help with AndroidStudio issues. Switching among build variants have always worked fine. Perhaps check the logs, they might help identifying the issue.

In theory you should not need anything special in the configuration in order to make variants work.
