### ISSUE TITLE
When a user accesses content on constructarcade.com, the user experience of some content is abnormal.

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#40]
## Configuration

Wolvic version: 
Wolvic build ID: 0.9.3

Hardware: 

## Steps to Reproduce

1. open https://constructarcade.com/game/house-of-the-dead/ 
2.  
3.

## Current Behavior

The screen display is abnormal.
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by Squareys** [comment]
I'll tag @Sorskoot (House of the Dead) and @Srile (Construct Arcade) here, they might jump in if there's something they can help with.

**Comment by Squareys** [comment]
@FerryAbt is the CTO at Construct Arcade, tagging him here for potential help also.

**Comment by svillar** [comment]
I think we can handle this as part of issue #149
