### ISSUE TITLE
Local WebXR build crashes on startup due to missing libmozglue

### ISSUE THREAD

**Issue by ipeakermit** [Igalia/wolvic#416]
## Configuration

Wolvic version: 9d06ab663d60e5ef110f7598dc1a01c7cae330bf
Wolvic build ID: 

Hardware: Pico 3

## Steps to Reproduce

1. git clone https://github.com/Igalia/gecko-dev/
2. git checkout FIREFOX_103_0_2_RELEASE
3. [Gecko-dev] ./mach bootstrap [response 4: Android without artifacts]
4. [Gecko-dev] ./mach build
5. [Wolvic] ./gradlew installPicoxrArm64WorldDebug
6. run Wolvic on headset (crashes)

## Current Behavior

Crash with "java.lang.RuntimeException: Could not find mozglue path."

## Expected Behavior

Should start up normally as per maven Firefox build

## Possible Solution

When importing the local build, the resulting apk lacks lib/arm64-v8a/libmozglue.so , is that significant?

## Context

See [issue](https://github.com/Igalia/wolvic/issues/407) --- would like to test that fixes there work for WebXR. 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by felipeerias** [comment]
Thank you for the report @ipeakermit . I have ran into similar issues recently when compiling for Oculus and it turned out to be a problem with my configuration.

Could you check that you have the following two lines (uncommented) in your `gecko-dev/mozconfig` file?

```
ac_add_options --enable-application=mobile/android
ac_add_options --target=aarch64
```

Also, please check that your `wolvic/local.properties` file includes the following two lines pointing at your local `gecko-dev` copy :

```
dependencySubstitutions.geckoviewTopsrcdir=/.../gecko-dev
dependencySubstitutions.geckoviewTopobjdir=/.../gecko-dev/obj-aarch64-unknown-linux-android
```

**Comment by ipeakermit** [comment]
> Thank you for the report @ipeakermit . I have ran into similar issues recently when compiling for Oculus and it turned out to be a problem with my configuration.
> 
> Could you check that you have the following two lines (uncommented) in your `gecko-dev/mozconfig` file?
> 
> ```
> ac_add_options --enable-application=mobile/android
> ac_add_options --target=aarch64
> ```
> 
> Also, please check that your `wolvic/local.properties` file includes the following two lines pointing at your local `gecko-dev` copy :
> 
> ```
> dependencySubstitutions.geckoviewTopsrcdir=/.../gecko-dev
> dependencySubstitutions.geckoviewTopobjdir=/.../gecko-dev/obj-aarch64-unknown-linux-android
> ```

Thanks, that's solved it.

One point of note: setting dependencySubstitutions.geckoviewTopobjdir seemed not necessary, indeed it seemed to cause another issue.
