### ISSUE TITLE
Opening a WebXR experience from another app

### ISSUE THREAD

**Issue by Arvide** [Igalia/wolvic#450]
Is it possible to via an intent launch a WebXR experience in Wolvic in full screen (force webxr 360 view) without having to load the url first?

What we're trying to do is to seamlessly launch a WebXR experience from launcher app and then seamlessly bring the user back to the launcher after completing the WebXR experience.

**Comment by svillar** [comment]
It's not possible right now. You can use an intent to launch wolvic with a given URL but not in immersive mode.

**Comment by svillar** [comment]
Just for clarification, the problem of launching immersive WebXR experiences is that there is no standard way to do that. Most of the experiences use an "Enter VR" button. But that button is different on each experience, and it's something that is under the control of the WebPage. So there is no way for Wolvic to know how a particular experience should be launched.

There are things that could be done though, for example if we make the assumption that every experience has a button that must be clicked to enter the experience, then we could add some code to Wolvic that could process a couple of web page coordinates specified in an android intent, and simulate a user click on that button. I think that could be done. Would that solve your problem in your use case?

**Comment by Arvide** [comment]
Thank you!
Yes, that would indeed solve the problem.

Is that something you can be talked into adding?

**Comment by svillar** [comment]
> Thank you! Yes, that would indeed solve the problem.
> 
> Is that something you can be talked into adding?

It isn't a priority right now, but we could consider that for the future indeed (or if it becomes a priority for any of our partners)

**Comment by Arvide** [comment]
Thank you!

**Comment by msub2** [comment]
Also worth considering the proposed [WebXR navigation spec](https://github.com/immersive-web/navigation), where an experience listens for a `sessiongranted` event to automatically launch an immersive experience without the need for explicit user activation on the page

**Comment by svillar** [comment]
> Also worth considering the proposed [WebXR navigation spec](https://github.com/immersive-web/navigation), where an experience listens for a `sessiongranted` event to automatically launch an immersive experience without the need for explicit user activation on the page

Right we're following that development as well, but it'll take some time to land (if ever) and it isn't going to be likely implemented in Gecko.

**Comment by FlorisMXR** [comment]
Hi there, I saw this ticket has been closed. Could you provide any context if it's now possible to launch videos into VR mode in an easy way, instead of clicking in the menu? 

Best,

**Comment by FlorisMXR** [comment]
> Hi there, I saw this ticket has been closed. I was trying to be launched into VR mode straight away, but in all the WebXR links I've tried this didn't work when using the newest version of Wolvic. Any ideas why this is not working? Do you also have an example URL of one that works successfully based on your testing? We're curious if this would work for YouTubeVR.

Bumping this!

**Comment by svillar** [comment]
> > Hi there, I saw this ticket has been closed. I was trying to be launched into VR mode straight away, but in all the WebXR links I've tried this didn't work when using the newest version of Wolvic. Any ideas why this is not working? Do you also have an example URL of one that works successfully based on your testing? We're curious if this would work for YouTubeVR.
> 
> Bumping this! @svillar

Hi @FlorisMXR. Many of the questions you have, have been answered in PR #1171 which implemented this behaviour. As @felipeerias explained there not every single web application works. As mentioned in [this comment](https://github.com/Igalia/wolvic/pull/1171#issuecomment-2406487479) not all of them are suitable to be launched using the implemented strategy for reasons. That very same comment provide detailed instructions about how to launch experiences automatically on start (note that you'd have to adjust the package name, for example for meta is `com.igalia.wolvic.metastore` although for most of the other devices is just `com.igalia.wolvic`)

**Comment by FlorisMXR** [comment]
> > > Hi there, I saw this ticket has been closed. I was trying to be launched into VR mode straight away, but in all the WebXR links I've tried this didn't work when using the newest version of Wolvic. Any ideas why this is not working? Do you also have an example URL of one that works successfully based on your testing? We're curious if this would work for YouTubeVR.
> > 
> > 
> > Bumping this! @svillar
> 
> Hi @FlorisMXR. Many of the questions you have, have been answered in PR #1171 which implemented this behaviour. As @felipeerias explained, not every single web application works. As mentioned in [this comment](https://github.com/Igalia/wolvic/pull/1171#issuecomment-2406487479) not all of them are suitable to be launched using the implemented strategy for reasons. That very same comment provide detailed instructions about how to launch experiences automatically on start (note that you'd have to adjust the package name, for example for meta is `com.igalia.wolvic.metastore` although for most of the other devices is just `com.igalia.wolvic`)

Thank you for your response, our team is looking into it!
