### ISSUE TITLE
gecko supports VideoEncoder?

### ISSUE THREAD

**Issue by wei-kris** [Igalia/wolvic#452]
Hello, I want to visit a website on an HTC device. It uses the built-in VideoEncoder of the browser. After testing, the built-in browser of the HTC device does not support VideoEncoder, so I want to know whether gecko supports VideoEncoder?

Thank for any help ！

**Comment by svillar** [comment]
According to [this](https://caniuse.com/?search=videoencoder) VideoEncoder is not available nor even in 107 (we're using 105) so unfortunately not. In any case it's a pretty recent technology, Chrome for Android started to support it this month, so you'd have to wait a bit.
