### ISSUE TITLE
[Issue] VR Videos only play audio, no video, on most sites.

### ISSUE THREAD

**Issue by HVal561** [Igalia/wolvic#455]
## Configuration

Wolvic version: 1.2
Wolvic build ID: c355e128 (AC 63.0.0)

Hardware: Meta Quest 2 version 49.0.0.186.357.440026508

## Steps to Reproduce

Try to view a VR video on one of many sites that contain VR videos that are not Youtube or Vimeo.  This is seemingly the case on any pornographic website.

## Current Behavior

The video will start playing, but while audible, the actual video will be completely black.  This will be the case whether attempting to view the video in VR or without entering VR.

## Expected Behavior

The video would play in VR normally, as it does in the Meta Browser, or did in Firefox Reality.

## Context

I emphasize sites that are not Youtube or Vimeo, and seemingly any pornographic site, because upon viewing reviews for the browser on the Quest page, many people have reported this issue in reviews since the browser's most recent update without specifying any website, and every developer response asks what site specifically, asking "Youtube, Vimeo, or other?" and it seems likely that many people may be referring to pornographic sites and don't wish to disclose this.  I'm not naming any specific sites in this post as I feel it's not appropriate, though it seems to be the case with _any_ of them.  If it's not considered inappropriate and will help provide information, I'm more than willing to provide names for sites where the issue is experienced.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. This is a dup of #370 . Good news is that it's already fixed, and it will work in the about to be released 1.3
