### ISSUE TITLE
keyboard position messed up when open multiple windows in pico4

### ISSUE THREAD

**Issue by abamilod** [Igalia/wolvic#458]
## Configuration

Wolvic version: 1.2
Wolvic build ID: 

Hardware: Pico 4

## Steps to Reproduce

1. Open multiple windows
2. Try to write url on address bar
3. Keyboard position is above and cannot point with the controller

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting, right this is a well known issue for us. It started to happen after the migration to OpenXR layers. We'll investigate that but in the meantime we'll fix it by forbidding the keyboard to create cylinder layers.

**Comment by svillar** [comment]
Partially fixed by #459. The real fix is not that one though, as we're just switching to a quad layer instead of a cylinder layer, but at least the keyboard is not misplaced and remains usable.

**Comment by abamilod** [comment]
ok thank you. good enough.
