### ISSUE TITLE
3DSBS Audio-Video out of sync

### ISSUE THREAD

**Issue by max2treiber** [Igalia/wolvic#460]
## Hardware

HTV Vive Flow

## Steps to Reproduce

1. Open Wolvic
2. Browse to any 3D-180-SBS Video. I tested it with many different videos on a private Apache webserver in my LAN. The problem seems to occur independently of the encoding, but more frequent with higher resolution videos.

## Current Behavior

At first A/V is perfectly in-sync. After jumping forward and backward in the video a couple of times, audio and video become out of sync. There seems to be no way to get the sync back. The video has to be reloaded.

## Context

It suspect that this issue might be due to the low performance of the Qualcomm XR1 in the VIVE Flow and some frames beeing dropped in Video but not Audio or something like that.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Hi @max2treiber, thanks for reporting. As you know Vive is not officially supported so although we're always interested in making the browser better, these bugs might not have a high priority in our queue. Hope you could understand.

**Comment by max2treiber** [comment]
Sure, thanks the reply!!!
Just our of curiosity: What do you think, could this rather be a bug in an underlying Vive library? (If yes, which one?) or is the wolvic code itself responsible for rendering Audio and Video correctly?

**Comment by svillar** [comment]
> Sure, thanks the reply!!!
> Just our of curiosity: What do you think, could this rather be a bug in an underlying Vive library? (If yes, which one?) or is the wolvic code itself responsible for rendering Audio and Video correctly?

The one in charge of playing audio/video is the web engine, i.e. Gecko. Wolvic has no control about syncing and/or encoding/decoding. All we can do is the usual playback stuff: play,pause,stop etc...

That said Gecko is using android libraries to ultimately play those media files. So the issue could be at Gecko or Android level.

**Comment by max2treiber** [comment]
Ok, then this is most probably not related to wolvic at all. I also found out, that the same problem occurs with the Viveport Browser. Thank you!

**Comment by svillar** [comment]
> Ok, then this is most probably not related to wolvic at all. I also found out, that the same problem occurs with the Viveport Browser. Thank you!

hmm I think HTC is rebranding Wolvic and calling it Viveport Browser anyway?
