### ISSUE TITLE
Scene flashes white in several experiences while in immersive mode 

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#463]
## Configuration

Wolvic version:  1.3
Wolvic build ID: 59 onwards

Hardware: Quest2, Pico4

## Current Behavior
1. Open an immersive experience that is fairly graphics-intensive (e.g, https://mk-metaverse-scenes.netlify.app/?scene=louvre)
2. Enter immersive mode.

An white flash occurs frequently, covering the entire view. It doesn't seem to go away when the web app stops loading resources, but I have noticed that it is more prominent with some head poses than others. It makes for a really poor experience.  

## Expected Behavior
No annoying white flashes.

**Comment by javifernandez** [comment]
We have received comments from users via the feedback form about this issue:

> screen flashes white constantly in mozilla hubs demo space

**Comment by javifernandez** [comment]
This is still reproducible in the 1.4.2 version we are about to release. 

Is this issue related to #86 ? Just in case we could consider Mozilla Hubs an useful test case for this issue.
