### ISSUE TITLE
Add missing proguard rules in HVR flavor

### ISSUE THREAD

**Issue by MortimerGoro** [Igalia/wolvic#48]
## Steps to Reproduce

1. Create a release version of Wolvic for HVR with minifyEnabled = true
2. Application doesn't launch correctly
3. Create a release version of Wolvic for HVR with minifyEnabled = false
2. Application launches correctly

## Possible Solution

Add missing proguard rules specific for HVR

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by felipeerias** [comment]
Unless I'm missing something, I'm not seeing this problem any more.
