### ISSUE TITLE
Igalia/wolvic Oculus Go please

### ISSUE THREAD

**Issue by TA-001** [Igalia/wolvic#485]
As per issue 291 when you were coming to terms with wolvic,I was hoping to get it to work with the Oculus Go.
 it seems that version 1.3 may not be compatible with the Oculus Go due to major changes. What is the last version that will be compatible and how can I get it to work, please.

**Comment by svillar** [comment]
We have never released any version officially supported in the Oculus Go. We started working with the Quest2 as basis. I don't have a Go so I don't really know whether it would work there or not.

**Comment by TA-001** [comment]
Thanks for replying. Did the Quest2 a major rewrite of firefox reality due to significant changes in Oculus Quest 2 platform, or just made of minor incremental changes? Is there a way of me compiling it for an Oculus Go and testing it? How would I do this?
