### ISSUE TITLE
wolvic app AndroidManifest on hvr sdk

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#488]
## Configuration

Wolvic version: 1.3
Wolvic build ID: 

Hardware: huawei vr glass 3dof & 6dof

## Steps to Reproduce

1.
2.
3.

## Possible Solution

a requirement form hvr sdk R&D:
2D UI activity and 3D VR activity 

        <activity android:name=".GuideActivity"
            android:launchMode="singleTask"
            android:screenOrientation="landscape">
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <activity
            android:name="com.huawei.hvrsdk.nativedemo.MainActivity"
            android:configChanges="screenSize|orientation|keyboardHidden|keyboard"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:screenOrientation="landscape"
            android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" >
            
            <intent-filter>
                <action android:name="com.huawei.android.vr.action.MAIN"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Sorry, what are the required changes? And what are they for?

**Comment by dingsing2021** [comment]
> Sorry, what are the required changes? And what are they for?

its for the new hvr sdk version, please help to give us a test apk, thanks.

**Comment by svillar** [comment]
> > Sorry, what are the required changes? And what are they for?
> 
> its for the new hvr sdk version, please help to give us a test apk, thanks.

OK, so I have some questions:
1. As far as I see you are asking to split the current activity we have in 2, one for the phone view and another one for VR. Is that correct?
2. For the 2D activity you include `android:name=".GuideActivity"`, should we use `.GuideActivity` or the name of our activity as in the VR version?
3. What would happen for the current users if we release a package with these changes? Will something break for them? 

Regards

**Comment by dingsing2021** [comment]
feedback from hvr sdk:
this is not a new features in vr sdk,  and some other apps made with unity already support it.
The VR runtime can determine and perform corresponding processing based on this field.

default setting for 2D activity: android.intent.action.MAIN
default setting for 3D activity: com.huawei.android.vr.action.MAIN

and here is no breaking for users.
If it's convenient, compile a test package to provide

**Comment by svillar** [comment]
> feedback from hvr sdk: this is not a new features in vr sdk, and some other apps made with unity already support it. The VR runtime can determine and perform corresponding processing based on this field.
> 
> default setting for 2D activity: android.intent.action.MAIN default setting for 3D activity: com.huawei.android.vr.action.MAIN
> 
> and here is no breaking for users. If it's convenient, compile a test package to provide

We already have those, check the [manifest](https://github.com/Igalia/wolvic/blob/main/app/src/hvr/AndroidManifest.xml). Is there anything else required?

**Comment by dingsing2021** [comment]
for 3D and 2D ， wolvic should provide two different activities ：

here is the demo 

        <activity
            android:name=".VRBrowserActivity"    --- a activity for 3d vr mode
            android:label="@string/app_name"
            android:screenOrientation="landscape">
            <meta-data android:name="android.app.lib_name" android:value="native-lib" />
            
            <intent-filter>
                <action android:name="com.huawei.android.vr.action.MAIN"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>
        <activity android:name=".VRBrowser2DGuideActivity"  **--- add a new activity for 2D mode
            android:label="@string/app_name"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by svillar** [comment]
I don't think this is required anymore. Please reopen if some action is still needed
