### ISSUE TITLE
Moved out of the security zone and re-entered, wolvic has automatically exited

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#49]
## Configuration

Wolvic version: 0.9.3
Wolvic build ID: 

Hardware: huawei vr glass 6dof

## Steps to Reproduce

1. enter the Wolvic,  Go to the home page or open a VR application to enter the VR mode.
2. then walking exit the security zone( the head position out of the security zone ) , 
3. then the vr glass enter the VST(video see through ) mode ;
4. walking back and enter the security zone again, the VR Glass enter the VR mode.

## Current Behavior

1，wolvic has automatically exited;

## Expected Behavior

still go to wolvic, and the previously visited page remains the same.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I am not sure I understand the steps to reproduce the issue. I understand that

1. Launch Wolvic but do not enter VR mode yet
2. Move out of the security zone
3. Move back to the security zone

And then you mention that Wolvic exits, is that a good description of the issue?

**Comment by svillar** [comment]
I've been debugging this a bit. I don't know what the previous runtime was doing, but it looks like we're receiving an exit XR event from OpenXR. In that case we basically destroy all the resources and exit the application. This is the relevant part of the log

```
03-01 11:20:32.579  4634  8433 D HvrInterface: [@SDK][HvrInterface.cpp:unInitRender](546): OUT
03-01 11:20:32.579  4634  8433 I HxrFunctions: [@SDK][HxrFunctions.cpp:hxr_xrEndSession](645): out hxr_xrEndSession
03-01 11:20:32.579  4634  8433 I VRB     : OpenXR XrEventDataSessionStateChanged: state XR_SESSION_STATE_STOPPING->XR_SESSION_STATE_IDLE session=0x1 time=0
03-01 11:20:32.579  4634  8433 I VRB     : OpenXR XrEventDataSessionStateChanged: state XR_SESSION_STATE_IDLE->XR_SESSION_STATE_EXITING session=0x1 time=0
03-01 11:20:32.579  4634  8433 I VRB     : BrowserWorld::ShutdownGL
```

Now the thing is whether that is expected or not. From Wolvic side we might perhaps tune the way we handle the exit XR session, and do not exit the render loop in that case, and just whenever we have a request exit from Java...

**Comment by svillar** [comment]
The problem with this is the app model of Wolvic. We are not a windowed app but a fullscreen one which "ignores" the environment it's being run. This is similar to what happens with copy and paste to other apps. When we exit the security zone Android destroys the surface we use to paint the 2d browser environment. This means that we proceed to destroy all the associated resources and exit. Changing this will involve a big revamp of the browser. We'll eventually come back to this as soon as we have enough time for that.

**Comment by svillar** [comment]
As it was merged, I'm closing this.
