### ISSUE TITLE
The performance of Wolvic is worse than FirefoxReality(FFReality) while running webXR content.

### ISSUE THREAD

**Issue by MossPia** [Igalia/wolvic#492]
## Configuration

Wolvic version:   Version 1.3
Wolvic build ID:  

Hardware: 

Oculus Quest2,
Vive Focus3

## Steps to Reproduce

1.  Open Wolvic browser
2. go to  https://heyvr.io/game/archery-training
3. Enter VR mode

## Current Behavior

When the game running, the FPS is not good enough

## Expected Behavior

The running performance should presents good enough as FireFoxReality

## Context

I like to enjoy webXR content, I choose FFReality as default browser to play them and it works well. Since FFReality official announe to end support, so that I try to use Wolvic VR browser to instead of it.

Unfornatelly, the wolvic's performance is worse than FFReality after I test, the FPS reduce 7~8 frames per seconds. (Oculus quest2 and Vive Focus3 both I have, they got the similar test result)

Some forum said that to many GMEM load will cause the render performance down,  
https://developer.qualcomm.com/software/snapdragon-profiler/app-notes/avoid-gmem-loads

I try to use profiler tool to check, Wolvic's usage amount of GMEM load is higher than FFReality obviously , I am not sure whether it is the major reason to cause the performance got huge impact, could you check the problem ?

![image](https://user-images.githubusercontent.com/125337861/218652461-232d8636-a877-4178-b977-4136277eb3a3.png)
There are too many GMEM load from Wolvic (surface[3200, 1600])

![image](https://user-images.githubusercontent.com/125337861/218652634-67d0feef-10e7-41f4-8a70-5947470e24d2.png)
No GMEM load from FFReality (surface[3200, 1600])

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Well, Wolvic 1.3 uses OpenXR as backend while FxR (and Wolvic 1.2) use OculusVR. Maybe that's a source of those. Could you retest with Wolvic 1.2?

**Comment by MossPia** [comment]
I use Oculus Quest 2 to compare render rate between Wolvic 1.2 and 1.3, FPS in Wolvic 1.2 is better than Wolvic 1.3 while playing webXR content. 


[Use default settings]

Wolvic version 1.2 (fps 60~62)

Wolvic version 1.3 (fps 54~55) 

 

Also I found that GMEM load depth stencil symptom is gone after disable MSAA so that the performance got huge improve. 

[Disable MSAA]

Wolvic version 1.2 (fps 85~86)

Wolvic version 1.3 (fps 70~71)



I understand that enabling MSAA will introduce performance drop, however I can find Quest native browser can avoid GMEM load while enabling MSAA (4) and keep very high FPS (87~88). Maybe this is a potential area that you can significantly improve the FPS on Wolvic.

**Comment by svillar** [comment]
> I use Oculus Quest 2 to compare render rate between Wolvic 1.2 and 1.3, FPS in Wolvic 1.2 is better than Wolvic 1.3 while playing webXR content.
> 
> [Use default settings]
> 
> Wolvic version 1.2 (fps 60~62)
> 
> Wolvic version 1.3 (fps 54~55)
> 
> Also I found that GMEM load depth stencil symptom is gone after disable MSAA so that the performance got huge improve.
> 
> [Disable MSAA]
> 
> Wolvic version 1.2 (fps 85~86)
> 
> Wolvic version 1.3 (fps 70~71)
> 
> I understand that enabling MSAA will introduce performance drop, however I can find Quest native browser can avoid GMEM load while enabling MSAA (4) and keep very high FPS (87~88). Maybe this is a potential area that you can significantly improve the FPS on Wolvic.

This is very useful information @MossPia, thank you very much for the research. We'll take a look as soon as we have some available slot.

**Comment by BattleAxeVR** [comment]
Doesn't wolvic use gecko as the default backend? According to the backend comparison video, it runs about half the speed of chromium in some tests I did, so that may explain this. 

I've been trying to switch to chromium in a local test build here and having no luck, it's not obvious where to get the .aar for that or where to put or anything.

**Comment by svillar** [comment]
> Doesn't wolvic use gecko as the default backend? According to the backend comparison video, it runs about half the speed of chromium in some tests I did, so that may explain this.
> 
> I've been trying to switch to chromium in a local test build here and having no luck, it's not obvious where to get the .aar for that or where to put or anything.

See my reply to #501
