### ISSUE TITLE
Cant install the PICO XR build on Pico4. Its lloading till 90% than tells that "installation not possible". Did the latest Pico OS update, downloaded Wolvic apk through your website. Weird.

### ISSUE THREAD

**Issue by Falk4** [Igalia/wolvic#497]
Cant install the PICO XR build on Pico4. Its lloading till 90% than tells that "installation not possible". Did the latest Pico OS update, downloaded Wolvic apk through your website. Weird.

**Comment by svillar** [comment]
Just to double check, I've just downloaded it and installed on my Pico4 without any issue. So the question now is:

1. What's the Pico OS version you're using (mine is 5.3.2)
2. Are you donwloading the apk from github releases page or from wolvic.com/dl
3. How are you installing the package?
4. Is your device in developer mode?

**Comment by CodeFreezr** [comment]
Same Prob here. Pico OS 5.3.2. Tried both APK via wolvic.com/dl and github 1.3.1. Pico normally did not need Developer Mode to install apk.

**Comment by svillar** [comment]
> Same Prob here. Pico OS 5.3.2. Tried both APK via wolvic.com/dl and github 1.3.1. Pico normally did not need Developer Mode to install apk.

Same questions. How are you installing the package? Are you using `adb`?

**Comment by CodeFreezr** [comment]
As dozen others I download the APK here from github with the PicoBrowser. Then, like all my other APK installation, I click the APK and select "Intall". Installation begins until 90%, then it stops. A Info "Can't install Application" was displayed.

**Comment by svillar** [comment]
> As dozen others I download the APK here from github with the PicoBrowser. Then, like all my other APK installation, I click the APK and select "Intall". Installation begins until 90%, then it stops. A Info "Can't install Application" was displayed.

OK thanks for the info, we'll check that. So far we have installed it with `adb` via command line interface. We'll verify what's going on with the graphical install

**Comment by Falk4** [comment]
Now it works !!! I had to click 7 times to open Pico 4´s secret developer mode, than I allowed third party apps. Now it works.

**Comment by svillar** [comment]
> Now it works !!! I had to click 7 times to open Pico 4´s secret developer mode, than I allowed third party apps. Now it works.

Cool!. Thanks for researching, we'll add that info to the downloads page so every body is aware of that

**Comment by svillar** [comment]
So it looks like the problem was that you have to put the device in developer mode. We added a warning in wolvic.com/dl.

Hopefully we could get Wolvic into the store soon, so users won't have to deal with all this mess of sideloading the application.
