### ISSUE TITLE
Build instructions for chromium backend request

### ISSUE THREAD

**Issue by BattleAxeVR** [Igalia/wolvic#501]
Hi, after spending a couple hours trying to figure out how to enable the chromium backend, I'm giving up and just going to ask how to do it. 

I tried addubg backend=chromium in a user.properties file but then it asks for chromium_aar. 

I tried downloading cef and zipping that up manually then referring to it, but it didn't work and I'm not even sure that's the right library. Can anyone help? I've got the gecko default build running just fine but the 3D performance is inadequate for my needs. Thanks!

**Comment by svillar** [comment]
That backend is not ready at all, we did some experiment last year, but it was just that. Apart from that it was based on WebLayer, an API that is going to be deprecated in Chromium. So better wait for the results of the ongoing effort to use a chromium backend based on the content API.
