### ISSUE TITLE
Wolvic is unable to detect 360 degree videos

### ISSUE THREAD

**Issue by syami** [Igalia/wolvic#502]
**Is your feature request related to a problem? Please describe.**
Opening this feature request/bug. I had earlier referenced it here #285. The problem is that when I open a 360 degree video, I have to go through 3 separate clicks to indicate to the browser that it is a 360 degree video and it should render it accordingly. The first click is on the bottom right of the screen to expand the screen, the 2nd click is to select the 3-d Goggle icon, and 3rd is to select from the given list of video types. In this case it is 360 degree.
This in my opinion is a serious UX issue that takes away the fun of using a VR environment. It also takes a lot of effort for newbies to even know where to click and what.

**Describe the solution you'd like**
Auto-detect the video type and play.
<img width="1440" alt="Click-1" src="https://user-images.githubusercontent.com/28549987/220220800-802fa103-131e-406d-873f-df3d45d806f5.png">
<img width="1440" alt="Click-2" src="https://user-images.githubusercontent.com/28549987/220220803-8a8ee133-782a-4db7-86d9-aa6bade33005.png">
<img width="1440" alt="Click-3" src="https://user-images.githubusercontent.com/28549987/220220805-7d4760f3-48b9-468c-ba01-b70d6d23760e.png">

**Describe alternatives you've considered**
None

**Additional context**
See attached the 3 click screenshots in sequence (the first two are highlighted, the 3rd one is obvious) that are currently needed.

**Comment by svillar** [comment]
I agree with you that it's very important to make a good guess by default for videos. We already have code to do that but it might need improvements. Mind sharing URLs for videos were you see those issues? It will definitely help us debugging the issue.

**Comment by svillar** [comment]
> Unfortunately, these are our internal app URLs and not accessible outside the company :(
> Is it possible to send some kind of event notification to the browser so that the 3-clicks can be prevented? We can send 3 events in a row as well.

If that's an internal URL then there is little we could do. Perhaps you could setup some demo site and send us privately the credentials. That also explains why videos are not autodetected properly. That is not an easy task. Wolvic has an specific extension for YouTube that kicks in when visiting the site and that negotiates qualities and formats. The actual solution would be to do something similar for your internal apps, you could use the YouTube extension as a basis for that development.

**Comment by syami** [comment]
What is the name of the extension? Can we install it on our browser and see if that helps?

**Comment by svillar** [comment]
> What is the name of the extension? Can we install it on our browser and see if that helps?

It's already enabled in Wolvic, it's an internal extension that cannot be disabled. The code is [here](https://github.com/Igalia/wolvic/tree/main/app/src/main/assets/extensions/fxr_youtube)

**Comment by syami** [comment]
Thank you!

**Comment by svillar** [comment]
OK, let us know if you need something else. Also we'll happily consider integrating new changes that could improve that detection code. I'll close this because it seems a private use case, but again will be glad to reopen this if this becomes a general purpouse issue.
