### ISSUE TITLE
Pico 4 not work since update to 5.4.0

### ISSUE THREAD

**Issue by richi207** [Igalia/wolvic#506]
Browser 1.3.1 not work on Pico 4 since update Pico 4 to 5.4.0

**Comment by svillar** [comment]
That's unfortunate, do you have access to the device logs (`adb logcat`)? We'll check anyway once we get the update.

**Comment by Nidre** [comment]
Same problem on 5.4.0. 

You can install update manually:

Check it: `adb shell getprop ro.oem.state`
If you get **true**, download it: 
https://mirror.lewd.wtf/archive/picoxr/firmware/pico4/global/5.4.0-202302171231-RELEASE-user-phoenix-b3159-21724b5b8e.zip
If u get **blank or false**: 
https://mirror.lewd.wtf/archive/picoxr/firmware/pico4/global/non_oem/5.4.0-202302171557-RELEASE-user-phoenix-b3162-3d2f0dbe1b.zip

Put it zip to **/dload** on your pico (create this dir). And use manual update button.

**Comment by felipeerias** [comment]
@Nidre I'm sorry, but we don't support that. We will ensure that Wolvic works well with Pico 5.4.0 when it is officially released.

@richi207 Did you do a manual update as well?

**Comment by richi207** [comment]
Yes, I have manual updated

**Comment by belzebub40k** [comment]
> @Nidre I'm sorry, but we don't support that. We will ensure that Wolvic works well with Pico 5.4.0 when it is officially released.

AFAIK it is already officially released. I got the OTA update on my device a few days ago.

**Comment by svillar** [comment]
We know the reason of the crash. It's because we had to add a workaround for PicoOS < 5.4.0 because they did not implement correctly some part of the OpenXR spec. Looks like they fixed that in 5.4.0 so the workaround is causing Wolvic to crash (because it cannot create Android surfaces to display contents). We'll upload a PR soon and will release it as part of 1.3.2 to be released soon.

**Comment by owomushi** [comment]
[wolviclogs.txt](https://github.com/Igalia/wolvic/files/10834426/wolviclogs.txt)
this is my logcat
