### ISSUE TITLE
wolvic app Application Introduction in huawei appstore China update 

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#509]
## Configuration

Wolvic version: 1.3.1
Wolvic build ID: 

Hardware: huawei vr glass 3dof & 6dof

## Steps to Reproduce

1.
2.
3.

## Expected Behavior

the Application Introduction is simple and English  ， for china users ，it isn't very friendly, and some keywords missed, it is Unfavorable to search.
and version update, here is none Chinese introduction.

## Possible Solution

1, here is a Chinese Application Introduction for reference， the Chinese keywords can help user searching，and get more 
exposure opportunities in huawei app store.
wolvic 是一款安全，并且开源（基于Firefox Reality Browser）的WebXR内容浏览工具，适配华为VR Glass，并且同时支持3dof手柄，手机手柄以及6dof手柄操控，该应用可在华为VR Glass中带来沉浸式的体验。
通过Wolvic，您可以访问WebXR内容，包括VR视频，图片，以及基于WebXR标准的各种WebXR游戏应用等内容。
更多信息，请访问https://www.wolvic.com

2、version update 1.3.1 ，here is a Chinese Introduction 
    1.  新增支持 Progressive Web Apps (PWAs)
    2.  支持导入自定义扩展插件，支持文件下载功能
    3.  优化了相关的性能，提升流畅性

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
OK makes sense. We'll modify it in the next release.

**Comment by svillar** [comment]
New version 1.3.2 will have the text localized in Chinese. Thanks for reporting!
