### ISSUE TITLE
https://raw-emotions.phoria.com.au only show "Enter VR" with the Oculus Browser

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#51]
## Context

Several web applications out there are filtering the contents based on the User Agent (UA). That has been a common (and very bad) practice in the 2D web that it's being exported to the immersive Web.

Ideally we should first try to reach the server side folks to ask them to use a different way to identify the browser. If we get no answer in a reasonable amount of time we could always fallback to using specific user agent quirks (or overrides in Wolvic terminology) to fake the server.

**Comment by svillar** [comment]
Note that similar to what happens in #12, we should claim being the Oculus Browser and also not include the `Android` part of the UA, otherwise many sites assume that we're a mobile device not capable of rendering the content.

**Comment by svillar** [comment]
Already contacted phoria.com.eu, let's see what they say.

**Comment by vanilla-plus** [comment]
Hey team! I'm one of the developers at PHORIA.

We're well aware of the strange UA policy implementation and were apprehensive about it at the time as well. It was a decision made under a very tight deadline - I believe it was related to distinguishing between Android mobile from memory. Android mobile devices were offering VR support but it was the very old Google Cardboard split-screen style. I'm positive there's a better way of handling it.

Now that we have some breathing room, we'd love to revisit the issue. Leave this one with us and we'll get to it hopefully soon.

**Comment by svillar** [comment]
> Hey team! I'm one of the developers at PHORIA.
> 
> We're well aware of the strange UA policy implementation and were apprehensive about it at the time as well. It was a decision made under a very tight deadline - I believe it was related to distinguishing between Android mobile from memory. Android mobile devices were offering VR support but it was the very old Google Cardboard split-screen style. I'm positive there's a better way of handling it.
> 
> Now that we have some breathing room, we'd love to revisit the issue. Leave this one with us and we'll get to it hopefully soon.

That's great to hear. I perfectly understand this kind of decisions taking on tight deadlines, sometimes things need to "just work" instead of being the best solution.

Humbly offering an advice, in general is better to look for specific features in JS than checking the UA that can be spoofed or being misleading as in this case.

**Comment by vanilla-plus** [comment]
Absolutely! This thread kicked off an internal discussion about that exact topic.

I checked in with the developer who wrote that part and apparently it was required for supporting the Facebook Browser. There was simply no other way to navigate it it seems. Nonetheless, we'll revisit this shortly and provide that support as best we can.

Thanks for bringing it to our attention!

**Comment by svillar** [comment]
This will work in Wolvic in the next release. We're still hoping for a fix on server side though.
