### ISSUE TITLE
[PicoXR] Use GL_COMPRESSED_RGB8_ETC2 for skybox textures

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#522]
PicoOS 5.4 brings support for `GL_COMPRESSED_RGB8_ETC2`. We can get rid of the code using PNG textures and use the compressed format as we do for the other platforms.

**Comment by svillar** [comment]
Related to this, giving all the issues in <5.4 versions, we should consider dropping support for those versions since those issues affect core parts of the application, I don't think it makes sense for example to distribute both textures in future releases just in case users don't want to upgrade to 5.4 or later.

**Comment by CoreaKorea** [comment]
Hello, I'm a Pico 4 user.

When can I use Wolvic?

Or is there another way?

It's so frustrating that it hasn't worked since the 5.4.0 update.

**Comment by svillar** [comment]
> Hello, I'm a Pico 4 user.
> 
> When can I use Wolvic?
> 
> Or is there another way?
> 
> It's so frustrating that it hasn't worked since the 5.4.0 update.

We'll release 1.3.2 addressing the issues in Pico 5.4 really soon. We're sorry for the inconveniences but it was not Wolvic's fault really, but the update that broke previous behaviour of the system without prior notice.

**Comment by user080975** [comment]
Is there an approximate date when the new fix might be released for Pico?

**Comment by svillar** [comment]
> Is there an approximate date when the new fix might be released for Pico?

I've just released it :smile:

**Comment by user080975** [comment]
Thank you! Is there a way to check console or debug my site in Wolvic browser from desktop or someway?

**Comment by svillar** [comment]
> Thank you! Is there a way to check console or debug my site in Wolvic browser from desktop or someway?

Yes, Wolvic supports [remote debugging](https://github.com/Igalia/wolvic/wiki/Debugging).

That said, please leave this issue for the actual problem described in the first comment, let's not hijack it. Thanks!
