### ISSUE TITLE
Oculus Go APK Please

### ISSUE THREAD

**Issue by TA-001** [Igalia/wolvic#53]
## Hardware

Oculus Go 
## Steps to Reproduce

1. Not reporting a bug but rather asking for help in please continuing to support the Oculus Go and preventing it becoming prematurely obsolete hardware. The oculus store does not update the store for oculus go leaving us locked in a situation where we have software that becomes outdated and no longer functions - with changes in servers used - be it amazone prime video, or other. 
2. Please allow at least it to have a decent browser without having to get rid of the paid for software by making it a blank android version. I side loaded Firefox reality 2020 andit works but has bugs such as constantly reloading the environmental fle when changing it, and still no voice recognition. Please make available APKs which can be sideloaded by SideQuest for the Oculus Go without having to log into a store and keep good hardware functioning for longer, avoiding unnecessary obsolescene and environmental waste as well as a lot of unnecessary expense.
3.
4.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by TA-001** [comment]
"By July 2019, the Go was estimated to have sold over two million units. On June 23, 2020, Facebook Technologies announced it would be ending the sales of the Oculus Go later that year and would not accept new Go apps or app updates into the Oculus Store after 4 December 2020."

**Comment by svillar** [comment]
Already mentioned in issue https://github.com/Igalia/wolvic/issues/38

**Comment by DraconicNEO** [comment]
> "By July 2019, the Go was estimated to have sold over two million units. On June 23, 2020, Facebook Technologies announced it would be ending the sales of the Oculus Go later that year and would not accept new Go apps or app updates into the Oculus Store after 4 December 2020."

Can still be side-loaded and quite easily too since the Oculus Go has package installer accessible.

**Comment by BWC4WIFE** [comment]
> 
false -- see issue #38

**Comment by DraconicNEO** [comment]
> > 
> 
> false -- see issue #38

I point it out because the number one ~~argument~~ excuse Devs have against legacy platform support like this is storefront closure.

**Comment by TA-001** [comment]
I replied to the email but was not sure it would get back to you.
I think that the ability to sideload is reasonably well known about.

Programs such as sidequest make this easy.

Great hardware without software is useless.

Ongoing browser support is what keeps capable hardware usable.

The store issue is very sad, and facebook should allow new apps and updates. The store still works, but facebook do not allow updates on it.

I can sideload browsers such as opera but they do not use the whole screen and work as well as firefox reality does.

Firefox does work with Amazon Prime though you get blocky green videos at times.


I am not clear if you said there was an APK available for Wolvic that could be sideloaded and works. Please advise of a link. Else do I need to compile it, having added libraries etc. to it. If so can you advise of how to do this? If the software has changed due to extensive changes to Oculus Quest 2 OS, could you advise the last version of Wolvic that is or could be compatible?

**Comment by DraconicNEO** [comment]
> I replied to the email but was not sure it would get back to you. I think that the ability to sideload is reasonably well known about.
> 
> Programs such as sidequest make this easy.
> 
> Great hardware without software is useless.
> 
> Ongoing browser support is what keeps capable hardware usable.
> 
> The store issue is very sad, and facebook should allow new apps and updates. The store still works, but facebook do not allow updates on it.
> 
> I can sideload browsers such as opera but they do not use the whole screen and do not work as well as firefox reality does.
> 
> Firefox reality (last version)does work with Amazon Prime though you get blocky green videos at times. Voice recognition is also important in a VR headset without having ready access to a keyboard.
> 
> I am not clear if you said there was an APK available for Wolvic that could be sideloaded and works. Please advise of a link. Else do I need to compile it, having added libraries etc. to it. If so can you advise of how to do this? If the software has changed due to extensive changes to Oculus Quest 2 OS, could you advise the last version of Wolvic that is or could be compatible?

I never used side quest before, all I did was install a file manager after enabling the hidden unknown sources option in the settings (got there using a complicated process that involved a keyboard for the directional navigation due to certain menus not being VR compatible).

There is indeed an APK version of available (check releases page), however when I tested it it doesn't seem to work on Oculus go which is why I made #38 I have no idea if the developer has fixed said issue in the latest version (try it and see if it works for you).

I didn't attempt to change or recompile it so I'm not really sure about how I might go about fixing this issue myself.

As far as latest versions that might be compatible I'm not really sure but I don't think that I found a working one back when I tested, the existing one would need to be modified to work on the oculus go either by the main developer or by somebody else, I'm hoping that the main developer sees my issue and is able to fix it though.

**Comment by BWC4WIFE** [comment]
> > I replied to the email but was not sure it would get back to you. I think that the ability to sideload is reasonably well known about.
> > Programs such as sidequest make this easy.
> > Great hardware without software is useless.
> > Ongoing browser support is what keeps capable hardware usable.
> > The store issue is very sad, and facebook should allow new apps and updates. The store still works, but facebook do not allow updates on it.
> > I can sideload browsers such as opera but they do not use the whole screen and do not work as well as firefox reality does.
> > Firefox reality (last version)does work with Amazon Prime though you get blocky green videos at times. Voice recognition is also important in a VR headset without having ready access to a keyboard.
> > I am not clear if you said there was an APK available for Wolvic that could be sideloaded and works. Please advise of a link. Else do I need to compile it, having added libraries etc. to it. If so can you advise of how to do this? If the software has changed due to extensive changes to Oculus Quest 2 OS, could you advise the last version of Wolvic that is or could be compatible?
> 
> I never used side quest before, all I did was install a file manager after enabling the hidden unknown sources option in the settings (got there using a complicated process that involved a keyboard for the directional navigation due to certain menus not being VR compatible).
> 
> There is indeed an APK version of available (check releases page), however when I tested it it doesn't seem to work on Oculus go which is why I made #38 I have no idea if the developer has fixed said issue in the latest version (try it and see if it works for you).
> 
> I didn't attempt to change or recompile it so I'm not really sure about how I might go about fixing this issue myself.
> 
> As far as latest versions that might be compatible I'm not really sure but I don't think that I found a working one back when I tested, the existing one would need to be modified to work on the oculus go either by the main developer or by somebody else, I'm hoping that the main developer sees my issue and is able to fix it though.

no -- the issue persists; oculus insists that an update is needed.  Ive attempted to build it using oculusSDK as well as movile but cannot determine how to compile a funtiomal build.

**Comment by TA-001** [comment]
Thanks for replying. I had been hoping that 1 version of wolvic was compatible or easily made compatible. Let still hope, or hope a way of streaming high res from a pc via an ethernet adapter via usb or the like and using a remote desktop connection if forced. (Did try ethernet usb adapter, attached to the usb otg with power - but was not recognised).
