### ISSUE TITLE
3D SBS not working in curved mode

### ISSUE THREAD

**Issue by WiseSalamander** [Igalia/wolvic#545]
## Configuration

Wolvic version: 1.3.1 versionCode 72
Wolvic build ID: (not sure how to check this, but is the current version to download as of 3/11/2023)

Hardware: Oculus Quest 2 256gb

## Steps to Reproduce

1. browse to a youtube side by side 3d video (it happens the same with any other video source)
2. set up curved screen in options 
3. set full screen 
4. chose side by side 3D

## Current Behavior

Any kind of 3D video loaded in the video player when having the curved screen option on will not show in 3D(it does work when this the curved screen is off). 

## Expected Behavior

3D showing correctly in any video loaded in the player with the curved screen option on. 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Many thanks for the report, will investigate this
