### ISSUE TITLE
A simple way for CN users get full features  (enable toolbar)

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#547]
## Configuration

Wolvic version: 1.3.2
Wolvic build ID: 

Hardware: HUAWEI VR Glass 3dof & 6dof

## Steps to Reproduce

1.
2.
3.

## Current Behavior

For CN users, if they want get the a full version(URL toolbar, configurations etc) , the only way is download from  wolvic.com/dl , it is inconvenient.

## Expected Behavior

a simple way for CN users to get full features.

## Possible Solution

base on the wolvic of CN verison ,  the users can use the controller to enable/disable the toolbar, some suggestion:

1, for 3dof controller ,  the way to enable the toolbar. and the same way to disable it. 
- push down the triger & touchpad button together for 3 seconds  

2, for 6dof controller , the way to enable the toolbar. and the same way to disable it. 
- right controller: push down the   triger & A button  together for 3 seconds. 
or
- left controller : push down the triger & X button   together for 3 seconds.

if the user set it (enable or disable toolbars), this setting is recorded every time you start or reinstall.

For the phone controller(3dof) mode ,this function does not need to be considered.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Fixed now. To be released in 1.3.4
