### ISSUE TITLE
It cannot be controlled with a handle on the Pico neo3

### ISSUE THREAD

**Issue by wayne10086** [Igalia/wolvic#549]
## Configuration

Wolvic version: 1.3.2
Wolvic build ID: 

Hardware: pico neo3（5.4.4）

## Steps to Reproduce

1.It can be opened on pico neo3
2.It cannot be controlled with a handle on the Pico neo3
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Neo3 is not supported. As the release notes mention, we do support Pico4 and Pico4E. It should indeed run on other devices supporting OpenXR but we don't officially support them, meaning that things like input controllers might not work properly.
