### ISSUE TITLE
noapi clarification

### ISSUE THREAD

**Issue by ashiskumarnaik** [Igalia/wolvic#555]
I am a newbie open source enthusiast . I want to test using noapi (android device) . Tried to find suitable link but no dice. Can I get more context for using noapi and getting involved in development in general without headset :)
Apart from that is there some communication channel to discuss work especially for begginners. I am actually interested for Igalia coding experience .
Thanks

**Comment by svillar** [comment]
You basically have to select the noapi build variant in android studio and connect your android device to the computer you're developing in.

PS: this is the Wolvic project page. For anything related to Igalia's CE program refer to the [web page](https://www.igalia.com/coding-experience/) thanks.

**Comment by svillar** [comment]
Closing this
