### ISSUE TITLE
Stereo 180 Left to Right projection broken

### ISSUE THREAD

**Issue by lockemx** [Igalia/wolvic#562]
## Configuration

Wolvic version: 1.3.2 76
Wolvic build ID:  89731950 (AC 75.0.22)

Hardware: Quest 2 64GB on v50

## Steps to Reproduce

1. https://www.dailymotion.com/video/x2rc2uj
2. Choose Stereo 180 Left to Right (VR180) projection mode.
3. Compare to the first option of 3D Side by Side, which looks nice and works well (even though you can't zoom to it)

## Current Behavior
The broken VR180 mode will be flat (no depth) with same image in each eye. It will be stretched to a dome almost to the extent when there should be black there (with only half a dome of visible video).

## Expected Behavior
VR180 is displayed with depth. Left and right eye see different images.

## Possible Solution
Fix a regression from release 1.2, which was the last version to work properly in this mode. Possibly related: <https://github.com/Igalia/wolvic/pull/439>. On a side note, 1.2 also had an issue where the video would be grainy as if it was lower resolution than it was, or there were problems with the rendering initialization. You would have to reload the video several times until you bypassed the issue. I don't think this was related to buffering in a different quality at all.

**Comment by svillar** [comment]
Many thanks for the report. 

The 3D SBS option selected by Wolvic is the right one. I don't exactly understand what are you expecting from using stereo 180. For example, I encourage you to try the same video with the Meta browser, which result are you looking for?

**Comment by lockemx** [comment]
Sorry, I was in a rush to find a video and put a bad example. It should have been a VR180 video meant for dome projection in 180 degrees. It's hard to find one on the major video sites. I can tell you that the other mode I talked about is broken when it worked in version 1.2 and still does if I revert to that version. You are supposed to see a different image in each eye, and it's not supposed to be stretched so much. It's like you are zoomed in way too close to the edge of the dome and can't zoom out. I'll try looking for another video now.

**Comment by svillar** [comment]
> Sorry, I was in a rush to find a video and put a bad example. It should have been a VR180 video meant for dome projection in 180 degrees. It's hard to find one on the major video sites. I can tell you that the other mode I talked about is broken when it worked in version 1.2 and still does if I revert to that version. You are supposed to see a different image in each eye, and it's not supposed to be stretched so much. It's like you are zoomed in way too close to the edge of the dome and can't zoom out. I'll try looking for another video now.

BTW if you want to share some nsfw URL privately feel free to [contact us](info@igalia.com) directly

**Comment by svillar** [comment]
Gengle ping :smile:, we're really interested in fixing video issues but first we need to know what's exactly failing and where. Again contact us privately if you don't want to make explicit the sites you're trying.

**Comment by lockemx** [comment]
I sent an interesting video by email. I tested using an APK for version 1.2. That works on a SBS video like this that projects in VR180 or however you say it. Even though the 1080p setting is not even close to HD on this website, you can tell that the old version can display each eye differently, and it's not stretched. The newest versions can't do it, even though many other sites work well in OpenXR mode or whatever everyone moved to for better VR support. So, it's a problem of legacy videos not working, I suppose. I hope you can see the issue, and it's not just me because I was an avid user of some old sites that never upgraded how they display SBS videos for VR.

**Comment by svillar** [comment]
OK the fact that it worked in 1.2 makes sense. Starting in 1.3 Oculus build is based on OpenXR instead of in OculusVR. In the specific case of VR videos the handling is completely different in both backends. We had to fix 3D SBS some time ago, and now it looks like 180 left to right needs adjustments too. We'll look into that.

**Comment by svillar** [comment]
I think [this](https://www.youtube.com/watch?v=41-Izl-pLLc) is a sfw example that is not working as expected (360 rendering instead of 180)
