### ISSUE TITLE
VR180 YouTube Videos are not in 3D

### ISSUE THREAD

**Issue by spenme** [Igalia/wolvic#578]
## Configuration

Wolvic version: 1.1 (viveport)
Wolvic build ID: 059d7268 (AC 63.0.0)

Hardware:  HTC VIVE XR Elite

## Steps to Reproduce

1. Play any VR180 YouTube video. [Like this one](https://www.youtube.com/watch?v=1C16AT6vPrY). [Or this one](https://www.youtube.com/watch?v=py-kIZss75o).
2. Click through the projection modes.
3. These videos should be in 3D. Notice how there is no way to watch these videos with depth.

## Current Behavior

The standard 180 projection option in Wolvic allows VR180 YouTube videos to play in 180 degrees. That's great, but when switching to the 180 stereo options, Wolvic just splits the YouTube video in half rather than creating the desired 3D effect.

It seems like Wolvic is not obtaining the 3D stereo information from VR180 YouTube videos and is instead just using one image.

This may be a YouTube limitation or a problem exclusive to Wolvic 1.1 on viveport. I'm not sure.

## Expected Behavior

The VR180 stereo projection option should be able to play VR180 videos from YouTube (like the ones mentioned above) in stereo 3D.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for the report, this is a duplicate though off #562

**Comment by svillar** [comment]
Oh and by the way, those videos are standard videos, they aren't VR 180 videos, you can check that on any other browser/device (like Meta/Pico/....) and all of them render the video in 2D, they aren't using any special stereo/VR format, the title is just misleading.

**Comment by spenme** [comment]
The videos are in fact in 3D when viewed via the YouTube app in VR. [Here's a screenshot I took from my phone of the second video](https://imgur.com/a/yBPVJaW). Notice how the images being fed to each eye are unique. I've circled a part in the image where it's clear. 

That said, if other browsers are not displaying these videos in 3D, then that feature must be exclusive to the YouTube app. Oh well.

**Comment by svillar** [comment]
> The videos are in fact 3D (VR180) when viewed via the YouTube app in VR. [Here's a screenshot I took from my phone of the second video](https://imgur.com/a/yBPVJaW). Notice how the images being fed to each eye are unique. I've circled a part in the image where it's clear.
> 
> That said, if other browsers are not displaying these videos in 3D, then that feature must be exclusive to the YouTube app. Oh well.

Ah OK. Yeah, most likely YouTube is filtering by UserAgent and only sending the VR video to the native app.
