### ISSUE TITLE
Android support libraries upgrade broke some widgets

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#582]
It looks like PR #519 broke several widgets. The top bar widget used to close windows has been broken since then.

Also I've observed (not always) that the URL bar is also broken, in many executions it just renders the background, no text is displayed there.

**Comment by felipeerias** [comment]
The top bar widget is fixed by PR https://github.com/Igalia/wolvic/pull/584

However, the URL problem was introduced after the libraries were updated in PR https://github.com/Igalia/wolvic/pull/519

**Comment by svillar** [comment]
> The top bar widget is fixed by PR #584
Cool 
> However, the URL problem was introduced after the libraries were updated in PR #519
Can you bisect it?
