### ISSUE TITLE
Couldn't build the Wolvic from the source on virtual android emulator android studio

### ISSUE THREAD

**Issue by mhmdawnallah** [Igalia/wolvic#591]
## Configuration

Wolvic version: `Latest version in the main branch`
Wolvic build ID: `Latest version  in the main branch`

Hardware: `noapi (Pixel 2 API 30 virtual emulator on Android Studio)`
Operating System: `Ubuntu 22.04.2 LTS`

## Steps to Reproduce

1. Clone the latest version of wolves main branch
2. Open the project with android studio 
3. Let it finishes the gradle sync process 
4. Make sure the android emulator is open (in my case it is `Pixel 2 API 30 virtual android emulator`)
5. Go to the settings of the android emulator and enable `Developer Mode` then enable `User Debugging`
6. Run the app
7. You will get this warning: `Device supports x86, armeabi-v7a, armeabi, but APK only supports arm64-v8a on device Pixel 2 API 30`
8. You will get this error after some time of the gradle building process: `app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java:32: error: package com.huawei.hvr does not exist import com.huawei.hvr.LibUpdateClient;`

## Current Behavior

- Warning:
`Device supports x86, armeabi-v7a, armeabi, but APK only supports arm64-v8a on device Pixel 2 API 30`
- Error:
`app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java:32: error: package com.huawei.hvr does not exist import com.huawei.hvr.LibUpdateClient;`

## Expected Behavior

It should build the app successfully.

## Possible Solution

N/A

## Context

It's my first time with Wolvic and I wanna contribute to the open-source repository so the first step for me is to install it locally and play around with it.

## Error Logs and Stack Traces

<details open>
N/A

```
```

</details>

**Comment by kavi-kumaran** [comment]
> OK, we should not have to include hvr stuff in noapi build. Feel free to provide a patch for it, we would have limited time for that.

I am new to open source, I will give it a try to fix it.

**Comment by kavi-kumaran** [comment]
@svillar I believe @mhmdawnallah may have forgotten to select the 'noapi' build variant. I encountered the same issue when I forgot to choose the 'noapi' build variant, as by default Android Studio sets the build variant to 'hvr'. However, once I changed the build variant to 'noapi', the issue was resolved.

**Comment by mhmdawnallah** [comment]
Thanks, @kavi-kumaran for sharing your experience. Before closing this issue, I couldn't open the app on the Emulator because it gives me "Wolvic VR Browser(Dev) keeps stopping"?

**Comment by mhmdawnallah** [comment]
I've solved the issue. It's that my Android device don't support a location service which makes the app not starting I used [genymotion](https://www.genymotion.com/) instead.
