### ISSUE TITLE
WebXR Not Supported error when viewing WebXR content

### ISSUE THREAD

**Issue by mattvulcano** [Igalia/wolvic#593]
## Configuration

Wolvic version: 1.3.2
Wolvic build ID: WaveVR

Hardware: HTC Vive XR Elite

## Steps to Reproduce

1. Deploy Build via Android Studio
2. When in app, navigate to a website with WebXR content

## Current Behavior

A dialog box displays with the message 'WebXR Not Supported In Browser'

## Expected Behavior

WebXR content loads as expected.

## Context

With the version of Wolvic that HTC offers in their app store(build 1.1 I believe), all VR videos that are played in browser are suffering from the 'black screen/no video, only audio' issue, aside from like, Youtube videos. Seeing that there was a newer version available that fixed this issue, I tried to find a release that would work with my headset. 

After reading through the issues and seeing that HTC/Vive builds are not supported/maintained, I decided to try and build from source myself. After some issues I was able to build a local GeckoView repo at the current 'FIREFOX_RELEASE_xx' branch, then get Wolvic to build and deploy using the latest HTC Wave SDK 5.2.0, using my local GeckoView binaries. Everything in the browser seems to work fine, except when I go to websites that have WebXR content, I see the above error message. 

Is there something small that I am missing, or some step that I missed, that is causing this? I am not seeing any errors in Android Studio when debugging it. I also checked the settings to ensure that 'Enable WebXR Content' was toggled on, and that 'Enable DRM Content' was toggled on, just in case that was the issue.

I feel like I am very close to getting this to work, I just figured it would be faster to log an issue and ask instead of dig through the codebase myself. Thank you for taking the time to look at this.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
There are various reasons why you get that message:
* Not building the right geckoview, you should use the branch & repo mentioned in the README. It's critical to use the same protocol version in geckoview and in wolvic
* There are issues in the WaveSDK backend, if for some reason, Wolvic is not able to list the available VR devices whenever Gecko asks for them, then Gecko will understand that there are no VR devices attached, and thus disable WebXR content.

**Comment by mattvulcano** [comment]
Thanks for the reply! Currently I am building Wolvic from this repo: https://github.com/Igalia/wolvic.git, master branch. I am building GeckoView from this repo: https://github.com/Igalia/gecko-dev.git, using FIREFOX_103_0_2_RELEASE branch.

If those look right, I am guessing that maybe it is your second point, that it cannot find an available VR device. Perhaps because it was written for Vive Flow, and I am using the Vive XR Elite, something is different? I guess I have some investigation to do.

Any thoughts on what files/where in the codebase I should start to look into this?

**Comment by svillar** [comment]
> Thanks for the reply! Currently I am building Wolvic from this repo: https://github.com/Igalia/wolvic.git, master branch. I am building GeckoView from this repo: https://github.com/Igalia/gecko-dev.git, using FIREFOX_103_0_2_RELEASE branch.
> 
> If those look right, I am guessing that maybe it is your second point, that it cannot find an available VR device. Perhaps because it was written for Vive Flow, and I am using the Vive XR Elite, something is different? I guess I have some investigation to do.
> 
> Any thoughts on what files/where in the codebase I should start to look into this?

On the gecko side, you should take a look at `void VRManager::ProcessManagerState_Enumeration()` in particular check that after `PullState()` (which retrieves device info from Wolvic) `mEnumerationComplete` is true.

On the Wolvic side, check that `CompleteEnumeration()` is called before that `mEnumerationComplete`happens. If you're using the WaveVR backend then the `DeviceDelegateWaveVR` is the responsible of doing that. As mentioned we don't currently maintain that code so I don't know when or how it's doing that.
