### ISSUE TITLE
360º images wrongly follow the headset orientation

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#611]
## Configuration

Wolvic version:  1.3.3
Wolvic build ID:  84

Hardware: meta quest 2

## Steps to Reproduce

1. load the site https://www.360cities.net/
2.  Click on the "Enter VR" button in the top of the rendered image
3. Move the headset to explore the 360 image

## Current Behavior

The image is moved aligned with the headset.

## Expected Behavior

The image should be locked in one position, allowing the user to explore in a 360 angle along with the movement of the headset. 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
That's what happens whenever the site uses WebVR (deprecated) instead of WebXR. Could you check that?

In Wolvic we disabled WebVR on purpouse because we don't want to maintain a deprecated API

**Comment by javifernandez** [comment]
> That's what happens whenever the site uses WebVR (deprecated) instead of WebXR. Could you check that?
>

The site is using WebVR, indeed. 

So this should be a WONTFIX then ?  It's a pity because the site looks quite interesting:

https://www.360cities.net/about

The user has reported similar issues in these sites:

- https://www.airpano.com/
- https://edu.cospaces.io/Universe

**Comment by svillar** [comment]
> > That's what happens whenever the site uses WebVR (deprecated) instead of WebXR. Could you check that?
> 
> The site is using WebVR, indeed.
> 
> So this should be a WONTFIX then ? It's a pity because the site looks quite interesting:
> 
> https://www.360cities.net/about
> 
> The user has reported similar issues in these sites:
> 
> * https://www.airpano.com/
> * https://edu.cospaces.io/Universe

Yeah WebVR is not going to be supported, we had similar issues in the past for Chinese sites using WebVR as well.

**Comment by javifernandez** [comment]
Closed as WONTFIX then.
