### ISSUE TITLE
can wolvic support PC + vr ？

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#628]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
Short answer is no. Wolvic is designed to run on standalong AOSP (android based) devices. Anything different from that would require huge architectural changes.

That said Wolvic already run tethered on some devices like the Huawei Glasses or the Lenovo A3.
