### ISSUE TITLE
Hand tracking not supported for vive xr elite?

### ISSUE THREAD

**Issue by rainyear** [Igalia/wolvic#648]
`Wolvic VR Browser 1.3.2` installed from vive xr elite's app store, `versionCode 72`, hand tracking feature is not working.

**Comment by svillar** [comment]
First of all thank you for taking your time to report the issue.

That said I'm sorry but our team is not big and we cannot provide support for HTC devices at the moment. We basically prioritize the devices from our partners who are the ones supporting the development of the project.

All that we know is that HTC takes the Wolvic's code and releases it in the store. I think they're still using the WaveVR SDK. Our handtracking implementation was done using OpenXR, so unless they implement it using WaveVR I guess HTC users won't get it :disappointed:

**Comment by rainyear** [comment]
Thanks for the info.
