### ISSUE TITLE
Youtube Slow Script Error

### ISSUE THREAD

**Issue by ThatVRPerson** [Igalia/wolvic#65]
Slow Script Error

A web page is slowing down your browser (moz-extension://5427dfe7-ef62-49ca-aee3-5b4add9f6dfe/inject/index.js).  What would you like to do?

STOP IT or WAIT

## Configuration

Wolvic version: 0.9.4
Wolvic build ID: 2/14/2022 (Release Date)

Hardware: Oculus Quest 2 Software/Runtime v37

## Steps to Reproduce

1. Install all add-ons available (uBlock Origin (enable and update all non region lists), Privacy Badger, Dark Reader, HTTPS Everywhere, NoScript Security Suite, Privacy Possum)
2. Enter Private Browsing
3. Go to Youtube.com and starts to slow/get Slow Script Error
4.  Tried on both Desktop Mode and non-Desktop Mode

## Current Behavior

-Not smooth and website really slows down either add-ons are not optimized or something else is wrong

## Expected Behavior

-Youtube should load smoothly like it would on any other device

## Possible Solution

-One of the add-ons listed above is not optimized and causing errors

## Context

-Same issue on Firefox Reality.  Was trying to browse Youtube with non quest 2 browser to enjoy fully immersive VR180/360 videos.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by elima** [comment]
I was finally able to reproduce this, and the offending Add-on is [Dark Reader](https://darkreader.org/).

We need to dig a bit to see if there is something conflicting in Wolvic, otherwise blacklist the extension and contact the authors to troubleshoot the issue.

For now, please avoid the extension.

**Comment by svillar** [comment]
It's an addon issue, so let's close this
