### ISSUE TITLE
Use a different application name for HVR mainland China package

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#653]
The application name is specified in `app/src/main/res/values/non_L10n.xml`. For the case of hvr flavour for mainland china (i.e. `cn` flavour) the app must be named just `Wolvic` instead of `Wolvic VR Browser`.

So far we've been replacing that manually before generating the packages, but this should be automated.

**Comment by HollowMan6** [comment]
I think we can close this issue now since https://github.com/Igalia/wolvic/pull/741 has already been merged.
