### ISSUE TITLE
Target Android API level 32

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#654]
Got the following today when uploading Meta builds to the Store
```
NOTE: 
Meta Quest apps will soon be required to target Android API level 32. The AndroidManifest.xml
in this binary targets API level 31. Please upload a new build targeting Android API 32 or higher.
For more details, please refer to https://ocul.us/3RbwVQj
```
The link is wrong as it refers to Android API 29 but the rest of the message still applies.

We can try to upgrade the target for all the platforms instead of just Meta (except those which already have specific constraints).

**Comment by HollowMan6** [comment]
Close this issue as https://github.com/Igalia/wolvic/pull/820 has already been merged.
