### ISSUE TITLE
Unable to click using hand tracking if using only one hand

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#655]
## Configuration

I was only able to reproduce this in Meta Quest2, but I don't see any reason why this could not happen in other devices

## Steps to Reproduce

1. Launch Wolvic with the right controller
2. Leave the controller aside while the splash is shown
3. Browser window is shown and right hand is detected
4. Try to click anywhere

## Current Behavior

Hover and other events work fine, but clicking does not

## Expected Behavior

Clicking should work

## Possible Solution

Looks like it has to do with the fact that we're using just one controller (hand). Somehow the input is locked in the other one. Once both hands are detected it's possible to click again after some time.

**Comment by elima** [comment]
The root cause is that a squeeze action may get started by one hand and never stopped because the hand disappears from view, lost aim, or was changed by a controller (user picking up a controller). We just need to reset (stop) the action when we detect a hand going off.

I'm working on a fix.
