### ISSUE TITLE
Selecting text is awful

### ISSUE THREAD

**Issue by Emnolope** [Igalia/wolvic#659]
**Describe the solution you'd like**
Go in the app. Try editing some text. Try deleting a sentence. Try pasting one.

**Describe alternatives you've considered**
Grip button based select
Both cotrollers, start and end.

**Comment by svillar** [comment]
So I've recorded a short clip in which I:
1. select a word but long pressing
2. easily enlarge shrink the selection using the classic android controls
3. got a popup automatically shown offering several actions. I copy
4. paste the copied text via a long press, and a click on paste button

What exactly do you find awful? I think the experience is pretty good

https://github.com/Igalia/wolvic/assets/1826122/c1a5dcf1-bc0a-4a31-95fd-432e025dd6f5

**Comment by svillar** [comment]
I'll leave this open for another week. After that I'll close it due to lack of feedback

**Comment by svillar** [comment]
OK, no more input from reporter in more than a month. Let's close this
