### ISSUE TITLE
Custom Animated or more user friendly environments

### ISSUE THREAD

**Issue by ThatVRPerson** [Igalia/wolvic#66]
**Is your feature request related to a problem? Please describe.**
A working guide (or easy to use video) on how to create and load custom environments. Even better if they could be animated to allow for a more immersive experience and easily installed within the browser.

**Describe the solution you'd like**
Up to date and user friendly way of creating and importing custom environments. Kudos if the environments can be animated instead of static. Or a central way (similar to installing add-ons) to try different skins and environments without custom loading.

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
Wolvic supports custom override environments as Firefox Reality used to. We've added [some documentation](https://github.com/Igalia/wolvic/wiki/Environments) in our wiki.
