### ISSUE TITLE
 Leak of surface when exiting VR mode

### ISSUE THREAD

**Issue by mshin-wolvic** [Igalia/wolvic#662]
## Steps to Reproduce
1. Enter an immersive VR of WebXR
2. Take off the headset and wait a few seconds/or a few minutes until the device status is changed to suspend

## Current Behavior
When the VR device status is changed to suspend, we force exit VR mode.
The current sequence is `StopPresenting` is called first and then, `CancelFrame` is called later.
The problem is the surface is added to the map again in `CancelFrame` after `m.surfaceMap` is clear, and
it keeps the last surface object.

```
ExternalBlitter::StopPresenting() {
  ...
  m.surfaceMap.clear()
}

ExternalBlitter::CancelFrame() {
  ...
  m.surfaceMap[aSurfaceHandle] = surface;
  ...
}
```

**Comment by svillar** [comment]
Great catch!

**Comment by HollowMan6** [comment]
I think this issue should have already been fixed. Don't see the CancelFrame() called after StopPresenting() is called now: https://github.com/Igalia/wolvic/blob/02eac16ec0ee2aa331f199c0ca895b786d22dbe8/app/src/main/cpp/BrowserWorld.cpp#L298-L311
