### ISSUE TITLE
Persistent setting for the passthrough mode

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#666]
**Is your feature request related to a problem? Please describe.**
In Wolvic 1.3.4 the passthrough in switched on / off from the hamburger menu in the navigation bar. The menu item shows the mode the user want the app to change to. Wolvic is always launched with the passthrough switched off, independently of its last state.

**Describe the solution you'd like**
Define a persistent setting where to store the current state of the passthrough mode. The menu item used to handle will take its value from this settings.

**Comment by svillar** [comment]
Well I am not sure if we need to store that in settings unless we want to make it persistent. My main concern was that it does not seem to be placed where it should. If you think it should become a setting that users could modify I'd be OK but that was not my point.

**Comment by javifernandez** [comment]
> Well I am not sure if we need to store that in settings unless we want to make it persistent. My main concern was that it does not seem to be placed where it should. If you think it should become a setting that users could modify I'd be OK but that was not my point.

you're right, indeed. Although I think this issue is still worth to be pursued in the future, I've filed #668 to address the specific issue you mentioned regarding the place where the passthrough state is being handled.

**Comment by HollowMan6** [comment]
@javifernandez Do you still think we need a setting option for this? I can help with this issue. I think we of course can put an option in the "Environment" section of the Settings, with a switch such as `Use passthrough mode when Wolvic starts`. Wolvic will be launched with passthrough on when that setting is on.

**Comment by javifernandez** [comment]
> @javifernandez Do you still think we need a setting option for this? I can help with this issue. I think we of course can put an option in the "Environment" section of the Settings, with a switch such as `Use passthrough mode when Wolvic starts`. Wolvic will be launched with passthrough on when that setting is on.

YEah, I think it's still worth pursuing. We have request from some devices to change the default so Wolvic starts with passthrough enabled. This change will go on that direction, so that even if the default is not aligned with the device's characteristic, users may have an option to preserve their preference.
