### ISSUE TITLE
Couldn't install wolvic in Pico 4 Pro

### ISSUE THREAD

**Issue by lengmoXXL** [Igalia/wolvic#673]
## Configuration

Wolvic version: v1.3.4
Wolvic build ID: 

Hardware: Pico 4 Pro

## Steps to Reproduce

1. download apk https://github.com/Igalia/wolvic/releases/download/v1.3.4/Wolvic-picoxr-arm64-world-gecko-generic-release.apk
2. install it in pico 4 pro

## Current Behavior

![image](https://github.com/Igalia/wolvic/assets/19929075/2f773a65-4e6b-4a88-bba2-1ddd22c0cf18)
couldn't install

## Possible Solution

install succeeded

## Context

Pico OS Version: 5.5.0
Developer Mode already opened

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. I guess you mean the Pico 4E right?

Note that Wolvic is already in the bussiness Store of Pico so you can download it directly from the store.

**Comment by lengmoXXL** [comment]
Maybe no, it seems that Pico 4 Pro can only be found in https://www.picoxr.com/cn and Wolves can not found in the store, I'm not sure there exist some difference between with Pico 4E, if the problem also exist in Pico 4E, I can try it again later. Thank you for your reply.

**Comment by svillar** [comment]
> Maybe no, it seems that Pico 4 Pro can only be found in https://www.picoxr.com/cn and Wolves can not found in the store, I'm not sure there exist some difference between with Pico 4E, if the problem also exist in Pico 4E, I can try it again later. Thank you for your reply.

BTW are you able to the the logcat of the device while installing the application? It might give us some clues

**Comment by lengmoXXL** [comment]
```
2023-05-20 13:22:22.835  1213-1515  PeroptWhiteListParser   system_server                        W  In packageWhiteList: updateAppInfo com.igalia.wolvic
2023-05-20 13:22:23.026  1213-1515  PackageManager          system_server                        W  we get store list to check package:com.igalia.wolvic
2023-05-20 13:22:23.027  1213-1515  PackageManager          system_server                        W  we notifyPackageInstallResult examine_install_app:packagename:com.igalia.wolvic;install_from:nullcom.pvr.tobservice,uid:1000;is_developer_mode:0;is_within_list:1;is_same_signature:0;is_new_applist:1
2023-05-20 13:22:23.027  1213-1515  PackageManager          system_server                        W  we notifyPackageInstallResult install_app_result:packagename:com.igalia.wolvic;install_from:null;result:-116;fail_reason:package sign verity failed
2023-05-20 13:22:25.654  4259-4259  InstallFailed           com.android.packageinstaller         I  Finished installing com.igalia.wolvic
```

**Comment by svillar** [comment]
I see, do you have any previous version of Wolvic installed?

**Comment by lengmoXXL** [comment]
No, I have the same problem since version 1.3.

**Comment by stu-Jun** [comment]
After enabling developer mode, Pico 4 Pro can install Wolvic, but after entering, I have no way to operate with the handle or in any way.

**Comment by svillar** [comment]
> After enabling developer mode, Pico 4 Pro can install Wolvic, but after entering, I have no way to operate with the handle or in any way.

That's because we only have support for the Pico4 and 4E. Wolvic does not recognize the device and thus cannot render the appropriate controllers. Good news is that it should be easy to fix. Could you please connect the device to a linux machine and execute the following command:
`$ lsusb`

It should output lines like:
`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`

So the part I'm interested in is the one after `ID`, in the example above `1d6b:0003` because those are the vendor and model Ids that we need.

**Comment by lengmoXXL** [comment]
`Bus 020 Device 010: ID 2d40:00b7 2d40 PICO 4 Pro  Serial: ****`

I got it from executing `lsusb` from Mac.

**Comment by svillar** [comment]
One last thing, please paste the result of the following command when the Pico4 Pro is connected to the computer
`$ adb shell getprop | grep ro.product`

**Comment by lengmoXXL** [comment]
```
lizhiyuan@dev wolvic % /Users/lizhiyuan/Library/Android/sdk/platform-tools/adb shell getprop | grep ro.product
[ro.product.board]: [kona]
[ro.product.brand]: [Pico]
[ro.product.build.date]: [Fri May 19 06:28:29 CST 2023]
[ro.product.build.date.utc]: [1684448909]
[ro.product.build.fingerprint]: [Pico/Phoenix/PICOA8110:10/5.6.0/smartcm.1684448909:user/dev-keys]
[ro.product.build.id]: [5.6.0]
[ro.product.build.tags]: [dev-keys]
[ro.product.build.type]: [user]
[ro.product.build.version.incremental]: [5.6.0]
[ro.product.build.version.release]: [10]
[ro.product.build.version.sdk]: [29]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [PICOA8110]
[ro.product.first_api_level]: [29]
[ro.product.locale]: [zh-CN]
[ro.product.manufacturer]: [Pico]
[ro.product.model]: [A8110]
[ro.product.name]: [Phoenix]
[ro.product.odm.brand]: [Pico]
[ro.product.odm.device]: [PICOA8110]
[ro.product.odm.manufacturer]: [Pico]
[ro.product.odm.model]: [A8110]
[ro.product.odm.name]: [Phoenix]
[ro.product.product.brand]: [Pico]
[ro.product.product.device]: [PICOA8110]
[ro.product.product.manufacturer]: [Pico]
[ro.product.product.model]: [A8110]
[ro.product.product.name]: [Phoenix]
[ro.product.property_source_order]: [odm,vendor,product,product_services,system]
[ro.product.system.brand]: [Pico]
[ro.product.system.device]: [PICOA8110]
[ro.product.system.manufacturer]: [Pico]
[ro.product.system.model]: [A8110]
[ro.product.system.name]: [Phoenix]
[ro.product.vendor.brand]: [Pico]
[ro.product.vendor.device]: [PICOA8110]
[ro.product.vendor.manufacturer]: [Pico]
[ro.product.vendor.model]: [A8110]
[ro.product.vendor.name]: [Phoenix]
```

I can see that it works for 1.4, thank you very much.
