### ISSUE TITLE
Controller buttons do not click when only one controller on

### ISSUE THREAD

**Issue by MolotovCherry** [Igalia/wolvic#685]
## Configuration

Wolvic version: 1.3.4 (88)
Wolvic build ID: ff20e65b (AC 75.0.22)

Hardware: Oculus Quest 2, latest stable update v53 (android 12)

## Steps to Reproduce

Not sure if this is related to hand tracking mode, or when only one controller is on, but anyways

1. Turn both `hand tracking` and `auto switch from controllers to hands` on (I have `mid` sensitivity)
2. Open Wolvic
3. If only one controller registers on Oculus, then clicking won't work (though scrolling with joystick works). You have to make sure both controllers are waked in order to click. You can do only one controller a variety of ways, like double tapping to turn into hand only mode, and waking only one controller.

## Current Behavior
Clicking any button does not register anywhere in the whole UI (not just page)

As you can see in the video below, when only one controller is showing, I am clicking everything, but nothing clicks, but it suddenly works when the second controller is registered

https://github.com/Igalia/wolvic/assets/13651622/e8fee379-b14f-499f-bf7b-79bd2ca0d012

## Expected Behavior
Clicking actually clicks

## Possible Solution
Disable automatic hand switching

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for reporting. I think this is a dup of #655  ?
