### ISSUE TITLE
Weird black hand glitch on floor

### ISSUE THREAD

**Issue by MolotovCherry** [Igalia/wolvic#686]
## Configuration

Wolvic version: 1.3.4 (88)
Wolvic build ID: ff20e65b (AC 75.0.22)

Hardware: Oculus Quest 2, latest stable update v53 (android 12)

## Steps to Reproduce

1. Turn on passthrough with double tap feature in settings
2. Turn on hand tracking (and probably auto controller/hand switching)
3. Open Wolvic
4. Double tap side of headset to turn on passthrough and watch for black hand to glitch into view. Mine always appears on the floor in the same area

## Current Behavior
I see a black hand on the ground which glitches (flashes) into view sometimes. This only happens when wolvic is open.

## Expected Behavior
No hand or black item glitching in view

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by MolotovCherry** [comment]
Update: It seems it occurs when the oculus menu is open as well, and doesn't only happen in passthrough mode

**Comment by MolotovCherry** [comment]
This may possibly be a bug with the quest 2 update. At this time, I was on v54. I think I might have seen this apart from this app once. (But it still seemed consistent when using this app, perhaps I hadn't really noticed it before)

**Comment by javifernandez** [comment]
> This may possibly be a bug with the quest 2 update itself. At this time, I was on v54. I think I might have seen this apart from this app once. (But it still seemed consistent when using this app, perhaps I hadn't really noticed it before)

Thanks for the update. Could you please try to reproduce the issue in the last release 1.4.1 ? 

BR

**Comment by MolotovCherry** [comment]
This is a system bug. I've seen it outside of the app as well. This report can be closed

**Comment by MolotovCherry** [comment]
After more testing/experience, I see this is just a plain system bug, since it also happens independently from the app. I doubt that just the act of having wolvic installed would cause it (though I don't want to uninstall it to test since I have my data on wolvic). This report can be closed
