### ISSUE TITLE
Broken Folder Name

### ISSUE THREAD

**Issue by bittin** [Igalia/wolvic#71]
https://github.com/Igalia/wolvic/blob/main/app/src/main/res/values-sv-rSE/strings.xml

The Swedish Translation/Country Code is sv-SE should not be an extra r there if you remove it, the Swedish translation will start working again just fyi 

also this Wiki page: https://github.com/MozillaReality/FirefoxReality/wiki/Localization 
and some more places also have it wrong

**Comment by svillar** [comment]
Many thanks for reporting. I'll fix it straight away.

WRT the wiki page, that belongs to Mozilla, so not much we could do 😉️

**Comment by svillar** [comment]
OK, I should not reply without carefully reading the report :). That extra "r" you mention means region and is kind of a convention for android applications/Android Studio for specifying the specific region of a given language, for example for english you could have en-rUS and en-rGB.

I've just tried with the released 0.9.5 and the swedish translation works fine. Please reopen if you have further issues.

**Comment by bittin** [comment]
Swedish translation bumped up to 99%
