### ISSUE TITLE
Too much restart needed to restablish unstable connection

### ISSUE THREAD

**Issue by Emnolope** [Igalia/wolvic#712]
Wolvic 1.3.4 vc 88 Quest 2 v53

I'm using my janky ass internet connection with pdanet on android, even uses a manual proxy config. Anyway the signal is awful and the Internet dies completely when the headset is turned off.

When the headset standsby and turns on again, the quest 2 os is able to connect back to the Internet, but wolvic needs to be restarted to reconnect. i thnk this also happens with ustable wifi too.

**Comment by svillar** [comment]
We do check the connection status, among other things to show the wifi signal icon in the navigation bar. Anyway we'll check what happens. Thanks for reporting.

**Comment by HollowMan6** [comment]
This issue may be somehow related to #964, Not sure how it works now after #966 is merged.

**Comment by svillar** [comment]
> This issue may be somehow related to #964, Not sure how it works now after #966 is merged.

Yeah, I was actually never able to reproduce it. So let's close this. Please reopen if you still experience it.
