### ISSUE TITLE
Youtube Captions

### ISSUE THREAD

**Issue by GXboy12345** [Igalia/wolvic#717]
## Configuration

Wolvic version: 1.3.4
Wolvic build ID: 88?
Hardware: Quest 2, V...0659

## Steps to Reproduce
Watch any YouTube video w/ captioning on
## Current Behavior
Subtitles do not show at all
## Expected Behavior
Captions should be visible
## Error Logs and Stack Traces

```
```

</details>

**Comment by svillar** [comment]
Looks like the Gecko version we use doesn't support them. Will check later.

**Comment by HollowMan6** [comment]
Interestingly, looks like the Youtube captions are still not working even if we use Gecko 116.0.3 here https://github.com/Igalia/wolvic/pull/917

**Comment by HollowMan6** [comment]
> I would assume this is related to https://github.com/Igalia/wolvic/tree/main/app/src/main/assets/extensions/fxr_youtube

Can confirm that this extension caused the issue, as the Youtube caption works well when we have the extension disabled.
