### ISSUE TITLE
💡 A launch/kiosk mode that better allow WebXR PWAs to compite with Natives APPs

### ISSUE THREAD

**Issue by LAGENCECREE** [Igalia/wolvic#735]
### Is your feature request related to a problem? Please describe.

Probably due to the high cost of headsets, I observe that **the common business reality for VR app developers is to create applications that will be used on organizations headsets**. These headsets are purchased by organizations to offer immersive experiences to their own audience. They are usually made available at trade shows, arcade rooms, or enterprises, and are used by a significant number of end-users who take turns using just one application or game.

**In this field, webXR is a great challenger :**
-⚡**instant preview for collaborators and customers during the developpement**,  
-🚀 **updates online version in seconds **, 
-🚀**deliver fast on an url without stores approval** 
-💿**offline capacity with pwa**
-⭐**3D render great if you work with great 3d makers..(because is less an engine thing than people think)**

Current VR Browsers are doing well. However, **there are a couple of issues:**

- **End users have to click on the "Enter VR" button**, unfortunately sometimes we don't want to rely on hand controllers or hand tracking, some projects are 3DOF only.
- End users can navigate outside the application using the Oculus button and access undesirable parts of the operating system.

### Describe the solution you'd like

Although I'm not a lower-level developer, it would be revolutionary if we could achieve the following with Wolwic:

1 - Provide a way to open an XR session programmatically without the need for user interaction (similar to the --disable-gesture-requirement-for-presentation flag in Chromium).
2- Implement a more closed kiosk mode that prevents users from exiting the experience unless they know the proper method and **the password**.
3 - Enable the ability to launch the kiosk mode automatically at system startup.

With the following command for example:

`adb shell am start -a android.intent.action.MAIN -d "wolvic://com.igalia.wolvic/\?kiosk=true\&url=webxrexperience.com\&exitpassword=thepassword\&emailrecovery=contact@admin.com\&usergestureneeded=false\&starton=boot" com.igalia.wolvic.metastore/com.igalia.wolvic.VRBrowserActivity`

I hope that my feedback will be helpful and all or some of the points mentioned relevants. 
As a webXR developer and ambassador, we need projects like Wolwic to continue making WebXR a reality!

### Describe alternatives you've considered
Native apps like Unreal and Unity...
or build an apk embedding webapp and xr browser -> overkilling, i want to rely on a good and existing browser, like Wolwic

### Additional context

Example of scenario:

- There is a website called "https://thexrgame.com/" that is developed exclusively for webXR.
- This website is made available on an arcade room on an Oculus Quest 2,  for a large number of visitors/players.
- "https://thexrgame.com/" should be launched at boot time of the device or through an APK (by opening the "wolvic://" link).
- Lauching process of the webapp invoke "enter vr' automaticaly 
- The player cannot access anything else outside.
- Special users have the option to exit the experience by clicking on a 🔓 icon and entering a password.

**Comment by svillar** [comment]
Hi @LAGENCECREE thank you very much for your input, it's really valuable. It does actually align with the interests of some potential partners that are interested in similar use cases. Let's see if we get the required funding to prioritize this work which seems interesting.

> ### Describe the solution you'd like
> Although I'm not a lower-level developer, it would be revolutionary if we could achieve the following with Wolwic:
> 
> 1 - Provide a way to open an XR session programmatically without the need for user interaction (similar to the --disable-gesture-requirement-for-presentation flag in Chromium). 

The flag in chromium, AFAIK just avoids showing the confirmation dialog to enter WebXR. You still have to click on the "Enter VR" button or whatever the app specifies, which as you know it's different for every single WebXR app as this is not standarized. That said we have ideas related to programatically issuing click commands on certain coordinates to avoid users having to click those buttons

> 2- Implement a more closed kiosk mode that prevents users from exiting the experience unless they know the proper method and **the password**. 

This is interesting, we'll evaluate it.

> 3 - Enable the ability to launch the kiosk mode automatically at system startup.

You mean to start Wolvic in kiosk mode at startup? I am not an Android expert but I have my doubts that this could be possible.

**Comment by LAGENCECREE** [comment]
thanks for your interest !

i will follow any progress :)

> 3 - Enable the ability to launch the kiosk mode automatically at system startup.
yes, it seems doable at less on non rooted android phones (Macrodroid app do that), but im not an android dev expert too.

**Comment by svillar** [comment]
Closing in favour of #1279. I know this was reported first but this is already buried in the pile, so a more recent issue is likely going to drag more attention
