### ISSUE TITLE
[Start Page] Link to Jumpy Balls is broken

### ISSUE THREAD

**Issue by msub2** [Igalia/wolvic#736]
Like the Hello WebXR experience, Jumpy Balls used to be hosted on the mixedreality.mozilla.org domain, which unfortunately since mid-January of this year now just redirects to the Hubs homepage. I propose updating the Jumpy Balls URL to point to my rehost at https://msub2.github.io/jumpy-balls/, as it's apparent that bringing the original domain back is not a priority on Mozilla's side. This link is also what's currently used for the Meta NTP.

**Comment by svillar** [comment]
Hi @msub2 thanks for the heads up. We'll fix that really soon

**Comment by bkardell** [comment]
Fixed
