### ISSUE TITLE
Controllers and hands no longer appear on the Quest 1 since v1.4

### ISSUE THREAD

**Issue by MikeRatcliffe** [Igalia/wolvic#738]
Controllers and hands no longer appear on the Quest 1 since the 1.4 update so there is no way to interact with the app, so it's completely unusable.

I originally posted this issue as a review comment:

> Controllers and hands no longer appear on the Quest 1 since the v1.4 update, so the app is now unusable... such a shame because I used it often.

To which you responded:

> We're sorry to hear that. Unfortunatelly Quest 1 has not and is not officially supported so we do not include it in our QA process. That said, please send us an email to info@wolvic.com with the result of the following command if possible `adb shell getprop ro.product.vendor.model`.

Which is interesting because according to your oculus store entry, the Quest 1 **is** supported, so it should surely be included in your QA process:

<img width="544" alt="Quest 1 is supported" src="https://github.com/Igalia/wolvic/assets/116941/a4337e6c-5661-4741-a065-149abd72ba86">

## Configuration
Wolvic version: 1.4
Wolvic build ID: No way to interact so no build info available

Hardware:  Quest

```sh
adb shell getprop ro.product.vendor.model
Quest
```

## Steps to Reproduce
1. Install Wolvic v1.4 on the Quest 1.
2. Open Wolvic.

## Current Behavior
Wolvic opens, but there are no controllers or hands rendered, so there is no way to interact with the app.

## Expected Behavior
Hands or Controllers should be rendered so that the user can interact with the app.

## Context
Wolvic v1.4 was rolled out a couple of days ago, so this affects all Quest 1 users.

```
```

</details>

**Comment by Shar-Ke** [comment]
Same issue Quest 1. Update Volvic 1.4 and lost controllers in app. Hand-tracking does not render either. I am a low level user ...all I know to try is to un/reinstall and restart etc.
Hopefully it can be QA supported as I've used Volvic since FF traded over and am a huge fan! Would be a shame to lose it...nothing else compares to the functionality!!

**Comment by svillar** [comment]
Mind trying the update? If that works for you it'd be awesome if you could reconsider your review in the store :)

**Comment by svillar** [comment]
> > Would you be able to sideload an APK package with Quest1 support if I generate it?
> 
> If you can then that would be great, thanks for the fix!

It's already in the store, should be enough with upgrading

> I'd generate it myself but it looks like the third-party repo is private :/

It's private because it's software (SDKs) under EULAs so we cannot distribute it, but nothing secret is there

**Comment by MikeRatcliffe** [comment]
> It's already in the store, should be enough with upgrading

Works perfectly, thx.

**Comment by Shar-Ke** [comment]
@svillar ....sorry to interject here ...Thanks for the update!! Very pleased to see access to Wolvic restored. Seems to be working excellent as before! As for the focus on Quest2, unfortunately I am not able to upgrade do to the expense. Entry into VR for me through Quest1 was an indulgence, so maybe in the future I will be able to move further but the cost is prohibitive for some people. Anyway, I see I am way out of my depth on GitHub but wanted to say thanks!!
