### ISSUE TITLE
[Question] Where can I get the APK for ThinkReality A3 and Lynx-R1?

### ISSUE THREAD

**Issue by drumath2237** [Igalia/wolvic#745]
Hello.

According to the release notes, v1.4 supports some new devices like ThinkReality A3 and Lynx-R1.
But I cannot find APKs for these devices in the [release page](https://github.com/Igalia/wolvic/releases/tag/v1.4).
So, I want to ask you where to get these.

Thank you!

**Comment by svillar** [comment]
We're running some legal checks first. Stay tuned!

**Comment by svillar** [comment]
Also we didn't want to release those packages until we have a good hand tracking implementation for them. With the latest additions like #743 or #755 we're closer than ever.

**Comment by drumath2237** [comment]
Thank you so much. I understood the intention of hand tracking support.
To be honest, I tried APK for ThinkReality A3 before it deleted, and I found it very difficult to interact with web pages.
I'm looking forward to a better resolution and experience with improved hand tracking!

**Comment by svillar** [comment]
Will likely be available in 1.4.2

**Comment by drumath2237** [comment]
@svillar 
Hi 👋 
Is there any update?
Now I can't see the binaries on the 1.4.2 release page.

**Comment by svillar** [comment]
> @svillar Hi 👋 Is there any update? Now I can't see the binaries on the 1.4.2 release page.

We won't be distributing them at least in the short term. But you can always create them from sources. Sorry for the inconveniences.
