### ISSUE TITLE
[Bug] Issues with hand tracking input emulation on ThinkReality A3

### ISSUE THREAD

**Issue by Srile** [Igalia/wolvic#747]
Hello, first time contributor. Love what you guys are building here. I had access to a ThinkReality A3 and wanted to report on some of my findings:

## Configuration

Wolvic version:  1.4.1
Wolvic build ID: 01509654 (AC 75.0.22)

Hardware: ThinkReality A3

## Steps to Reproduce
1. You can test a current state over on https://sprayspace.art/wolvic
2. It works, but the input emulation (hand tracking is disabled in the project) for WebXR is broken in the ways mentioned below, the link above contains fixes to work around the issues in the emulation.
3. Compare behavior to https://sprayspace.art/app (This works with other hand tracking implementations in other browsers without issue)

## Current Behavior
1. The app reports `xrPose.emulatedPosition` to be true.
2. `inputSouce.gamepad.buttons[0].value` is always set to `1`, no matter if I release the select button or not. 

## Expected Behavior
1. `xrPose.emulatedPosition` is supposed to be false for 6-DoF inputs, which is the case here as the position of the hand is transmitted correctly. This was causing issues with the code I had specifically written for 3-DoF systems in the previous version. (see: https://developer.mozilla.org/en-US/docs/Web/API/XRPose/emulatedPosition)
2. `inputSouce.gamepad.buttons[0].value` should be set to `0` when the user ends the `select` gesture.

```
```

**Comment by elima** [comment]
Hi Srile, thanks for the detailed report!

Yes, while Wolvic doesn't have hand-tracking support in WebXR yet, we do expose controllers to WebXR when on hand-tracking mode as a gap-filling strategy. This support is a bit quirky and meant to change soon as we transition to a different web-engine that does support WebXR hand-tracking APIs.

That said, I will look into the issues you mention and see if we can easily fix those for the short term.

**Comment by svillar** [comment]
The issue with the gamepad primary action was fixed in #941
