### ISSUE TITLE
Support to browse web in vr for cardboard on Android mobile

### ISSUE THREAD

**Issue by vinod-angari** [Igalia/wolvic#758]
I am looking for browser to browse web in VR in cardboard using Android mobile.

I came across Wolvic, however on Android it will run in non-VR mode.

I found an alternative, Gizmo VR Virtual Reality Videos. It is capable of browsing web in VR with the help of cardboard on Android.
Play store link: https://play.google.com/store/apps/details?id=com.GizmoVR.Virtual.Reality.Videos

Is there way you can add support for VR mode on Android?

**Comment by svillar** [comment]
It isn't in our plans, unfortunately, it'll be quite some work and our current team cannot assume that.

**Comment by vinod-angari** [comment]
Thanks for your response! Is there a reference you can point me to get started and learn more about how to do it for Android (Using Wolvic as it's base if possible)?
