### ISSUE TITLE
Modernize deprecated getMetrics(DisplayMetrics) in Display

### ISSUE THREAD

**Issue by HollowMan6** [Igalia/wolvic#799]
getMetrics(DisplayMetrics) in Display has been deprecated. Use WindowMetrics#getBounds() to get the dimensions of the application window. Use WindowMetrics#getDensity() to get the density of the application window.

## Location
https://github.com/Igalia/wolvic/pull/787/files#r1251789601

## Possible Solution
As suggested in: 
https://developer.android.com/reference/android/view/Display

**Comment by HollowMan6** [comment]
WindowMetrics#getDensity() is only available in API 34, while we are using 33 currently.

**Comment by haanhvu** [comment]
I'll work on this
