### ISSUE TITLE
HTML Geolocation API doesn't work even with the release version (1.4) in the app store

### ISSUE THREAD

**Issue by MikeRatcliffe** [Igalia/wolvic#815]
Blocks #684

This is possibly only an issue on Quest 1, but I have no way to test it on the Quest 2.

It appears that geolocation doesn't work even with the release version in the app store (1.4).

I tested using https://www.audero.it/demo/geolocation-api-demo.html 

The error returned by the API is `User denied geolocation prompt` even though permissions have been granted.

Manually adding the permission to Wolvic also fails:

```sh
$ adb -s 192.168.1.181:5555 shell pm grant com.igalia.wolvic.metastore android.permission.ACCESS_COARSE_LOCATION
Security exception: Package com.igalia.wolvic.metastore has not requested permission android.permission.ACCESS_COARSE_LOCATION
```

**Comment by MikeRatcliffe** [comment]
I'll take a look into this as I am working on #684, which is blocked by this bug.

**Comment by svillar** [comment]
Oh wow, we're indeed removing both COARSE and FINE location permissions for the Oculus packages. We have had this for more than a year now, I wonder why this was done...

**Comment by MikeRatcliffe** [comment]
> Meta does not allow submitted apps to ask for neither COARSE nor FINE location permissions.

Aha, I've learned something new today... closing.
