### ISSUE TITLE
Keyboard layout doesn't match the system's language 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#845]
## Configuration

Wolvic version:  main branch
Wolvic build ID: 

Hardware:  Oculus Quest2

## Steps to Reproduce

1. Launch wolvic
2. Confirm the keyboard layout matches the system's language  
3. Launch the system settings  and change the language 
4. Reboot
5. Launch Wolvic 
6. Type in the url bar

## Current Behavior

The keyboard shows English layout

## Expected Behavior

The keyboard's layout should match the language setting (Spanish)

## Context

This is not happening in 1.4.1 so probably a regression introduced recently.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by HollowMan6** [comment]
So maybe caching the layout itself can be a new feature? (not sure?)

I can reproduce the "Welcome page doesn't match the system's language" issue. Will try to fix that.

**Comment by HollowMan6** [comment]
PR #855 should fix this issue. I have also tested that PR combining PR #812 and it all works fine, so PR #812 should not be related to this issue and it's ready for landing.

https://github.com/Igalia/wolvic/pull/812#pullrequestreview-1533861828
