### ISSUE TITLE
Disable hand tracking on demand

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#867]
**Is your feature request related to a problem? Please describe.**
Wolvic implements some navigation actions through handtracking gestures (eg, left-hand gesture to trigger back-navigation). Doing the gesture accidentally may cause a video being cut or losing some form data being filled due to unsolicited back-navigation.

**Describe the solution you'd like**
A way for the user to disable on demand the actions associated to hand-tracking gestures. 

**Describe alternatives you've considered**

**Additional context**
Some comments from users via the 'feedback form':

>  too many gestures are bound to the back button! I'm trying to watch a movie, I raise my hand to scratch my nose, the movie closes. Can we maybe have a bindings screen or something? Or a lock mode

> I use a bluetooth keyboard with my headset.  When I put my controller down to type in a text field or textarea, or even in the URL bar, the hand tracking takes over and registers nonsensical gestures as I type.  Even as I've been typing this message, the hand tracking has stolen focus, scrolled, and repositioned the text cursor about every third word.

**Comment by svillar** [comment]
Is this really still an issue after adding the GestureManager?

**Comment by javifernandez** [comment]
> Is this really still an issue after adding the GestureManager?

It's less severe for the devices supporting the MSFT extension, but still a problem for the other. 

And in any case, there could be use cases where it might be interesting to disable handtracking.

**Comment by svillar** [comment]
MSFT extension has nothing to do with this, will only be used for rendering the hand mesh.

**Comment by javifernandez** [comment]
> MSFT extension has nothing to do with this, will only be used for rendering the hand mesh.

Sorry, I mean the XR_HAND_TRACKING_AIM_SYSTEM_GESTURE_BIT_FB extension

**Comment by javifernandez** [comment]
We have received another request for this feature by an user of our 1.4.1 version:

> add a clap feature to disable and enable hand visiblity predictive suggests for typing

**Comment by javifernandez** [comment]
Another request from the feedback form, this time using the 1.4.2 version on Oculus:

> I am sure you get this request often, but tracked keyboards would be nice. Also, a way to shut off hand controls when typing.

**Comment by javifernandez** [comment]
A new request received via the feedback form:

> A way to disable hand tracking (if one already exists, apologies, I wasn't able to find it) would be very nice. Often, when I start watching content, I put down the controller. This causes the hand tracking to come on automatically and leads to random pointers, or sometimes even pausing, or just my hands glitching out, which is all very distracting.

**Comment by blueracer516** [comment]
I'm also interested in seeing a feature like this
