### ISSUE TITLE
Crash when forcing immersive mode in YouTube 360

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#871]
## Configuration

Wolvic version: 
Wolvic build ID: 

Hardware:  pico 4 fw 5.6.0 global

## Steps to Reproduce

1.  Load a video from YouTube 360 
2. Enable the immersive mode via the contextual menu
3.

## Current Behavior

Wolvic crashes

## Expected Behavior

Wolvic should reproduce the video in immersive mode 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I've just tested on a Pico4 with 5.6.0 and it works fine, no crash at all.

Let's reopen this if we get more reports, but without any extra data, and no way to reproduce it, we can barely do anything.
