### ISSUE TITLE
Passtrghough capabilities on Pico4

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#872]
**Is your feature request related to a problem? Please describe.**
There is no passthrough mode in Pico

**Describe the solution you'd like**
Enable the passthrough functionality in Pico devices

**Describe alternatives you've considered**

**Additional context**

**Comment by javifernandez** [comment]
It seems that the Pico4's runtime doesn't provide APIs to implement this feature, so I don't think we will supported in the short / medium term.

**Comment by svillar** [comment]
Closing as support was added. Expect it for 1.5.1
