### ISSUE TITLE
No playback in Apple TV streaming service 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#874]
## Configuration

Wolvic version:  1.4 1
Wolvic build ID: 

Hardware:  Oculus Quest2

## Steps to Reproduce

1. Play a video on the Apple TV platform
2.
3.

## Current Behavior

play back is a series of green and white block

## Expected Behavior

the video should be played back correctly.

## Context

We had a similar report in #761 which was supposedly fixed and the patch integrated in the 1.4.1 version. 

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bkardell** [comment]
![2c8c80f36468f032da7603ac4628582f](https://github.com/Igalia/wolvic/assets/870501/8675d6be-82f9-45ea-8de0-50ef3b8d01cc)

Tried 3 different shows, they're all garbled like this.  EME related maybe?

**Comment by svillar** [comment]
We know this is a Gecko bug. We're planning a Gecko upgrade that will fix it. Stay tunned
