### ISSUE TITLE
Dark mode support 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#875]
**Is your feature request related to a problem? Please describe.**
Wolvic doesn't have support for dark mode
 
**Describe the solution you'd like**
It'd be great to have the possibility of using dark mode in the browser

**Describe alternatives you've considered**

**Additional context**

**Comment by HollowMan6** [comment]
![image](https://github.com/Igalia/wolvic/assets/43995067/424311e0-a388-49cc-89ea-7bed0ad922ae)

We already have the Dark Reader extension, so this is already supported.
