### ISSUE TITLE
Rolling head in immersive mode causes scene to deform a bit

### ISSUE THREAD

**Issue by elima** [Igalia/wolvic#88]
## Configuration

Wolvic version: 0.9.5
Wolvic build ID: f9678560 (AC 63.0.0)
Hardware: Oculus Quest 2

## Steps to Reproduce
1. Open any immersive VR content in Wolvic (e.g, https://moonrider.xyz/)
2. Roll you head left and right (in the Roll axis, ears trying to touch shoulders).

## Current Behavior
The entire scene wobbles a bit, proportionality and shape of objects deform (e.g, a rectangular button becomes a rhomboid); causing a sub-optimal experience.

## Expected Behavior
The proportions and shape of objects in the scene are maintained.

## Comments
Oculus Browser doesn't show this behavior.

**Comment by RickAndTired** [comment]
Wolvic version 0.9.5
f9678560 (AC 63.0.0)
Oculus Quest 2 (tested on 4 different headsets)

I am also getting the same bug

This only happens on IPD setting 1 and 3
The bug is not present on IPD 2

This bug is also present in Firefox Reality

**Comment by msub2** [comment]
Same issue as #43

**Comment by elima** [comment]
> Same issue as #43

Right, I overlooked that one. Closing as duplicate of #43.
