### ISSUE TITLE
Some Page Loads Slowly

### ISSUE THREAD

**Issue by mattermon** [Igalia/wolvic#887]
## Configuration
Wolvic version: 1.4.1
Wolvic build ID: 
Hardware:

## Steps to Reproduce
1. visit https://www.mzgf.com/world
2. open webvr content, such as https://vr.mzgf.com/?projectCode=00g1301M&projectType=ALL

## Current Behavior
Page loads slowly, even up to minutes, as mentioned https://github.com/Igalia/wolvic/issues/548

## Possible Solution
I have tried some methods 
1. On `gecko-dev` project, revert some [commits](https://github.com/mozilla/gecko-dev/compare/master...Igalia:gecko-dev:FIREFOX_103_0_2_RELEASE) , means that use Mozilla offical release on branch FIREFOX_103_0_2_RELEASE
*Webvr content still loading slowly*
2. On `Wolvic` project, remove `dependencySubstitutions` options in `local.properties` 
*Webvr content loading normally, ignore webvr content abnormal*

I doubt is there some  build dependencies or the version difference of GeckoView after add `dependencySubstitutions` options?

**Comment by svillar** [comment]
BTW, it is not possible that you could load webxr content without the dependency substitutions, Wolvic will work in 2D browsing mode but won't allow you to load WebXR content.

**Comment by mattermon** [comment]
1. Yes, when substitutions options not used, GeckoView version is 105.0.20220822095220.
2. When loading a WebXR/WebVR content, after page loaded, there will be a button such as "Enter VR" etc. Until the button clicked, will enter vr mode(Immersive Mode).
![截图 2023-08-01 18-42-20](https://github.com/Igalia/wolvic/assets/8621214/77e12e9d-c08e-48a3-8569-2a3c387ab008)

**Comment by mattermon** [comment]
Any ideas on this problem？

**Comment by svillar** [comment]
As far as I've seen that page is still using WebVR.

**Comment by svillar** [comment]
> As far as I've seen that page is still using WebVR.

or maybe we need an UA override to get the proper WebXR version, I'll check that.

**Comment by mattermon** [comment]
Hi svillar,

You are right，_https://vr.mzgf.com/?projectCode=00g1301M&projectType=ALL_ is using WebVR.
While as you have met in https://github.com/Igalia/wolvic/issues/548，the page loading very slow（before entering vrmode）.
I wondered if this has relationship with WebVR or WebXR.

BR.

**Comment by mattermon** [comment]
I tried to cherry picked  [#894](https://github.com/Igalia/wolvic/pull/894). After modify UA for mzfg, it worked for entering immersive mdoe, it's great!

But, sorry for my poor English. Maybe I did not describe very clearly.
What i meat is that, after click any page like _https://vr.mzgf.com/?projectCode=00fli01M&projectType=ALL_  from _https://www.mzgf.com/mj/world_, it casts a long time before show anything(the whole page is white). 

As shown in [video](https://youtu.be/ttoeAwa9L24)

**Comment by mattermon** [comment]
@svillar Would you please take a look at the video at your convenience?
