### ISSUE TITLE
Need  instructions to override environment for PICO4 (not quest2)

### ISSUE THREAD

**Issue by rESMILE3160** [Igalia/wolvic#891]
## Configuration

Wolvic version: 
Wolvic build ID: 

Hardware: 

## Steps to Reproduce

1.
2.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Not sure what do you mean by override environment. Could you clarify? Are you talking about the build process or about the environments inside wolvic?

**Comment by svillar** [comment]
3 weeks without reply from reporter, let's close this.

Please reopen if you still think that there is something to be done here.
