### ISSUE TITLE
DateTime picker prompt dialog is not properly triggered

### ISSUE THREAD

**Issue by HollowMan6** [Igalia/wolvic#896]
## Configuration

Wolvic version: main
Wolvic build ID: 

Hardware: Should be hardware-agnostic, at least in Meta Quest 2

## Steps to Reproduce

1. Open https://people.igalia.com/femorandeira/input/
2. Click on the date/time input
3. Complete the date/time picker prompt dialog
4. Click on the same input again

## Current Behavior

The dateTime picker prompt dialog is not triggered again, the only way to get the dateTime picker prompt dialog show again is to re-focus the input (click on anywhere outside of the input to make the input lose focus, and then click on the input to make it get focused again)

## Expected Behavior

The dateTime picker prompt dialog should get triggered every time we click on the input.

## Possible Solution

It's still not clear what caused this.

## Context

[Previous investigation](https://github.com/Igalia/wolvic/pull/877#discussion_r1286178365) suggests that it is caused by `onDateTimePrompt()` not properly called. So maybe some issue related to the gecko.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Question is, does it only happen with date inputs? I guess it happens also with file pickers?

**Comment by HollowMan6** [comment]
> Question is, does it only happen with date inputs? I guess it happens also with file pickers?

I think it doesn't happen with file pickers, since the button isn't focused after we make the choice. So far, I think it only happens with date/time inputs.

**Comment by HollowMan6** [comment]
I think at least it can be a fix if we make the date/time inputs unfocused after we complete the picker dialog, but I'm not sure how since the only thing we can work on is the callback (`onDateTimePrompt()`)

**Comment by HollowMan6** [comment]
Now I can confirm this is purely a gecko issue, as I can reproduce the exact same issue as here in Firefox Android using my Android phone: https://apkcombo.com/firefox/org.mozilla.firefox/old-versions/105.1.0/

So close this.

**Comment by HollowMan6** [comment]
This should be fixed when we upgrade to a later version of gecko, as I can see it's fixed in latest version.

**Comment by HollowMan6** [comment]
Reopen and to be closed together with https://github.com/Igalia/wolvic/pull/917
