### ISSUE TITLE
Verification failed on chinese Pico 4 Pro

### ISSUE THREAD

**Issue by exstrim401** [Igalia/wolvic#897]
## Configuration

Wolvic version: 1.4.1
Wolvic build ID: 

Hardware: Pico 4 Pro

## Steps to Reproduce

1. Open app
2. Wait about one minute

## Current Behavior

Verification failed error after a minute. If I open app without an account it requires me to sign in
![image](https://github.com/Igalia/wolvic/assets/57351693/e226b10c-1f9f-478d-b9fd-d46e751e1f31)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
The app is not officially released in China yet, so I guess you're installing it on the device via the provided APK right?

According to [this]() however user entitlement only applies to apps that have been published in the store "User entitlement checks only apply to the apps that have been published on the PICO Store. For unpublished apps, users always pass entitlement checks regardless of their entitlement status."

Maybe this does not apply for mainland China though...

**Comment by exstrim401** [comment]
Yeah I installed picoxr APK from the releases. I guess it will work if I rename package name

**Comment by exstrim401** [comment]
Closing as it works fine now
