### ISSUE TITLE
"toolchain-win64-fix-stacks" artifacts not found when building gecko-dev on Windows

### ISSUE THREAD

**Issue by intsven** [Igalia/wolvic#900]
## Configuration

Wolvic version: 
Wolvic build ID: 

Hardware: 

## Steps to Reproduce

1. git clone https://github.com/Igalia/gecko-dev/ on Windows 10
2. git checkout FIREFOX_103_0_2_RELEASE
3. [Gecko-dev] ./mach bootstrap [response 4: Android without artifacts]

## Current Behavior

ERROR!!!!!! Could not find artifacts for a toolchain build named `toolchain-win64-fix-stacks`. Local commits, dirty/stale files, and other changes in your check out may cause this error. Make sure you are on a fresh, current checkout of mozi lla-central. Beware that commands like `mach bootstrap` and `mach artifact` are unlikely to work on any versions of the code besides recent revisions of mozilla -central.

## Expected Behavior

Should not throw error.

## Context

I also tried it in WSL and got a similar error.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Sorry but you'd have to ask in another forum. This is about developing Wolvic. For support for building Firefox/GeckoView you'd better reach to mozillians.
