### ISSUE TITLE
Huawei VR 3dof Support

### ISSUE THREAD

**Issue by tianyaguiren** [Igalia/wolvic#919]
## Configuration

Wolvic version: 1.4.2
Wolvic build ID: 

Hardware: Huawei VR Glasses

## Steps to Reproduce

1.3dof Can't identify
2.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Sorry we don't understand what the problem is. Could you explain it a little bit better? We need more details of what's happening

**Comment by svillar** [comment]
closing due to the lack of feedback
