### ISSUE TITLE
How can I build an apk for Openxr device

### ISSUE THREAD

**Issue by DavidChen528** [Igalia/wolvic#921]
I have an AR device support OpenXR，this device is not quest or pico...
quest 1：Should I build apk use AOSP？
quest 2：when I build AOSP，it download openxr-sdk，but what is this：
 ExternalProject_Add(EXTOpenXRLoader
            SOURCE_DIR ${lib_src_DIR}
            BINARY_DIR ${lib_build_DIR}
            PATCH_COMMAND git reset --hard && git apply ${CMAKE_SOURCE_DIR}/../third_party/patches/0001-Fix-some-missing-field-initializer-warnings.patch
            STEP_TARGETS patch
            EXCLUDE_FROM_ALL TRUE
            )

how can I get 0001-Fix-some-missing-field-initializer-warnings.patch？

**Comment by svillar** [comment]
Hmm right we need to fix that because the third_party repo is not publicly accesible...

**Comment by svillar** [comment]
> Thanks for your answer，I have built an OpenXR Apk，and success running with 6dof，but when I open an webxr link，it show XR not support，I think isSessionSupported('immersive-vr') got false，how can I fix it？I query some issues about，since to replase Gecko？

You must use our branch of Gecko as specified in https://github.com/Igalia/wolvic/#dependency-substitutions

**Comment by DavidChen528** [comment]
> > Thanks for your answer，I have built an OpenXR Apk，and success running with 6dof，but when I open an webxr link，it show XR not support，I think isSessionSupported('immersive-vr') got false，how can I fix it？I query some issues about，since to replase Gecko？
> 
> You must use our branch of Gecko as specified in https://github.com/Igalia/wolvic/#dependency-substitutions

I try to build the gecko-dev on branch wolvic_release or mozilla-central，both failed show message：
Error running mach:

    mach environment --format json --verbose

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke ``./mach busted`` to check if this issue is already on file. If it
isn't, please use ``./mach busted file environment`` to report it. If ``./mach busted`` is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

mozbuild.base.BuildEnvironmentNotFoundException: config.status not available. Run configure.

  File "/home/david/work/WebXR/wolvic/third_party/mozilla-central/python/mozbuild/mozbuild/mach_commands.py", line 2175, in environment
    return func(command_context, sys.stdout, verbose)
  File "/home/david/work/WebXR/wolvic/third_party/mozilla-central/python/mozbuild/mozbuild/mach_commands.py", line 2249, in _environment_json
    json.dump(command_context, cls=EnvironmentEncoder, sort_keys=True, fp=out)
  File "/usr/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/david/work/WebXR/wolvic/third_party/mozilla-central/python/mozbuild/mozbuild/mach_commands.py", line 2242, in default
    result["substs"] = obj.substs
  File "/home/david/work/WebXR/wolvic/third_party/mozilla-central/python/mozbuild/mozbuild/base.py", line 389, in substs
    return self.config_environment.substs
  File "/home/david/work/WebXR/wolvic/third_party/mozilla-central/python/mozbuild/mozbuild/base.py", line 365, in config_environment
    raise BuildEnvironmentNotFoundException(

**Comment by DavidChen528** [comment]
before that，when I try ./mach bootstrap，it show：
Error running mach:

    ['--log-no-times', 'artifact', 'toolchain', '--from-task', 'False:public/build/node.tar.zst']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.
You can invoke |./mach busted| to check if this issue is already on file. If it
isn't, please use |./mach busted file artifact| to report it. If |./mach busted| is
misbehaving, you can also inspect the dependencies of bug 1543241.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/False/artifacts/public/chain-of-trust.json

  File "/home/david/work/WebXR/gecko-dev/python/mozbuild/mozbuild/artifact_commands.py", line 482, in artifact_toolchain
    record = ArtifactRecord(task_id, name)
  File "/home/david/work/WebXR/gecko-dev/python/mozbuild/mozbuild/artifact_commands.py", line 327, in __init__
    cot.raise_for_status()
  File "/home/david/work/WebXR/gecko-dev/third_party/python/requests/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
ERROR: Command '['/home/david/.mozbuild/srcdirs/gecko-dev-7ae90f98dd51/_virtualenvs/mach/bin/python', '/home/david/work/WebXR/gecko-dev/mach', '--log-no-times', 'artifact', 'toolchain', '--from-task', 'False:public/build/node.tar.zst']' returned non-zero exit status 1.
ERROR: If you can't fix the above, retry with --disable-bootstrap.

**Comment by DavidChen528** [comment]
my error like [Bug 1798993](https://bugzilla.mozilla.org/show_bug.cgi?id=1798993)

**Comment by svillar** [comment]
> my error like [Bug 1798993](https://bugzilla.mozilla.org/show_bug.cgi?id=1798993)

You should talk to mozilla folks about gecko build issues

**Comment by DavidChen528** [comment]
> > my error like [Bug 1798993](https://bugzilla.mozilla.org/show_bug.cgi?id=1798993)
> 
> You should talk to mozilla folks about gecko build issues

OK，but Could you please send me an AAR base on your branch of Gecko？I can test first

**Comment by FanEric** [comment]
[](https://github.com/Igalia/wolvic/wiki/Developer-workflow#building-geckol) you can follow this for building Gecko
