### ISSUE TITLE
Add Yandex to the list of available search engines 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#922]
**Is your feature request related to a problem? Please describe.**
Currently Wolvic doesn't support Yandex as one of the options we offer the users to select as default search engine

**Describe the solution you'd like**
Include Yandex as one of the options to select the default search engine

**Describe alternatives you've considered**
It's possible to use the search engine through the yandex.com site

**Comment by svillar** [comment]
I think Yandex is already included if the device language is set to russian, but will have to double check.

**Comment by HollowMan6** [comment]
I can see we only have Google, DuckDuckGo, and Wikipedia when we set the language to Russian.

**Comment by HollowMan6** [comment]
Looks like it's related to upstream: https://github.com/mozilla-mobile/firefox-android/blob/0d89d4d85116703ac7323ba4a66a832149208c5d/android-components/components/feature/search/src/main/assets/search/list.json#L733 Do we want to send a patch to upstream to add Yandex to the list?

**Comment by HollowMan6** [comment]
Upstream PR opened at https://github.com/mozilla-mobile/firefox-android/pull/3367

**Comment by HollowMan6** [comment]
The [upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1849729) says that Yandex was intentionally removed as a built-in search provider from Firefox in Version 98.0.1 (desktop) / 98.2.0 (Android):

> From 98 release notes (https://www.mozilla.org/en-US/firefox/98.0/releasenotes/):

> Firefox allows users to choose from a number of built-in search engines to set as their default. In this release, some users who had previously configured a default engine might notice their default search engine has changed since Mozilla was unable to secure formal permission to continue including certain search engines in Firefox.

As of that, I'm not sure if we still want to include Yandex into the list of available search engines

**Comment by javifernandez** [comment]
I agree, not sure whether we are ready to close the issue as WONTFIX, but I don't see many reasons so far to support it.

**Comment by HollowMan6** [comment]
Close as wontfix as discussed in #930
