### ISSUE TITLE
Playing any Youtube video on a web page crashes

### ISSUE THREAD

**Issue by Harley-Jing** [Igalia/wolvic#925]
## Configuration
Wolvic version: 1.4.2
Hardware: Quest 2 (Wolvic-oculusvr-arm64-gecko-generic-debug)

## Current Behavior
Playing any Youtube video on a web page crashes

## Error Logs and Stack Traces
  Cmdline: com.igalia.wolvic
  pid: 20946, tid: 20999, name: Gecko  >>> com.igalia.wolvic <<<
        00 pc 000000000223d0d8  /data/app/~~cqEjLEjLlZ3itwSm49jg3A==/com.igalia.wolvic-1Y2m8MtVEd8-5Lh3fVcDLQ==/lib/arm64/libxul.so
        01 pc 0000000002263094  /data/app/~~cqEjLEjLlZ3itwSm49jg3A==/com.igalia.wolvic-1Y2m8MtVEd8-5Lh3fVcDLQ==/lib/arm64/libxul.so

## Details
I tested your Wolvic-oculusvr-arm64-world-gecko-generic-release package, which played YouTube videos without crashing。
![Snipaste_2023-08-22_14-40-46](https://github.com/Igalia/wolvic/assets/49121194/c5459e3a-6e7c-485d-be79-deb59d784fbb)
Why is this the case? Do I need some special settings for Android packaging?

**Comment by Harley-Jing** [comment]
> What gecko are you using? Are you getting it from maven or are you building it by yourself? If you use the one from Maven then WebXR won't work.

By looking at the build.gradle file, gecko did get it from Maven. How should I modify to use the local one?
![Snipaste_2023-08-22_17-53-29](https://github.com/Igalia/wolvic/assets/49121194/92ab1b21-311e-433e-8ece-28c2f09e2a5c)

**Comment by svillar** [comment]
> > What gecko are you using? Are you getting it from maven or are you building it by yourself? If you use the one from Maven then WebXR won't work.
> 
> By looking at the build.gradle file, gecko did get it from Maven. How should I modify to use the local one? ![Snipaste_2023-08-22_17-53-29](https://user-images.githubusercontent.com/49121194/262326116-92ab1b21-311e-433e-8ece-28c2f09e2a5c.png)

https://github.com/Igalia/wolvic/#dependency-substitutions

**Comment by Harley-Jing** [comment]
Thank you very much for your reply, this should be the cause of the problem now. But in the process of compiling `GeckoView`, I encountered a lot of errors, probably because the current compilation environment is on the Windows platform.
What platform do you compile `GeckoView`?

**Comment by Harley-Jing** [comment]
> > > What gecko are you using? Are you getting it from maven or are you building it by yourself? If you use the one from Maven then WebXR won't work.
> > 
> > 
> > By looking at the build.gradle file, gecko did get it from Maven. How should I modify to use the local one? ![Snipaste_2023-08-22_17-53-29](https://user-images.githubusercontent.com/49121194/262326116-92ab1b21-311e-433e-8ece-28c2f09e2a5c.png)
> 
> https://github.com/Igalia/wolvic/#dependency-substitutions

Thank you very much for your reply, this should be the cause of the problem now. But in the process of compiling GeckoView, I encountered a lot of errors, probably because the current compilation environment is on the Windows platform.
What platform do you compile GeckoView?

**Comment by Harley-Jing** [comment]
When I compile https://github.com/mozilla/gecko-dev/tree/FIREFOX_ESR_115_0_X_RELBRANCH , there is the following error. How did you solve it? Thanks.
## Error Logs and Stack Traces
ERROR!!!!!! Could not find artifacts for a toolchain build named `toolchain-macosx64-aarch64-minidump-stackwalk`. Local commits, dirty/stale files, and other changes in your checkout may cause this error. Make sure you are on a fresh, current checkout of mozilla-central. Beware that commands like `mach bootstrap` and `mach artifact` are unlikely to work on any versions of the code besides recent revisions of mozilla-central.

**Comment by svillar** [comment]
> When I compile https://github.com/mozilla/gecko-dev/tree/FIREFOX_ESR_115_0_X_RELBRANCH , there is the following error. How did you solve it? Thanks.
> 
> ## Error Logs and Stack Traces
> ERROR!!!!!! Could not find artifacts for a toolchain build named `toolchain-macosx64-aarch64-minidump-stackwalk`. Local commits, dirty/stale files, and other changes in your checkout may cause this error. Make sure you are on a fresh, current checkout of mozilla-central. Beware that commands like `mach bootstrap` and `mach artifact` are unlikely to work on any versions of the code besides recent revisions of mozilla-central.

You should talk to Mozilla folks about that. We only provide support for the exact versions that we use to generate packages as they're the ones that we have tested and patches.
