### ISSUE TITLE
华为glass无法显示操作手柄

### ISSUE THREAD

**Issue by bizhou78** [Igalia/wolvic#926]
最新版本无法检测到手柄，希望改进，我还要退回到以前版本才能使用。瓦的设备是华为glass。

**Comment by svillar** [comment]
According to google translate: "The latest version cannot be detected. I hope to improve it. I will return to the previous version to use. The equipment of the tile is Huawei Glass"

Not very much we can do with this. Please reopen if you have additional information or a more detailed report.
