### ISSUE TITLE
Search in page

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#929]
**Is your feature request related to a problem? Please describe.**
In Wolvic is not possible to search for specific words in a 2D web site

**Describe the solution you'd like**
Implement a Search in page functionality

**Additional context**
This has been requested by users via feedback form

> it would be great to have a search in page option

**Comment by javifernandez** [comment]
Apparently GeckoSession has an API for that (GeckoSession#getFinder()).

**Comment by HollowMan6** [comment]
Just investigated this a little bit. Actually, there is an Android Component called [feature-findinpage](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/findinpage/README.md) which is expected to be used in this case. However, it depends on browserStore and [EngineView](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/feature/session/README.md) which we are actually not currently using, and I think we will need some structural changes and refactor works to get those working.

Of course, we can use GeckoSession API such as GeckoSession#getFinder(), but then we will reinvent the wheels for the UI and logic and I don't think it will be very easy to maintain this later.

**Comment by HollowMan6** [comment]
opened PR at #947, solved this with a mixture of feature-findinpage (works as the frontend) and GeckoSession#getFinder() (replaces backend logics in feature-findinpage)
