### ISSUE TITLE
Zoom in and out

### ISSUE THREAD

**Issue by tarikjones** [Igalia/wolvic#938]
Videos are always way too zoomed out. I know for some people it’s way too zoomed in. It would be great if there was a way to zoom in and out and even move the display up and down. 

I know you can resize the browser, but for videos, it goes back to the original size. Zooming in and out of videos would be a great feature.

**Comment by javifernandez** [comment]
Thank you for filing the issue. We are already working on a change (see [PR#743](https://github.com/Igalia/wolvic/pull/734) for details) to allow users to change the distance of the browser widows.
