### ISSUE TITLE
Implement the feedback form with a native UI dialog 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#940]
**Is your feature request related to a problem? Please describe.**
Clicking on the feedback form button interrupt video playing

**Describe the solution you'd like**
Launch an android native UI dialog allowing the video to continue playing in background.

**Comment by svillar** [comment]
I don't think we need a native UI for that, just open the feedback form in a new tab

**Comment by javifernandez** [comment]
I'm afraid creating a background tab has drawbacks in terms of usability, since the user will have to look for the form in the tabs list. I assume that the main case when the user clicks on the feedback button is to use it in that precise moment. 

If we are worried about accidental clicks, I'd argue that we have the same problem with the release notes button, although in this case it appears just once.

If the user case is filling the feedback form while watching / listening a video, I think this is only possible via a non-modal dialog.

**Comment by svillar** [comment]
> I'm afraid creating a background tab has drawbacks in terms of usability, since the user will have to look for the form in the tabs list. I assume that the main case when the user clicks on the feedback button is to use it in that precise moment.

No I mean opening it in a new tab, not in the background. The new tab will pause the current action

**Comment by javifernandez** [comment]
> > I'm afraid creating a background tab has drawbacks in terms of usability, since the user will have to look for the form in the tabs list. I assume that the main case when the user clicks on the feedback button is to use it in that precise moment.
> 
> No I mean opening it in a new tab, not in the background. The new tab will pause the current action

But the enhancement request would be precisely to avoid pausing the current action.

**Comment by HollowMan6** [comment]
> Actually, if we want to stop interrupting the video playing, we can simply open the feedback form web page in a new window, and if we already have the maximum possible window, we again open the feedback form in a new tab.

Tried to implement this and it works well, no video-playing interruption now as long as the maximum window is not reached. @javifernandez

**Comment by javifernandez** [comment]
> I can see the current behavior is that we will open the feedback form in a new tab whenever the user clicks the icon. Personally, I don't prefer a native UI dialog for feedback form because it's less flexible.
> 
> Actually, if we want to stop interrupting the video playing, we can simply open the feedback form web page in a new window, and if we already have the maximum possible window, we again open the feedback form in a new tab.

We considered that approach when we initially discussed this new feature and the conclusion was that our limit of 3 windows opened at the same time was too small to use one for the feedback form. Perhaps we should revisit this  topic again, considering the use case described in this issue.

**Comment by HollowMan6** [comment]
> We considered that approach when we initially discussed this new feature and the conclusion was that our limit of 3 windows opened at the same time was too small to use one for the feedback form. Perhaps we should revisit this topic again, considering the use case described in this issue.

As for the use case described in this issue (stop interrupting video playing), considering the scenario when we already have the maximum (3) windows opened, we shouldn't have more than 1 window playing video. So, we can then iterate through windows and open the feedback form in the new tab where the video is not playing in that window (hopefully it's possible to detect video playing in a window).

**Comment by HollowMan6** [comment]
> > We considered that approach when we initially discussed this new feature and the conclusion was that our limit of 3 windows opened at the same time was too small to use one for the feedback form. Perhaps we should revisit this topic again, considering the use case described in this issue.
> 
> As for the use case described in this issue (stop interrupting video playing), considering the scenario when we already have the maximum (3) windows opened, we shouldn't have more than 1 window playing video. So, we can then iterate through windows and open the feedback form in the new tab where the video is not playing in that window (hopefully it's possible to detect video playing in a window).

opened another PR #960 so that we can have minimum user behavior change compared to the original one while still solving the issue:

If there's no video playing in the current window, we still open the new page in a new tab.

If we have video playing in current window, ensure we don't open a new tab in a window that has active video, but open it in the Window that has no video playing.

If all the current opened Windows have video playing, we have to open uri in a new window. If we have maximum window number, then open the uri as a new tab in current window.

**Comment by javifernandez** [comment]
> > > We considered that approach when we initially discussed this new feature and the conclusion was that our limit of 3 windows opened at the same time was too small to use one for the feedback form. Perhaps we should revisit this topic again, considering the use case described in this issue.
> > 
> > 
> > As for the use case described in this issue (stop interrupting video playing), considering the scenario when we already have the maximum (3) windows opened, we shouldn't have more than 1 window playing video. So, we can then iterate through windows and open the feedback form in the new tab where the video is not playing in that window (hopefully it's possible to detect video playing in a window).
> 
> opened another PR #960 so that we can have minimum user behavior change compared to the original one while still solving the issue:
> 
> If there's no video playing in the current window, we still open the new page in a new tab.
> 

I like this new approach very much.
