### ISSUE TITLE
Monado support

### ISSUE THREAD

**Issue by oilipheist** [Igalia/wolvic#942]
**Is your feature request related to a problem? Please describe.**
Support Monado to create pathway for freedesktop targets and unlock more form factors e.g steamdeck, nreal air drivers etc

**Describe the solution you'd like**
Support [Monado](https://gitlab.freedesktop.org/monado/monado)  

**Describe alternatives you've considered**
Build an alternative abstraction for steamvr, nreal etc

**Comment by svillar** [comment]
So I think there is some confusion here. Wolvic uses an OpenXR backend for most of the supported ports. Monado is just another OpenXR runtime, i.e. a particular implementation of the OpenXR API. This means that we don't need to do anything special to support it.

Actually we know Wolvic runs in devices using Monado like the Lenovo A3
