### ISSUE TITLE
The 'Address bar auto-complete' feature can not be disabled 

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#943]
## Configuration

Wolvic version: 1.4.2
Wolvic build ID:  

Hardware: Oculus Quest2

## Steps to Reproduce

1. Open the Settings > Privacy and Security  dialog
2. Switch off the "Address bar auto-complete" setting
3. Close the dialog
4. Type something in the url bar

## Current Behavior

The auto-completion feature is still enabled and suggesting potential text

## Expected Behavior

There should not be any auto-completed text suggestion

**Comment by HollowMan6** [comment]
Currently, it seems like only search engine suggestions are disabled.

Now fix is available in PR #946 so the address suggestion is also disabled.
