### ISSUE TITLE
Environments download should use `getFilesDir()`/`getCacheDir()` to store the downloaded zip file

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#963]
Remote environments are downloaded in form of a zip file containing the 6 faces of the cube that contains the skybox.

That zip file is currently downloaded to an external location that requires us to ask for READ/WRITE permissions. However that should not be like that. That zip file should not be available to any other app. It isn't a big deal (maybe privacy?) but we should not expose those files that only concern Wolvic.

We should use instead a directory inside the location returned by either `getFilesDir()` or `getCacheDir()`, likely the latter.

**Comment by svillar** [comment]
Making @javifernandez aware of this since he's been working on this.

**Comment by javifernandez** [comment]
The PR #954 that is currently under review, tries to follow this approach by using ```getExternalFilesDir```

**Comment by svillar** [comment]
> The PR #954 that is currently under review, tries to follow this approach by using `getExternalFilesDir`

The reason why I suggested `getFIlesDir` over that one is because of [this](https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String))

The docs say
> This is like [getFilesDir()](https://developer.android.com/reference/android/content/Context#getFilesDir()) in that these files will be deleted when the application is uninstalled, however there are some important differences:

> Shared storage may not always be available, since removable media can be ejected by the user. Media state can be checked using [Environment#getExternalStorageState(File)](https://developer.android.com/reference/android/os/Environment#getExternalStorageState(java.io.File)).
> There is no security enforced with these files. For example, any application holding [Manifest.permission.WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE) can write to these files.
> If a shared storage device is emulated (as determined by [Environment#isExternalStorageEmulated(File)](https://developer.android.com/reference/android/os/Environment#isExternalStorageEmulated(java.io.File))), it's contents are backed by a private user data partition, which means there is little benefit to storing data here instead of the private directories returned by [getFilesDir()](https://developer.android.com/reference/android/content/Context#getFilesDir()), etc.

**Comment by javifernandez** [comment]
However, we unzip the environment files in the external storage, so it made sense to use the same for the temporary download. Should we change this one as well then ?

**Comment by svillar** [comment]
> However, we unzip the environment files in the external storage, so it made sense to use the same for the temporary download. Should we change this one as well then ?

For environments I think we should use cached private storage because we don't want external apps to access it
