### ISSUE TITLE
False positive network status when starting Wolvic

### ISSUE THREAD

**Issue by HollowMan6** [Igalia/wolvic#964]
## Configuration

Wolvic version: 1.4.2 & main
Wolvic build ID: Includes store version

Hardware: Meta Quest 2

## Steps to Reproduce

1. Restart the headset without connecting to any network.
2. Start the Wolvic

## Current Behavior

Wolvic shows that we are connected to the network (WIFI name shows as \<unknown ssid>), while it's actually not connected to the Internet at all.

## Expected Behavior

Wolvic shows that we are not connected to the Internet when there's no connection

## Possible Solution

There's no issue when we have https://github.com/Igalia/wolvic/pull/906

So this is related to: https://github.com/Igalia/wolvic/issues/803#issuecomment-1691524795 The old method can be actually the problematic one and those can be correct reports (maybe caused by unstable WIFI connections).

https://github.com/Igalia/wolvic/issues/803#issuecomment-1691524795

## Context

![com igalia wolvic metastore-20230910-191007](https://github.com/Igalia/wolvic/assets/43995067/ba8cdbec-582d-435b-9184-8328f1b588c0)

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by HollowMan6** [comment]
cc @svillar

**Comment by svillar** [comment]
Are you suggesting to reapply #906 ? 

I was having issues with that, I don't think I have an unstable connection here, but I guess we can double check with the rest of the team about what their experiences are.

**Comment by HollowMan6** [comment]
> Are you suggesting to reapply #906 ?

I'm not suggesting reapplying #906, just want to notify you that the old method also has some issues. I think we can either figure out what went wrong in the old method to fix it or we simply decide to move on to the #906 and try to fix that for your case instead. Maybe the former way is more realistic to me since I can't reproduce your case while I can have a stable way to reproduce this issue.

**Comment by svillar** [comment]
> > Are you suggesting to reapply #906 ?
> 
> I'm not suggesting reapplying #906, just want to notify you that the old method also has some issues. I think we can either figure out what went wrong in the old method to fix it or we simply decide to move on to the #906 and try to fix that for your case instead. Maybe the former way is more realistic to me since I can't reproduce your case while I can have a stable way to reproduce this issue.

OK please then go ahead. Thanks!
