### ISSUE TITLE
Some Web XR Links do not work in Kiosk Mode

### ISSUE THREAD

**Issue by johnmanagexr** [Igalia/wolvic#970]
## Configuration

Wolvic version: 1.4.1
Wolvic build ID: fcdb7bb8 (AC 75.0.22)

Hardware: Oculus Quest 2

## Steps to Reproduce

1. Plug a device into your computer
2. Launch this webXR Link via an intent sent from adb in non-kiosk mode, see that it works

adb shell am start -a android.intent.action.VIEW -d "wolvic://com.igalia.wolvic/\?kiosk=false\&url=https://promisingpeople.agilixbuzz.com/" com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity

3. Launch the same link in kiosk mode:

adb shell am start -a android.intent.action.VIEW -d "wolvic://com.igalia.wolvic/\?kiosk=true\&url=https://promisingpeople.agilixbuzz.com/" com.igalia.wolvic/com.igalia.wolvic.VRBrowserActivity

## Current Behavior

The link shows a loading animation followed by a white screen when launched in kiosk mode. It loads correctly, as expected when, kiosk=false. Also notice with subsequent launches setting kiosk to false, kiosk stays enabled.

## Expected Behavior

The link loads both for kiosk and non-kiosked modes

<details open>

```
```

</details>

**Comment by HollowMan6** [comment]
Not reproducible in main, maybe this has already been fixed? (Sounds similar to: https://github.com/Igalia/wolvic/pull/914)

**Comment by johnmanagexr** [comment]
Amazing, thank you for the update! We'll test again after the next release.

**Comment by svillar** [comment]
> Amazing, thank you for the update! We'll test again after the next release.

Have you tested it in 1.5 ?

**Comment by johnmanagexr** [comment]
I didn't know it released! We'll get to testing straight away - thank you :)

**Comment by johnmanagexr** [comment]
Yes, and it did work! Thank you for the quick fix, and for informing us that it was in.
