### ISSUE TITLE
Restore the FxR inherited versionCode auto generation

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#977]
Long time ago we decided not to use the automatically generated version codes that FxR used to build from the current date and manually specify our owns. We thought that could give us more control over the packages we generate. The thing is that it does not really help, and what's worst, it makes the process of uploading to stores more complex, because you must always upload higher and higher versionCode numbers.

I think it's time to go back to the automatically generated version codes again.

Note that the version code is shown in the settings, so PR #310 should be re-examined

Also see [this commit](https://github.com/Igalia/wolvic/commit/cad2d654781e491c9b42da0048895a6ea8d9af23)

**Comment by HoussemNasri** [comment]
Hi @svillar, is this issue still relevant? It's been a while since it was opened and there is already a commit that marks it as resolved. If it's still relevant, I would like to work on this.

**Comment by svillar** [comment]
> Hi @svillar, is this issue still relevant? It's been a while since it was opened and there is already a commit that marks it as resolved. If it's still relevant, I would like to work on this.

It wasn't fix, we closed it because there was nobody working on that anymore. There is a patch but the problem is that it does really interfere with local development because each build gets a new version code and thus caching build results does not properly work. The idea IIRC was to have a specific version code for dev builds. Feel free to pick this up.
