### ISSUE TITLE
<name>.center domains are unable to be typed in the URL bar

### ISSUE THREAD

**Issue by NathanaelA** [Igalia/wolvic#990]
## Configuration
Wolvic version: 1.42
Wolvic build ID: 102   

Hardware: Oculus 2

## Steps to Reproduce
- Type xyz.center , http://xyz.center or https://xyz.center and it will default to searching for it at a search engine rather than loading the domain.

## Current Behavior
Typing a ".center" domain name in causes it to search for it via the default search engine

## Expected Behavior
Navigates to that website.

## Possible Solution
N/A

## Context
Basic navigation

## Error Logs and Stack Traces
<details open>

```
```

</details>

**Comment by svillar** [comment]
Good catch! Thanks for the report.
