### ISSUE TITLE
Date picker can be too tall

### ISSUE THREAD

**Issue by felipeerias** [Igalia/wolvic#998]
The prompt to pick a date and time is too tall and requires scrolling.

![Screenshot_com igalia wolvic_2023 09 20-23 58 01 004_647](https://github.com/Igalia/wolvic/assets/1412060/5f18d11f-ad52-4f3a-9e3e-62a40e9a831c)

![Screenshot_com igalia wolvic_2023 09 20-23 57 55 365_502](https://github.com/Igalia/wolvic/assets/1412060/a73039d4-b120-41b8-8ecf-7f13f41d377b)

Could we adjust the layout to prevent this? Maybe we could try to organize the UI elements horizontally? Something like this:

```
 —————————————
|      |      |
| DATE | TIME |
|      |      |
———————————————
|   BUTTONS   |
 —————————————
```

For comparison. this is how the prompt looks like in the Pico browser:

![Screenshot_com pico browser overseas_2023 09 21-00 19 35 061_410](https://github.com/Igalia/wolvic/assets/1412060/e46d1f35-c0ca-4817-bc04-b4a149af0c74)

**Comment by HollowMan6** [comment]
> Could we adjust the layout to prevent this? Maybe we could try to organize the UI elements horizontally? Something like this:
> 
> ```
>  —————————————
> |      |      |
> | DATE | TIME |
> |      |      |
> ———————————————
> |   BUTTONS   |
>  —————————————
> ```

Now we use Android's native DatePicker and TimePicker widgets https://github.com/Igalia/wolvic/pull/877/files#diff-e99ea6d075f9cf9f169d70e2959285d53308448338b3a36ef3a7e0994580c960R10-R12, and that's also how Firefox Android works in this case (no Android Components available).

![image](https://github.com/Igalia/wolvic/assets/43995067/ef4b42c5-115b-4808-adc4-a56b079b9b33)

We would need our own implementation of the widgets if we want to have that, and that can be a lot of work to reinvent the wheels.

**Comment by svillar** [comment]
My first impression was identical to @felipeerias 's but then I realized that that's how the android widgets look like. Having our own widgets is a no-goal really, so I'd look for mitigations instead of replacements.
